Использование ссылочных и нессылочных типов в составном типе.
1C-Company/v8-code-style pull request #1013
Opened 2022-03-29 04:55 UTC by iArtemv

## Что сделано

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-04-15 13:48 UTC, marmyshev requested changes
По сути - ок, небольшие мелочи поправить нужно)

2022-04-15 13:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectRefNonRefTypesCheck.java
> +            String typeItemName = McoreUtil.getTypeName(typeItem);
здесь может быть null

2022-04-15 13:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectRefNonRefTypesCheck.java
> +            String[] partsName = typeItemName.split("\\."); //$NON-NLS-1$
кажется, это делает метод McoreUtil.getCategory()

2022-04-15 13:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectRefNonRefTypesCheck.java
> +            .features(BASIC_FEATURE__TYPE);
а точно ли вся эта фича переписывается при изменении одного типа? Есть подозрение что добавляются/удаляются элементы коллекции, а сама фича не модифицируется - поэтому реакции на исправление ошибки может не быть. Прошу проверить, т.к ошибка вешается именно на это свойство!

2022-04-15 13:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectAnyRefTypeCheck.java
> +            if (REF_TYPES.contains(typeItemName))
имя может быть null - надо проверить, коллекция тут имутабельная - она позволяет ли проверять такое значение или будет выбрасывать исключение?

2022-04-15 13:48 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/DbObjectAnyRefNonRefTypeCheckTest.java
> +}
может стоит добавить еще тест на правильное поведение?

2022-04-15 13:48 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/DbObjectRefNonRefTypesCheckTest.java
> +}
может стоит добавить еще тест на правильное поведение?

2022-04-18 10:58 UTC, marmyshev commented on CHANGELOG.md
> +
Просьба перенести на 0.3

2022-06-24 15:42 UTC, marmyshev commented
@iArtemv нужно актуализировать реквест

2022-06-24 15:48 UTC, iArtemv commented
Актуализировал

2022-06-24 15:51 UTC, iArtemv commented
@marmyshev по этому реквесту еще ждем задачу в edt

2022-06-24 15:57 UTC, marmyshev requested changes

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/ru/db-object-ref-non-ref-type.md
> +
Нужна ссылка на стандарт

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/ru/db-object-anyref-type.md
> +## См.
нужна ссылка на стандарт

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/db-object-ref-non-ref-type.md
> +
нужна ссылка на стандарт (с 1ci.com или 1c-dn.com)

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/db-object-anyref-type.md
> +
нужна ссылка на стандарт (с 1ci.com или 1c-dn.com)

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectRefNonRefTypesCheck.java
> +                    resultAceptor.addIssue(Messages.DbObjectRefNonRefTypesCheck_Ref_and_other, TYPE_DESCRIPTION__TYPES);
Желательно вешать сообщение на индекс конкретного элемента проблемы - в будущем человек в большом списке может явно увидеть какой конкретно тип проблемный

2022-06-24 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DbObjectAnyRefTypeCheck.java
> +                resultAceptor.addIssue(Messages.DbObjectAnyRefCheck_AnyRef, TYPE_DESCRIPTION__TYPES);
Желательно вешать сообщение на индекс конкретного элемента проблемы - в будущем человек в большом списке может явно увидеть какой конкретно тип проблемный

2022-06-24 15:57 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/DbObjectRefNonRefTypesCheckTest.java
> +    extends CheckTestBase
можно использовать SingleProjectReadOnlyCheckTestBase если проект эксклюзивный под эту проверку

2022-06-24 15:57 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/DbObjectAnyRefNonRefTypeCheckTest.java
> +    extends CheckTestBase
можно использовать SingleProjectReadOnlyCheckTestBase если проект эксклюзивный под эту проверку

2022-06-24 15:57 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/DbObjectRefNonRefTypesCheckTest.java
> +        IBmObject object = getTopObjectByFqn("Catalog.Test3", dtProject);
А можно давать имена не Test123 а какой в них смысл вкладывается? хотя бы Compliant + Noncompiant 

а то потом через пару месяцев пойди разбери что за тест падает... :)

2022-07-07 08:04 UTC, marmyshev approved these changes

2022-07-07 14:14 UTC, merged