#37 Длина названия раздела превышает 35 символов
1C-Company/v8-code-style pull request #1016
Opened 2022-04-11 13:14 UTC by disant1

## Что сделано

- Добавлен плагин, проверяющий, что длина названия раздела не превышает 35 символов. У плагина есть 2 параметра - максимальная длина названия(по умолчанию 35) и фильтр для исключения из проверки определенных языков(по умолчанию пустой, т.е. проверяется для всех языков). Формат фильтра: коды языков на латинице, через запятую. Например "en,de".  

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [x] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #37

2022-04-12 05:11 UTC, tretyakevich requested changes

2022-04-12 05:11 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +        // Check subsystem is top-level
(комментарий) Ну если быть до конца честным, то здесь мы проверяем, что подсистема как раз подчиненная, и отсекаем эту ветку, если факт подтвержден.
Но это мелочи, конечно - само решение верное.

2022-04-12 05:11 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +            if (!excludeLang.toUpperCase().contains(key.toUpperCase()) && subsystem.isIncludeInCommandInterface())
В общем случае не очень оптимально (exludeLang будет преобразовываться toUpperCase несколько раз, операция недешевая). 
Также разумно subsystem.isIncludeInCommandInterface() включить в отсечение выше (где проверка наличия parent-подсистемы) - и вынос из цикла, и ближе к условиям проверки (если верхнего уровни и включена в КИ). 
Будет и оптимальнее, и читаться код будет лучше.

2022-04-12 05:11 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +                String name = synonyms.get(key);
Поскольку здесь мы используем мапу для полного обхода, а не для ассоциативного выбора - то хорошей практикой (опять же производительность и т.п.) - брать в цикле не keySet, а затем выбирать по ключу, а просто брать entrySet, и дальше Entry использовать для получения и ключа, и значения.

2022-04-12 05:11 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +                if (name != null && name.length() > max && max > 0)
Проверка валидности значения параметра (max>0) - опять же разумно вынести за цикл, и сделать отсечение в случае, если значение параметра не соответствует валидному диапазону.

2022-04-12 05:11 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/SubsystemSynonymTooLongCheckTest.java
> + *
(minor) Лишний перенос строки

2022-04-12 05:11 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/SubsystemSynonymTooLongCheckTest.java
> +        assertNull(marker);
Собственно не вижу теста на мультиязыковость - когда один длинный, второй нет, когда оба длинные (два маркера), когда ни одного.

2022-04-13 10:59 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +    @Inject
Исправлено.

2022-04-13 10:59 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +        super();
Исправлено.

2022-04-13 10:59 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +        // Check subsystem is top-level
Исправлено.

2022-04-13 11:00 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +            if (!excludeLang.toUpperCase().contains(key.toUpperCase()) && subsystem.isIncludeInCommandInterface())
Исправлено.

2022-04-13 11:00 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +                String name = synonyms.get(key);
Переделал

2022-04-13 11:00 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +                if (name != null && name.length() > max && max > 0)
Исправлено.

2022-04-13 11:01 UTC, disant1 commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/SubsystemSynonymTooLongCheckTest.java
> + *
Исправлено.

2022-04-13 11:01 UTC, disant1 commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/SubsystemSynonymTooLongCheckTest.java
> +        assertNull(marker);
Добавил проверок на количества маркеров, также добавил вариаций с мультиязычностью.

2022-04-15 09:58 UTC, marmyshev requested changes
По коду всё ок. Несколько мелких замечаний...

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +    public static final String MAX_SUBSYSTEM_SYNONYM_LENGTH = "max-subsystem-synonym-length"; //$NON-NLS-1$
По соглашению проекта - тут нужно кемелкейс в параметре

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +    public static final String SUBSYSTEM_SYNONYM_LANGS_FILTER = "subsystem-synonym-lang-filter"; //$NON-NLS-1$
По соглашению проекта - тут нужно кемелкейс в параметре

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +        String excludeLang = parameters.getString(SUBSYSTEM_SYNONYM_LANGS_FILTER);
тут нужно разбивать по запятым и в Set, строку на совпадение проверять - небезопасно - может часть строки совпасть

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +SubsystemSynonymTooLongCheck_Length_of_section_name_more_than_symbols_for_language = Length of section name {0} more than {1} symbols for language {2}
Здесь нужно заменить "name" на synonym - а его текст надо в кавычки:

Length of section synonym "{0}" is more...

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
> +SubsystemSynonymTooLongCheck_Length_of_section_name_more_than_symbols_for_language = Длина синонима раздела {0} превышает {1} символов для языка {2}
Предлагаю так:

Длина синонима раздела "{0}" превышает...

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/ru/subsystem-synonym-too-long.md
> +
Нужно добавить ссылки на стандарты на русском с сайта ИТС 

https://its.1c.ru/db/v8std#content:712:hdoc

для примера как тут https://github.com/1C-Company/v8-code-style/blob/master/bundles/com.e1c.v8codestyle.bsl/markdown/ru/form-module-pragma.md

2022-04-15 09:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/subsystem-synonym-too-long.md
> +
предлагаю добавить ссылки:

- https://support.1ci.com/hc/en-us/articles/360011003580-Sections-panel
- https://1c-dn.com/library/user_manual_taxi_interface_sections_panel/

2022-04-18 06:07 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +    public static final String MAX_SUBSYSTEM_SYNONYM_LENGTH = "max-subsystem-synonym-length"; //$NON-NLS-1$
Исправлено

2022-04-18 06:07 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +    public static final String SUBSYSTEM_SYNONYM_LANGS_FILTER = "subsystem-synonym-lang-filter"; //$NON-NLS-1$
Исправлено

2022-04-18 06:09 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/SubsystemSynonymTooLongCheck.java
> +        String excludeLang = parameters.getString(SUBSYSTEM_SYNONYM_LANGS_FILTER);
Сделал с использованием List, т.к. в этом случае код выглядит читабельнее и не надо доп. переменные создавать.

2022-04-18 06:09 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +SubsystemSynonymTooLongCheck_Length_of_section_name_more_than_symbols_for_language = Length of section name {0} more than {1} symbols for language {2}
Исправлено

2022-04-18 06:10 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/markdown/subsystem-synonym-too-long.md
> +
Добавлено

2022-04-18 06:10 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/markdown/ru/subsystem-synonym-too-long.md
> +
Добавлено

2022-04-18 06:11 UTC, disant1 commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
> +SubsystemSynonymTooLongCheck_Length_of_section_name_more_than_symbols_for_language = Длина синонима раздела {0} превышает {1} символов для языка {2}
Исправлено

2022-04-18 10:54 UTC, marmyshev approved these changes

2022-04-18 10:56 UTC, merged