#409 Отсутствует удаление временного файла после использования
1C-Company/v8-code-style pull request #1024
Opened 2022-04-26 13:01 UTC by disant1

## Что сделано
Добавлена проверка, что после после создания временного файла происходит его удаление. Проверка создает список из названий переменных открытых временных файлов внутри модуля и проверяет, что к этим переменным был применен один из методов для удаления файла. Список методов передается проверке в виде строкового параметра, где перечислены методы, разделенные символом "|".  По умолчанию заданы следующие методы: "УдалитьФайлы|DeleteFiles|НачатьУдалениеФайлов|BeginDeletingFiles|ПереместитьФайл|MoveFile".
Информация по параметрам, а также критичности и т.п. была взята по [ссылке](https://1c-syntax.github.io/bsl-language-server/diagnostics/MissingTemporaryFileDeletion/).

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-04-29 06:09 UTC, vadimeg requested changes

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +                return;
Исправлено

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        for (Map.Entry<String, StaticFeatureAccess> entry : undeletedFiles.entrySet())
Исправлено по второму варианту

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +    protected void check(Object object, ResultAcceptor resultAceptor, ICheckParameters parameters,
Исправлено

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        if (module == null)
Сделано

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        if (monitor.isCanceled())
Исправлено

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +    Map<String, StaticFeatureAccess> undeletedFiles = new HashMap<>();
Исправлено

2022-04-29 07:46 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +            if (monitor.isCanceled())
Исправлено

2022-04-29 08:44 UTC, vadimeg approved these changes

2022-04-29 08:45 UTC, vadimeg commented
Подождем, что скажет Дима @marmyshev. У меня по коду больше вопросов нет.

2022-05-12 12:13 UTC, marmyshev requested changes
Кажется проверка будет работать не очень точно. Если несколько файлов создаются - а удаляется один - такую проблему не найдет.

2022-06-03 11:26 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/markdown/missing-temporary-file-deletion.md
> +
Сделано.

2022-06-03 11:26 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/missing-temporary-file-deletion.md
> +
Сделано.

2022-06-03 11:26 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/plugin.xml
> +     </extension>
Исправлено.

2022-06-03 11:26 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +    private Map<String, StaticFeatureAccess> undeletedFiles = new HashMap<>();
Исправлено.

2022-06-03 11:29 UTC, disant1 commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/MissingTemporaryFileDeletion/src/CommonModules/CommonModule/Module.bsl
> +КонецПроцедуры
Переделал.

2022-06-03 11:29 UTC, disant1 commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/MissingTemporaryFileDeletionCheckTest.java
> +        assertEquals(MESSAGE, marker.getMessage());
Исправлено.

2022-06-03 11:29 UTC, disant1 commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/MissingTemporaryFileDeletionCheckTest.java
> +    private static final String PROJECT_NAME = "MissingTemporaryFileDeletion";
Сделано.

2022-06-03 11:30 UTC, disant1 commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/MissingTemporaryFileDeletion/.settings/Default.cset
> +        "deleteFileMethods": "УдалитьФайлы|DeleteFiles|НачатьУдалениеФайлов|BeginDeletingFiles|ПереместитьФайл|MoveFile|МоеУдалениеФайла"
Тут был добавлен  пользовательский метод удаления, сейчас функционал расширен.

2022-06-24 16:46 UTC, marmyshev requested changes

2022-06-24 16:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        while (!(source instanceof StaticFeatureAccess));
В целом, алгоритм может работать неправильно, т.к. не всегда у `DynamicFeatureAccess.getSource()` будет либо  DynamicFeatureAccess либо StaticFeatureAccess (может быть еще что-угодно в середине IndexAccess, Invocation и т.д.) - поэтому сформированное имя может нерелевантный или несуществующим.

2022-06-24 16:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +                fullName = source.getName().concat(".").concat(fullName); //$NON-NLS-1$
Может быть конкатенацию строк заменить на StringBuilder? не то что бы критичная проблемка - просто пересоздавшие объектов в памяти в цикле... :)

2022-06-24 16:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        while (!(source instanceof StaticFeatureAccess));
Ну и если проверка нарвется на такой код - то JVM в дамп... :)

2022-06-24 16:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        if (methodName.equalsIgnoreCase(METHOD_NAME) || methodName.equalsIgnoreCase(METHOD_NAME_RU))
Сравнение с константой - нужно объекты поменять местами

2022-06-24 16:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +                if (featureName.equalsIgnoreCase(METHOD_NAME) || featureName.equalsIgnoreCase(METHOD_NAME_RU)
Сравнение с константой - нужно объекты поменять местами

2022-06-28 08:06 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        while (!(source instanceof StaticFeatureAccess));
Поправил алгоритм

2022-06-28 08:06 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +                fullName = source.getName().concat(".").concat(fullName); //$NON-NLS-1$
Сделано

2022-06-28 08:06 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +        if (methodName.equalsIgnoreCase(METHOD_NAME) || methodName.equalsIgnoreCase(METHOD_NAME_RU))
Сделано

2022-06-28 08:06 UTC, disant1 commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/MissingTemporaryFileDeletionCheck.java
> +                if (featureName.equalsIgnoreCase(METHOD_NAME) || featureName.equalsIgnoreCase(METHOD_NAME_RU)
Сделано

2022-07-01 10:16 UTC, merged