#504 У поля "Ссылка" таблицы динамического списка не отключена пользовательская видимость
1C-Company/v8-code-style pull request #1025
Opened 2022-04-29 15:00 UTC by olgabozhko

## Что сделано

Добавлена проверка на отключение пользовательской видимости у поля "Ссылка" таблицы динамического списка.

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #504

2022-05-04 04:24 UTC, mgalios commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +    }
Можно упростить этот метод до 
```suggestion
    private boolean pathCheck(EList<EObject> eContents)
    {
        if (eContents.size() < 2 || !(eContents.get(1) instanceof AbstractDataPath))
        {
            return false;
        }

        EList<String> segments = ((AbstractDataPath)eContents.get(1)).getSegments();

        return segments.size() == 2 && LIST_SEGMENT.constains(segments.get(0)) && REF_SEGMENT.contains(segments.get(1));
    }
```

В этом случае надо будет заменить `REF_ABSTRACT_DATA_PATH` и  `REF_ABSTRACT_DATA_PATH_RU` на что-то типа
```
    private static final List<String> LIST_SEGMENT = List.of("List", "Список");
    private static final List<String> REF_SEGMENT = List.of("Ref", "Ссылка");
```

2022-05-04 10:02 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +    }
Спасибо, упростила.

2022-05-12 11:10 UTC, marmyshev requested changes

2022-05-12 11:10 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +            .containment(VISIBLE)
А почему бы не подписать сразу на UserVisible? и у него уже проверять фичу в isCommon()?
это будет правильнее - т.к. пользователь будет модифицировать этот объект и реакция нужна на изменение фичи USER_VISIBLE__IS_COMMON (ну точное название фичи посмотри в модели)

А уже если isCommon() == true - тогда уже проверить контейнер на то что это поле и что там в дата-пасе ссылка.

2022-05-18 11:31 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +        }
Убрала.

2022-05-18 11:31 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +                visible);
Заменила фичу.

2022-05-18 11:31 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +        if (pathCheck(visible.eContents()) && visible.getUserVisible().isCommon())
Спасибо, поменяла.

2022-05-18 11:32 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +            .containment(VISIBLE)
Исправила.

2022-05-18 11:32 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +    private static final List<String> LIST_SEGMENT = List.of("List", "Список"); //$NON-NLS-1$ //$NON-NLS-2$
Этот список я использую в pathCheck, где проверяю DataPath сегменты. Или на них тоже нельзя полагаться?

2022-06-15 17:59 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefUserVisibilityEnabledCheck.java
> +    private static final List<String> LIST_SEGMENT = List.of("List", "Список"); //$NON-NLS-1$ //$NON-NLS-2$
Убрала изменяемый первый сегмент, оставила только второй, где приходит Ref/Ссылка.

2022-06-24 15:39 UTC, merged