#639 Отсутствует включение безопасного режима перед вызовом метода Выполнить или Вычислить
1C-Company/v8-code-style pull request #1026
Opened 2022-05-04 08:14 UTC by mgalios

## Что сделано

Добавлена проверка на включение безопасного режима перед вызовом методов `Выполнить(Execute)` и `Вычислить(Eval)`

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #639

2022-05-04 08:23 UTC, mgalios commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ServerExecutionSafeModeCheck_eval_issue = Safe mode is not enabled when calling "Eval"
В этих файлах что-то не так с изменениями, видимо автоматическое форматирование сработало, вернуть как было, чтобы история чище была, или оставить так?

2022-06-02 14:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ServerExecutionSafeModeCheck.java
> +        return eObject instanceof Invocation && EVAL.contains(((Invocation)eObject).getMethodAccess().getName());
Регистро-зависимое сравнение строк в коллекции

2022-06-02 14:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ServerExecutionSafeModeCheck.java
> +        return SAFE_MODE_INVOCATIONS.contains(name) && params.size() == 1 && params.get(0) instanceof BooleanLiteral;
Регистро-зависимое сравнение строк

2022-07-28 10:00 UTC, mgalios commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ServerExecutionSafeModeCheck.java
> +        return SAFE_MODE_INVOCATIONS.contains(name) && params.size() == 1 && params.get(0) instanceof BooleanLiteral;
Использовал регистро-независимое сравнение строк

2022-07-28 10:01 UTC, mgalios commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ServerExecutionSafeModeCheck.java
> +        return eObject instanceof Invocation && EVAL.contains(((Invocation)eObject).getMethodAccess().getName());
Использовать регистро-независимое сравнение строк

2022-07-28 10:04 UTC, mgalios commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ServerExecutionSafeModeCheck_eval_issue = Safe mode is not enabled when calling "Eval"
Поправил форматирование

2022-07-29 12:54 UTC, marmyshev requested changes

2022-07-29 12:54 UTC, marmyshev commented on CHANGELOG.md
> -
косяк мержа

2022-07-29 12:54 UTC, marmyshev commented on CHANGELOG.md
> -
косяк мержа

2022-07-29 12:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ServerExecutionSafeModeCheck.java
> +    private boolean isServerCall(EObject eObject)
тут неудачное название `ServerCall` - "вызов сервера" - это режим перехода с клиента на сервер. Тут чтобы не вводить в заблуждение - либо `isServer()` или `isOnServer()`

2022-07-29 12:54 UTC, merged