#503 Реквизит "Ссылка" динамического списка не выведен в таблицу на форме
1C-Company/v8-code-style pull request #1028
Opened 2022-05-11 17:37 UTC by olgabozhko

## Что сделано

Добавлена проверка наличия реквизита "Ссылка" динамического списка в таблице на форме.

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #503

2022-05-12 05:07 UTC, vadimeg approved these changes

2022-05-12 10:54 UTC, marmyshev requested changes

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        item -> item.getName().contains(REF_NAMES.get(0)) || item.getName().contains(REF_NAMES.get(1));
тут может быть NPE - т.к. item.getName() может вернуть null, это не нормальная ситуация в модели данных, но возможная, поэтому лучше константное значение писать слева, а возможное null-значение справа.

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        }
Тут в общем случае линий код:
1. монитор нужно проверять в тяжелых алгоритмах или циклах - т.к. там где можно безболезненно прерваться.
2. нужно в конфигураторе указать подписку сразу на TABLE - и тут  у нас гарантия что прийдет точно этот объект можно смело катить без проверок - код будет выглядеть легче:

`Table table = (Table)object;`

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        if (((Table)object).eContents().stream().filter(DynamicListTableExtInfo.class::isInstance).count() == 1)
тут сильно быстрее будет работать если написать

if (table.getExtInfo() instanceof DynamicListTableExtInfo)

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +    private Predicate<? super FormItem> nameCheck =
это похоже на константу.
1. нужно перенести поле выше всего кода
2. добавить модификаторы private static final Predicate<? super FormItem> NAME_CHECK = ...

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +            if (form.getItems().stream().noneMatch(nameCheck))
такой алгоритм не будет учитывать группировки колонок - будет ложное срабатывание.

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +            FormItemContainer form = (Table)object;
имя переменной form - предлагаю заменить на table :)

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +    private static final String CHECK_ID = "form-list-ref-not-presented-check"; //$NON-NLS-1$
1. в коде не следует использовать мусорные слова (в данном случае check) которые не имеют никакого значения.
2. Я бы предложил перефразировать, `form-ref-list-field-exist` - проверка существования поля списка со ссылкой. или `form-list-field-ref-exist` (но лучше заглянуть в конвенцию по образованию кодов в docs, там есть советы как правильно писать)
3. если переименуешь код - не забудь переименовать файлы описаний в маркдауне и переименовать этот класс чтобы был созвучный

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        if (((Table)object).eContents().stream().filter(DynamicListTableExtInfo.class::isInstance).count() == 1)
Дополню. Не достаточно просто проверить что это таблица динамического списка.
Нужно еще проверить что таблица ссылочная - иначе будет много ложных срабатываний для случаев:
1. когда таблица - это регистр сведений/накопления/расчетов/бугхалтерии - там не бывает ссылок
2. когда кастомные запрос (при этом ссылки в запросе нет) и не указана базовая таблица - это редкая но при этом нормальная ситуация

нужно проверять базовую таблицу реквизита формы и что таблица "ссылочная".

2022-05-12 10:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +            .severity(IssueSeverity.MAJOR)
предлагаю сделать приоритет чуть ниже - а то мажорных проблем и так хватает)) разработчики не любят когда их сильно мажорят в коде))

2022-06-06 15:29 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        item -> item.getName().contains(REF_NAMES.get(0)) || item.getName().contains(REF_NAMES.get(1));
Постаралась это учесть.

2022-06-06 15:32 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        if (((Table)object).eContents().stream().filter(DynamicListTableExtInfo.class::isInstance).count() == 1)
Исправила.

2022-06-06 15:32 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +    private Predicate<? super FormItem> nameCheck =
Исправила.

2022-06-06 15:33 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +            if (form.getItems().stream().noneMatch(nameCheck))
Теперь пробую проверять группировки колонок через FormGroup.

2022-06-06 15:36 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +    private static final String CHECK_ID = "form-list-ref-not-presented-check"; //$NON-NLS-1$
Изменила на `form-list-field-ref-not-added` - чтобы ошибка была явно обозначена в названии (как написано в конвенции, "Следует отражать в коде проверки находимую проблему").

2022-06-16 05:41 UTC, vadimeg requested changes

2022-06-16 05:41 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.metadata.dbview;version="4.0.0",
Тут диапазон должен быть:
version="[4.0.0,5.0.0)"

2022-06-16 05:41 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && ((Form)((FormGroup)object).bmGetTopObject()).getItems().get(1) instanceof Table))
.getItems().get(1)
Непонятная проверка. Во-первых, элементов на форме может быть меньше, тогда будет IndexOutOfBoundException
И почему таблица должна быть по индексу 1? Она может быть в любом месте, в том числе и быть вложенной в  одну или несколько контейнеров (групп разного типа), тогда нужен рекурсивный обход для поиска

2022-06-16 05:47 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        }
Можно и FORM_ITEM_CONTAINER

2022-06-29 11:53 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        }
@olgabozhko Осталось только это?

2022-06-29 13:19 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListRefNotPresentedCheck.java
> +        }
Не совсем понимаю. Реквизит типа Динамический список является источником пути данных для Table и ее колонок. Остальные контейнеры элементов - Form, FormGroup, Addition - к динамическому списку отношения не имеют. Мы должны обрабатывать только Table в этой проверке.

2022-06-30 08:56 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.metadata.dbview;version="4.0.0",
Исправила.

2022-06-30 08:56 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && ((Form)((FormGroup)object).bmGetTopObject()).getItems().get(1) instanceof Table))
Убрала привязку к индексу, а по рекурсии вопрос - надо начинать с Form и обходить все в поисках таблиц?

2022-06-30 12:13 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && ((Form)((FormGroup)object).bmGetTopObject()).getItems().get(1) instanceof Table))
Давай попробуем привязаться к родителю таблицы с другой стороны, тогда не придется делать обход. Все таблицы придут в проверку, где бы они ни находились:

```
            .topObject(FORM)
            .containment(DATA_ITEM)
            .features(FORM_ITEM_CONTAINER__ITEMS, DATA_ITEM__DATA_PATH);
```
Т.е. мы берем DATA_ITEM, который является родителем (не контейнером!) для таблиц и ее колонок.
Колонки в обходе нужны, т.к. у них есть свой DataPath, который может быть удален пользователем, а это нужно учитывать. DATA_ITEM__DATA_PATH включили в фичи.
А таблицу ищем так:

        if (object instanceof Table || (object instanceof FormField))
        {
            Table table = object instanceof Table ? (Table)object : (Table)((FormField)object).eContainer();
...
только, конечно, нужно проверить, что ((FormField)object).eContainer() это instanceof Table!

Второй момент. Таблицы в реквизитах могут быть вложенными. Такой пример - создаем справочник, в нем табличную часть, потом форму списка.

![image](https://user-images.githubusercontent.com/17178862/176668058-11c956e2-ee25-4247-a848-e62d5514de75.png)

В этом случае для таблицы, которая ссылается на табличную часть пути к данным будут элементного типа, см. 
хелпер DatapathUtil.isElementDataPath(path)

Я бы переписал метод itemPathCheck(AbstractDataPath path) вот так:
```
            String lastSegment = segments.get(segments.size() - 1);
            return ((lastSegment.equals(REF_ABSTRACT_DATA_PATH.get(0))
                || lastSegment.equals(REF_ABSTRACT_DATA_PATH.get(1))));
```

Ну, и проверку на то, что путь есть и он имеет хотя бы один сегмент.

Третий момент. Пользователь может очистить путь к данным самой таблицы. Это нужно проверять в начале.
Если table.getDataPath() == null, то выходим до попытки найти связанный с таблицей реквизит.

2022-06-30 12:40 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && ((Form)((FormGroup)object).bmGetTopObject()).getItems().get(1) instanceof Table))
P.S. Не, не пойдет DataItem :(. Тоже будут false positives.
Пусть будет TABLE в качестве containment. С путями колонок таблицы надо подумать, но даже если не будет в обходе, то это меньшее зло

2022-07-01 05:25 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && ((Form)((FormGroup)object).bmGetTopObject()).getItems().get(1) instanceof Table))
Обсудили с коллегами. В общем, для этой проверки не подходит BasicCheck в качестве базового класса. Не получится на его основе сделать покрытие всех вариантов. В частности, у items таблицы могут поменяться DataPath и в BasicCheck это не обработаешь. В самом реквизите тоже могут быть изменения - удаление, добавление колонок и т.п. Нужна реализация на основе ICheck. В качестве примера можно посмотреть как реализована проверка ссылочной целостности на основе этого интерфейса - MdReferenceIntegrity

2022-07-01 06:54 UTC, vadimeg requested changes
Нужна реализация от ICheck

2022-07-14 14:53 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
Здесь проверяем, что FormGroup относится к таблице; а если таблица вложенная, то проверка должна среагировать именно на Table (хотя, возможно, я этот кейс не до конца понимаю). И отсюда, кстати говоря, вопрос:  ошибка должна отображаться для каждой из таблиц на форме (сейчас так сделано)? Или если хотя бы в одну из таблиц добавлена ссылка - этого достаточно?

2022-07-15 11:24 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
Вообще, здесь я хотела убедиться, что эта FormGroup принадлежит таблице, но, значит, это так не работает. Что до таблиц во вложенных подгруппах, то я жду что проверка среагирует на Table, где бы таблица ни находилась (object instanceof Table).

2022-07-15 11:34 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
Еще вопрос, сюда тоже надо добавить SkipBaseFormExtension (не через extension, раз здесь iCheck, а как-то иначе)?

2022-07-15 12:49 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
> Еще вопрос, сюда тоже надо добавить SkipBaseFormExtension (не через extension, раз здесь iCheck, а как-то иначе)?

Да. в базовой форме расширения тоже не надо делать проверку. Просто проверять, что форма не является BaseForm, как это сделано в SkipBaseFormExtension

2022-07-15 12:51 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
> Вообще, здесь я хотела убедиться, что эта FormGroup принадлежит таблице, но, значит, это так не работает. Что до таблиц во вложенных подгруппах, то я жду что проверка среагирует на Table, где бы таблица ни находилась (object instanceof Table).

Просто сейчас всегда проверяются только элементы формы, которая является контэйнером элементов. Группа тоже контейнер элементов (но не топ объект!), и у нее тоже есть метод getItems()

2022-07-21 18:45 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
Убрала вообще эту проверку; да, у группы тоже есть метод getItems(), но проверка сейчас реагирует на таблицу, даже если она во вложенной группе - и если не добавлен реквизит ссылка, то на этой таблице появляется ошибка. Если я упускаю какой-то кейс - подскажи, пожалуйста, шаги воспроизведения.

2022-07-22 07:20 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +        if (object instanceof Form && isBaseForm((Form)object))
Так неправильно. А если объект не форма, а таблица? Тогда проверки для базовой формы останутся. Надо топ-объект брать для проверки. Либо ((IBmObject)object).bmGetTopObject() либо ECoreUtil2.getContainerOf(object, Form.class)

2022-07-22 07:20 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +
лишняя пустая строка

2022-07-22 07:20 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +
лишняя пустая строка

2022-07-22 07:20 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
В тестирование нужно включить кейсы:
1. Таблица находится в о вложенных группах (Form->Group1->Group2->Table) для обычного динамического списка
2. Таблица находится в о вложенных группах (Form->Group1->Group2->Table) для динамического списка с произвольным запросом. В свойствах динамического списка нужно выставить галку "Произвольный запрос", открыть запрос в окне, добавить куда-нибудь пробел и сохранить (для того, чтобы настройки списка сохранились в файле формы именно в виде запроса). Нужны русский и английский варианты: List.Ref, Список.Ссылка

2022-07-22 07:23 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +        if (object instanceof Form && isBaseForm((Form)object))
И нам ведь здесь нужны только таблицы, так? Если так, то для всех объектов, кроме Table, нужно делать выход.

2022-07-25 14:35 UTC, marmyshev requested changes

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                .orElse(null);
Здесь находится первый попавшийся реквизит формы, а не тот который связан с таблицей.

Кажется было бы сильно проще `table.getDataPath().getObjects().get(0).getObject()` (ну только с учетом что надо всё безопасно проверять - индексы и касты)

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +    private static final Set<EClass> TARGET_CONTAINMENT = new HashSet<>(Arrays.asList(FORM_ITEM_CONTAINER));
Set.of(FORM_ITEM_CONTAINER), но вообще нужно подписываться на TABLE - иначе смысл было переделывать на общий интерфейс?

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +    private static final List<String> REF_ABSTRACT_DATA_PATH = List.of("Ref", "Ссылка"); //$NON-NLS-1$ //$NON-NLS-2$
Дело вкуса конечно, но тут бесполезный список - как список он не используется - всегда обращение четко по индексу - рекомендую заменить на 2 константы.

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                    .get(0);
Берется первая попавшаяся таблица - а не контейнер текущей группы.

рекомендую использовать `org.eclipse.xtext.EcoreUtil2.getContainerOfType(EObject, Class<T>)` или если по зависимостям Xtext в этом банде нет - то прям такой же 2х строчный алгоритм можно применить.

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +            if (checkTable(table))
Это (кажется) не правильно - тут нужно определить список измененных объектов и отправить их на проверку, а уже тяжелые вычисления (типа наличие правильного DataPath от реквизита ДС) делать в рамках проверки уже. Здесь обработка происходит в рамках транзакции - и код должен быть как можно легче

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +FormListFieldRefNotAddedCheck_The_Ref_field_is_not_added_to_dynamic_list = The Ref field is not added to dynamic list
Тут немного не точный смысл - если не знать о чем проверка - будет тяжело догадаться что имелось ввиду.

Предлагаю взять текст из русского: `Реквизит "Ссылка" динамического списка не выведен в таблицу на форме` - `The Ref attribute of dynamic list is not added to the table on the form`

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +        if (segments.isEmpty())
Здесь для ускорения можно проверять что количество сегментов = 2 - т.к. у ДС по другому не бывает, но вот ссылки могут вытащить откуда-то из другого объекта (будет 3+ сегмента) - и тогда это уже не ссылка ДС, а нечто другое. 

Предлагаю сдесь же добавить коммент поэтому поводу - что `segment.size() == 2` это специально потому что...

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                if (items.get(i) instanceof FormGroup && pathCheck(((FormGroup)items.get(i)).getItems()))
множественное получение по индексу.

Предлагаю вначале цикла сделать:

`FormItem item = items.get(i);`

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                    .filter(AbstractDataPath.class::isInstance)
А почему бы тут не взять сразу? `FormItem.getDataPath()`

2022-07-25 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/plugin.xml
> +            class="com.e1c.v8codestyle.internal.form.ExecutableExtensionFactory:com.e1c.v8codestyle.form.check.FormListRefUserVisibilityEnabledCheck">
Кажется тут косяк мержа какой-то

2022-07-27 10:51 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                    .filter(AbstractDataPath.class::isInstance)
Только не у FormItem, а у наследника - DataItem

2022-07-31 17:21 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                && checkIfTable(((Form)((FormGroup)object).bmGetTopObject()).getItems()))
У меня в текущем варианте проверка отрабатывает для ##1-2 
![image](https://user-images.githubusercontent.com/31319370/182038062-b1e19816-0131-41ea-b144-dbd1e3d9fbac.png)

2022-07-31 17:21 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +        if (object instanceof Form && isBaseForm((Form)object))
Исправила, спасибо.

2022-07-31 17:22 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +
Убрала.

2022-07-31 17:22 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +
Убрала.

2022-07-31 17:22 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                .orElse(null);
Изменила.

2022-07-31 17:22 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +    private static final Set<EClass> TARGET_CONTAINMENT = new HashSet<>(Arrays.asList(FORM_ITEM_CONTAINER));
Если подписываться на TABLE, проверка не реагирует на добавление ссылки в колонку:
![image](https://user-images.githubusercontent.com/31319370/182038117-12346f3c-6bfe-4e34-9958-5dcf54a344ee.png)

2022-07-31 17:23 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +    private static final List<String> REF_ABSTRACT_DATA_PATH = List.of("Ref", "Ссылка"); //$NON-NLS-1$ //$NON-NLS-2$
Заменила.

2022-07-31 17:23 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                    .get(0);
Поправила.

2022-07-31 17:24 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +            if (checkTable(table))
Убрала это.

2022-07-31 17:24 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +FormListFieldRefNotAddedCheck_The_Ref_field_is_not_added_to_dynamic_list = The Ref field is not added to dynamic list
Заменила, спасибо.

2022-07-31 17:24 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +        if (segments.isEmpty())
Добавила.

2022-07-31 17:24 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormListFieldRefNotAddedCheck.java
> +                    .filter(AbstractDataPath.class::isInstance)
Не поняла про DataItem, сделала через FormItem.getDataPath()

2022-07-31 17:26 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.form/plugin.xml
> +            class="com.e1c.v8codestyle.internal.form.ExecutableExtensionFactory:com.e1c.v8codestyle.form.check.FormListRefUserVisibilityEnabledCheck">
Там до этого был косяк, я поправляла) А сейчас вроде бы все нормально, просто порядок алфавитный изменился.

2022-08-02 11:30 UTC, merged