1037: Исключить BaseForm из проверок для форм
1C-Company/v8-code-style pull request #1038
Opened 2022-05-31 15:10 UTC by vadimeg

BaseForm исключено из проверок

2022-06-02 08:38 UTC, marmyshev requested changes

2022-06-02 08:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/InputFieldListChoiceMode.java
> +        }
Тут 2 момента.
1. Общую функциональность можно сделать через расширение проверки в конфигураторе подписки проверки добавить - там фильтровать топ-объект сюда даже приходить не будет - что-то типа SkipBaseFormExtension - удобно было бы сразу все одинаковый компонент добавлять.
2. Проверить что это не базовая форма можно по `form.getExtensionForm() == null` в этом расширении (ссылка заполняется на каком-то этапе ДД, но в момент валидация - она уже точно должна быть заполнена)

2022-06-02 09:32 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/InputFieldListChoiceMode.java
> +        }
№2. Валидация часто отрабатывает раньше, чем на DD заканчивается заполнение ссылок, для этого и сделано через FQN. Это не единственное место, где так сделано.

2022-06-02 09:42 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/InputFieldListChoiceMode.java
> +        }
№1. Конфигуратор проверки (CheckConfigurer) не расширяемый. Если расширять, то переделывать базовое API в EDT.

2022-06-03 07:43 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/InputFieldListChoiceMode.java
> +        }
Поправил

2022-06-29 13:25 UTC, merged