#311 Избыточное ключевое слово Экспорт
1C-Company/v8-code-style pull request #1044
Opened 2022-06-19 22:51 UTC by iArtemv

## Что сделано

- Проверка текстов модулей конфигурации на содержание неиспользуемые экспортные процедуры и функции.
- Учтено, что  экспортные методы, расположенные в области "ПрограммныйИнтерфейс" являются исключением, т.к. эти методы часто могут использоваться другими конфигурациями (библиотеками).

![image](https://user-images.githubusercontent.com/20300020/174503232-9cfc70c8-d95d-4d5d-8049-a2c01cbf1efc.png)

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-06-24 17:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportCheck.java
> +    private static final String CHECK_ID = "excess-export"; //$NON-NLS-1$
тут нужно добавить слово method, т.к. экспорт бывает не только у методов

2022-07-06 12:39 UTC, MaksimDzyuba requested changes

2022-07-06 12:39 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +        if (ModuleType.FORM_MODULE == module.getModuleType())
а разве еще не надо игнорировать модули команд? а еще есть модули веб сервисов, http сервисов, сервисов интеграции

2022-07-06 12:39 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +                    SearchScope.INFORMATION_REGISTERS, SearchScope.ACCUMULATION_REGISTERS,
а всякие планы обмена. хранилища настроек, а также модули конфигураций?

2022-07-06 12:39 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +            if (refs.isEmpty())
а были замеры, сколько секунд прибавляется на erp, если включить эту проверку?

2022-07-07 07:44 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +            if (refs.isEmpty())
замеряли на erp we - где-то час добавляется с небольшим

2022-07-07 17:01 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +            if (refs.isEmpty())
поэтому по дефолту предлагается настройку отключать (о том что она может выполняться длительное время явно пишем в описании), и те кто хочет проверить (пожелание популярное) разово включат, поправят ошибки и отключат, конечно хотелось бы иметь более быстрый поиск для текущей задачи, но пока текущий вариант поможет найти и почистить проблемы конфигурации

2022-07-12 12:49 UTC, MaksimDzyuba approved these changes

2022-07-12 15:32 UTC, marmyshev requested changes
кажется что стоит немного доделать - вдруг выигрыш по скорости будет...

2022-07-23 23:25 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.bsl.bm.ui.refactoring;version="[8.4.400,9.0.0)",
переделал на xtext поиск (не ui)

2022-07-23 23:25 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/qfix/RemoveExcessExportFix.java
> +}
переделал, но кажется если через multicheck не работают фиксы

2022-07-23 23:26 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/ExternalDependenciesModule.java
> +            .get((Class<? extends IGlobalScopeProvider>)BslGlobalScopeProvider.class));
убрал

2022-07-23 23:26 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +    private static final String CHECK_ID = "excess-export-method"; //$NON-NLS-1$
переименовал

2022-07-23 23:26 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +            || ModuleType.WEB_SERVICE_MODULE == moduleType)
поправил

2022-07-23 23:27 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +                    SearchScope.EXCHANGE_PLANS, SearchScope.SETTINGS_STORAGES, SearchScope.CONFIGURATIONS),
переделал на xtext

2022-07-23 23:27 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +                Set.of(SearchFor.LANGUAGE_ELEMENTS), Set.of(SearchIn.MODULES),
переделал

2022-07-23 23:27 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +import com.google.common.collect.Lists;
убрал

2022-07-23 23:27 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExcessExportMethodCheck.java
> +            FullTextSearchReferenceFinder referenceFinder = new FullTextSearchReferenceFinder(method.getName(), method,
переделал на xtext

2022-07-29 12:27 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private boolean isNotifyDescription(Module module, String name)
а зачем это, это же поиск ссылок должен находить

2022-07-29 18:03 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private boolean isNotifyDescription(Module module, String name)
Описание оповещений поиск ссылок находит, но их искать не нужно, т.к. они могут находиться в том же модуле в котором они описаны и это не будте считаться ошибкой (хотя для других методов это будет ошибка, если вызов на них только из модуля где они объявлены)

2022-07-29 21:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private boolean isNotifyDescription(Module module, String name)
> Описание оповещений поиск ссылок находит, но их искать не нужно, т.к. они могут находиться в том же модуле в котором они описаны и это не будте считаться ошибкой 

Либо я не понял ответ, либо ты ошибаешься:
1. есть оповещение в текущем модуле на текущий экспортный метод - его нужно искать. Если нашли - дальше искать внешние вызовы на метод смысла нет
2. Оповещение на текущий экспортный метод может быть создано в любом другом модуле - его тоже нужно искать - это приравнивается к обычному вызову.

получается - что их нужно всегда искать. Но в текущем модуле в первую очередь. 

Уточни, так ли сейчас работает?

2022-07-29 23:36 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private boolean isNotifyDescription(Module module, String name)
да, работает так.
Я кривовато описал, хотел передать следующую мысль, что если описание оповещения описано и реализовано в одном и том же модуле, то для реализации оповещения не нужно искать описание оповещения именно сервисом поиска ссылок по всей конфигурации (но чтобы это выяснить мы просматриваем контент модуля)

2022-08-01 18:01 UTC, marmyshev requested changes

2022-08-01 18:01 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private boolean isNotifyDescription(Module module, String name)
Предложение - метод назвать `existLocalNotifyDescription()`  - может будет чуть понятней...

2022-08-02 07:30 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +            && !haveCallerInOtherModule(method))
порядок вроде от самого простого (проверка параметра) самому тяжелому (поиск ссылок)

2022-08-02 10:50 UTC, marmyshev requested changes

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +                if (moduleMethodName.equalsIgnoreCase(item.getUserData(USER_DATA)))
В любом цикле нужно проверять монитор - для этого предлагалось его сюда втаскивать

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +                if (moduleMethodName.equalsIgnoreCase(item.getUserData(USER_DATA)))
В любом цикле нужно проверять монитор - для этого предлагалось его сюда втаскивать

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +        IProgressMonitor monitor = new NullProgressMonitor();
это интересный код :) 
нужно ведь использовать монитор входящий в проверку, верно?

Здесь нужно делать нормального наследника от `NullProgressMonitor` с иерархией по вышестоящему монитору - чтобы установка отмены этого локального монитора не приводила к отмене вышестоящего, но при проверке отмены - учитывался вышестоящий монитор который из проверки.

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +        }
А зачем тут этот вызов? разве может сюда приходить модуль без этого флага? (кажется что нет)
Если установил этот флаг - надо пересчитать весь модуль с его учетом тогда. Но кажется что это не правильно такой пересчет делать в проверке.

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +                    if (StringUtils.equals(name, region.get().getName()))
Здесь в любой момент может произойти падение если параллельно было редактирование и объекты стали неактуальные - а монитор тут не проверяется в цикле

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +RedundantExportCheck_Exclude_title=Имена областей исключение
Не согласованы падежи.

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +RedundantExportCheck_Exclude_title=Имена областей исключение
Откуда станет известно о том, что это список с разделителями запятой? :)

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +RedundantExportCheck_Exclude_title=Exclude region names
Откуда станет известно о том, что это список с разделителями запятой? :)

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +                accept(new DefaultReferenceDescription(source, targetOrProxy, eReference, index, sourceUri));
А почему бы тут не проверить сразу на эквивалентность ури?

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +                URI targetUri)
вначале метода - неплохо бы проверить на отказ монитора

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +            {
вначале метода - неплохо бы проверить на отказ монитора

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +            //
Кажется забыт комментарий почему тут так сделано

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +    private static final Object TYPE_NAME = "NotifyDescription"; //$NON-NLS-1$
Тип - строка

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RedundantExportMethodCheck.java
> +        }
Если этого флага нет - тогда можно не продолжать?

2022-08-02 10:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +    {
Кажется в мастере уже есть эта процедура

2022-08-03 15:47 UTC, merged