Между "НачатьТранзакцию()" и "Попытка" есть исполняемый код
1C-Company/v8-code-style pull request #1063
Opened 2022-07-11 01:15 UTC by iArtemv

## Что сделано

- Между "НачатьТранзакцию()" и "Попытка" есть исполняемый код

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [x] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #569 
Closes #566
Closes #919

2022-07-11 09:30 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +                                    nextStatement);
Это какая-то дичь - зачем хадкодить прохождение тестов под одну единственную ситуацию?

Тут кажется простая логика (могла бы быть):
1. нашли invocation "НачатьТранзакцию" 
2. Нужно найти следующий стейтмент TryExceptStatement - если его нет - вешаем ошибку на "Начать-транзакцию" или следующий после него стейтмент.

вот тестовый код, который сейчас вообще непонятно как будет или не будет ловиться текущей реализацией, хотя проблема тут есть:

```bsl
Процедура Тест()

     НачатьТранзакцию();

 КонецПроцедуры 
```

Не понятно, почему эта проверка вешается на проверку завершения транзакции, а не на начало транцами?

2022-07-12 06:05 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +                                    nextStatement);
поправил

2022-07-13 07:42 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/BeginTransactionCheck.java
> +                        Messages.CommitTransactionCheck_Executable_code_between_begin_transaction_and_try, inv);
Копипаста из другого класса

2022-07-13 07:45 UTC, marmyshev requested changes

2022-07-13 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +
лишние изменения

2022-07-13 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +CommitTransactionCheck_Executable_code_between_begin_transaction_and_try=Между "НачатьТранзакцию()" и "Попытка" есть исполняемый код
CommitTransactionCheck класс не модифицировался в этом реквесте

2022-07-13 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/begin-transaction.md
> +# The scheme of working with transactions is broken
Заголовок не коррелирует с заголовком проверки

2022-07-13 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/begin-transaction.md
> +# Проверка нарушения схемы работы с транзакциями
Заголовок не коррелирует с заголовком проверки

2022-07-13 07:45 UTC, marmyshev commented on CHANGELOG.md
> +    6. Не найден оператор "Попытка" после вызова "НачатьТранзакцию()"
Прошу выделить описание в соответствующую проверку

2022-07-13 09:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +
Изменения всё еще присутствуют

2022-07-13 13:54 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +
Лишнюю убрал, а это просто по ходу пофиксил, вынести в отдельный реквест?

2022-07-13 15:20 UTC, merged