#995 Квик-фикс конвертации функции в процедуру
1C-Company/v8-code-style pull request #1066
Opened 2022-07-12 10:01 UTC by muhtimur

## Что сделано

- Добавлен квик-фикс конвертации функции в процедуру

![Запись экрана 2022-07-12 в 17 20 24 (1)](https://user-images.githubusercontent.com/84380737/178470054-5ff5fc5c-fac1-4315-9c96-a74c8fe87cf6.gif)

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #995

2022-07-12 14:01 UTC, marmyshev requested changes

2022-07-12 14:01 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +        List<ILeafNode> allLeafNodes = Lists.newArrayList(node.getLeafNodes());
1. Лучше не использовать Lists из гуавы (оно неявно тянется из Xtext)
2. предлагаю заманить на LinkedList и в циклах использовать pollFirst() pollLast() (на твоё усмотрение)

2022-07-12 14:01 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +            .description(Messages.ConvertFunctionToProcedureFix_description)
не забудь добавить “Convert function “{0}” to procedure”

2022-07-12 14:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +import com.e1c.v8codestyle.bsl.qfix.external.SingleVariantXtextBslModuleFix;
просьба заменить на пакет - com.e1c.g5.v8.dt.bsl.check.qfix.

2022-07-14 10:45 UTC, muhtimur commented on CHANGELOG.md
> -
Добавил

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +import com.e1c.v8codestyle.bsl.qfix.external.SingleVariantXtextBslModuleFix;
Заменил

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> + * Quick fix for check com.e1c.v8codestyle.bsl.strict.check:function-return-value-type
Добавил описание

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +            .description(Messages.ConvertFunctionToProcedureFix_description)
Добавил

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +        List<ILeafNode> allLeafNodes = Lists.newArrayList(node.getLeafNodes());
1. Убрал Lists
2. Добавил LinkedList (но некоторые сомнения по поводу правильности его создания, строка 89)

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +            if (leafNode.getText().equals(QuickFixMethodsHelper.getTypeMethodName(model, true)))
1. Заменил на кейворды, которые достаю из BslGrammarAccess
2. Получил кейворды до цикла

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +                result.addChild(new ReplaceEdit(leafNode.getTotalOffset(), leafNode.getTotalLength(),
Заменил

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +            if (leafNode.getText().equals(QuickFixMethodsHelper.getTypeEndMethodName(model, true)))
1. Заменил на кейворды
2. Получаю их до цикла

2022-07-14 10:45 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/bsl/ui/qfix/ConvertFunctionToProcedureFix.java
> +                result.addChild(new ReplaceEdit(leafNode.getTotalOffset(), leafNode.getTotalLength(),
Заменил

2022-07-14 11:35 UTC, marmyshev approved these changes

2022-07-14 11:40 UTC, merged