1071: Ложное срабатывание проверки: У реквизита "Ссылка" динамического списка выключен признак "Использовать всегда"
1C-Company/v8-code-style pull request #1075
Opened 2022-07-21 10:25 UTC by vadimeg

Добавлена обработка кастомных динамических списков. Исправлены тесты

2022-07-22 09:53 UTC, marmyshev requested changes
Нужно:
1. указывать закрываемую задачу в реквесте.
2. Нужно указать историю изменений

Следует использовать шаблон реквеста - там это обычно предлагается

2022-07-22 12:41 UTC, vadimeg commented
> Нужно:
> 
> 1. указывать закрываемую задачу в реквесте.
> 2. Нужно указать историю изменений
> 
> Следует использовать шаблон реквеста - там это обычно предлагается

Поправил

2022-07-25 13:37 UTC, marmyshev commented
@vadimeg файл истории изменений не обновил, в остальном всё ок)

2022-07-26 09:25 UTC, vadimeg commented
> @vadimeg файл истории изменений не обновил, в остальном всё ок)

Обновил

2022-07-27 10:25 UTC, merged