#467 В качестве правого операнда операции сравнения "ПОДОБНО" указано поле таблицы.
1C-Company/v8-code-style pull request #1079
Opened 2022-07-26 12:40 UTC by disant1

## Что сделано

Добавлена проверка корректного использования операции сравнения "ПОДОБНО" запросов. А именно,  что качестве правого операнда операции сравнения "ПОДОБНО" не указано поле таблицы. Добавлены JUnit тесты для проверки.

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #86

2022-07-27 08:32 UTC, marmyshev requested changes

2022-07-27 08:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/IncorrectLikeRightOperandCheck.java
> +        resultAceptor.addIssue(message, likeExpression, LIKE_EXPRESSION__LITERAL);
Тут предлагаю вешать ошибку точно на поле - указывать CommonExpression и фичу COMMON_EXPRESSION__CONTENT

2022-07-27 08:32 UTC, marmyshev commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/non-compliant.ql
> +;
Предлагаю еще добавить еще тест-кейс на то что справа указано одно поле:

```
SELECT
      StocksBalanceAndTurnovers.Warehouse
  FROM
      AccumulationRegister.Stocks.BalanceAndTurnovers AS StocksBalanceAndTurnovers
  WHERE
      StocksBalanceAndTurnovers.Warehouse LIKE Warehouse
  ;
```
Это позволи проверить на CommonExpression в том случае если это SinglePartCommonExpression.

2022-07-27 08:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/IncorrectLikeRightOperandCheck.java
> +        resultAceptor.addIssue(message, likeExpression, LIKE_EXPRESSION__LITERAL);
Причем будет еще оч круто, если ты сделаешь сокращение элементов коллекции commonExpressions от дублей - т.к. в этой коллекции указаны будут как поля таблицы (MultiPart) так и сами таблицы (SinglePart)

```java
Set<CommonExpression> unique = new HashSet<>();
unique.addAll(commonExpressions);
for(CommonExpression common : commonExpressions)
{
  if(common instanceof MultiPartCommonExpression)
  {
    unique.remove(((MultiPartCommonExpression) common).getSourceTable();
  }
}
```

и тогда вешать ошибки можно прям на все поля из unique.

2022-07-27 08:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-incorrect-like-right-operand.md
> +... ПОДОБНО Таблица1.Поле1
Просьба добавить чуть более полный пример текста запроса - а то кого-то может ввести в непонимание.
В остальных примерах - аналогично. Можно взять один из тест-кейсов.

2022-07-27 08:32 UTC, marmyshev commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/non-compliant.ql
> +;
на всякий случай, на русском - не обязательно, т.к. тут вариант скрипта роли не играет. На твое усмотрение.

2022-07-27 08:32 UTC, marmyshev commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/compliant.ql
> +;
на всякий случай, на русском - не обязательно, т.к. тут вариант скрипта роли не играет. На твое усмотрение.

2022-07-27 08:41 UTC, marmyshev requested changes

2022-07-27 08:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/IncorrectLikeRightOperandCheck.java
> +    private static final String CHECK_ID = "ql-incorrect-like-right-operand"; //$NON-NLS-1$
смущает название проверки (и следовательно имя класса) - слово incorrect в данном контексте не значит ничего. Сама по себе проверка - это уже на корректность или некорректность.

Предлагаю: `ql-like-operand-with-field` или что-то типа того.

Еще вариант `ql-like-expression-with-field`

2022-07-28 03:50 UTC, disant1 commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/IncorrectLikeRightOperandCheck.java
> +        resultAceptor.addIssue(message, likeExpression, LIKE_EXPRESSION__LITERAL);
Сделано

2022-07-28 03:50 UTC, disant1 commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/non-compliant.ql
> +;
Сделано

2022-07-28 03:50 UTC, disant1 commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-incorrect-like-right-operand.md
> +... ПОДОБНО Таблица1.Поле1
Сделано

2022-07-28 03:51 UTC, disant1 commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/non-compliant.ql
> +;
Убрал русский, облегчил немного

2022-07-28 03:51 UTC, disant1 commented on tests/com.e1c.v8codestyle.ql.itests/resources/ql-incorrect-like-right-operand/compliant.ql
> +;
Убрал русский, облегчил немного

2022-07-28 03:52 UTC, disant1 commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/IncorrectLikeRightOperandCheck.java
> +    private static final String CHECK_ID = "ql-incorrect-like-right-operand"; //$NON-NLS-1$
Переименовал в ql-like-expression-with-field

2022-07-28 11:35 UTC, marmyshev approved these changes

2022-07-28 11:51 UTC, merged