Добавлена проверка области событий
1C-Company/v8-code-style pull request #1081
Opened 2022-07-27 04:50 UTC by iArtemv

## Что сделано

- Добавлена проверка области событий
- Если метод является событием, проверяется что он в области событий
- Проверяется если в области событий располагается метод не относящийся к событию

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #733 #330

2022-07-27 09:25 UTC, marmyshev requested changes

2022-07-27 09:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ModuleStructureEventRegionsCheck_Title=Проверяет регион обработчиков событий на методов относящихся только к обработчикам
Аналогично, можно было бы перефразировать английский вариант, но на твое усмотрение.

2022-07-27 09:25 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/src/Catalogs/CatalogInRegionWrongMethod/ManagerModule.bsl
> +Procedure Test()
А что тестируем? :)

2022-07-27 09:25 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleStructureEventRegionsCheckTest.java
> +        Method method = methods.get(0);
Здесь можно было бы не грузить модуль - а сразу получать маркеры по URI модуля.

2022-07-27 09:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +    protected Optional<RegionPreprocessor> getUpperRegion(Method method)
или getFirstParentRegion() + getTopParentRegion()

2022-07-27 09:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +        }
Тут получается просто следующий родитель. Один следующий. А если уровень иерархии больше чем 2?

2022-07-27 09:32 UTC, marmyshev requested changes

2022-07-27 09:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventRegionsCheck.java
> +            return;
на это есть метод getModuleType()

но неплохо бы, на будущее, сделать еще Extension который бы сразу фильтровал нужные типы модулей (попробую сделать)

2022-07-28 05:33 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +                }
можешь пояснить как по семантической помдели выяснить, что в следующей ситуации метод находится вне найденного региона?
```
#Region EventHandlers
// Enter code here.
#EndRegion
Procedure FormGetProcessing(FormType, Parameters, SelectedForm, AdditionalInformation, StandardProcessing)
	//TODO: Insert the handler content
EndProcedure

#Region Internal
// Enter code here.
#EndRegion
```

2022-07-28 05:34 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +        }
поправил, чет мне изначально показалось что ищется самый верхний родитель

2022-07-28 05:36 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +        Optional<RegionPreprocessor> parent = getParentRegion(region);
именно так я изначально и подумал, что ищет самого верхнего

2022-07-28 05:37 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventRegionsCheck.java
> +            return;
завести задачу на extension?

2022-07-28 13:18 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +                }
посмотри в getParentRegion() - там не тупой поиск контейнеров до  `RegionPreprocessor`.

В данном методе - не правильно искать вначале

```
RegionPreprocessor region = EcoreUtil2.getContainerOfType(method, RegionPreprocessor.class);
         if (region == null)
         {
             return Optional.empty();
         }
```

нужно точно так же по контейнерам проверять не находимся ли мы случаем внутри AfterItem у области.

Неплохо было бы добавить твой пример в тесты.

2022-07-29 03:45 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +                }
Такой тест будет в проверке на вхождение метода в область module-structure-method-in-regions. Текущая проверка сейчас это не будет считать ошибочной ситуацией.

2022-07-29 11:07 UTC, marmyshev requested changes

2022-07-29 11:07 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/.settings/Default.cset
> +}
нужно удалить файл

2022-07-29 11:07 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
лишний файл

2022-07-29 11:07 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/.settings/com.e1c.v8codestyle.bsl.prefs
> +eclipse.preferences.version=1
лишний файл

2022-07-29 11:07 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/.settings/com.e1c.v8codestyle.prefs
> +commonChecks=true
лишний файл

2022-07-29 11:07 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/StructureModule/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.20
8.3.19

2022-07-29 11:07 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +     * @return the top parent region
null может быть?

2022-07-29 18:13 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventRegionsCheck.java
> +            return;
уже есть такая #1091

2022-07-29 21:09 UTC, merged