Добавлена проверка областей событий формы
1C-Company/v8-code-style pull request #1082
Opened 2022-07-27 05:25 UTC by iArtemv

## Что сделано

- Добавлена проверка областей событий формы

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #773
Closes #330

2022-07-29 12:03 UTC, marmyshev requested changes

2022-07-29 12:03 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleStructureEventFormRegionsCheckTest.java
> +        Marker marker = getFirstMarker(CHECK_ID, module.eResource().getURI(), getProject());
бессмысленно грузить кучу объектов - можно создать константу  с URI модуля - и обратиться только за маркерами

2022-07-29 12:03 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleStructureEventFormRegionsCheckTest.java
> +        Marker marker = getFirstMarker(CHECK_ID, module.eResource().getURI(), getProject());
Аналогично везде ниже

2022-07-29 12:03 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleStructureEventFormRegionsCheckTest.java
> +        assertNotNull(marker);
не проверяется куда повешен маркер - какая строка?

2022-07-31 21:07 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
> +        }
с топ областью может все же отдельной проверке оставить? иначе получится одна ошибка будет дублироваться с разным текстом

2022-08-01 12:31 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
> +                table = (Table)e;
Кажется тут дальше нет смысла продолжать цикл, если нашли таблицу

2022-08-01 12:31 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
> +                check(result, container, regionName, methodName, scriptVariant);
Тут "отрицание, проверку типа и возврат" можно заменить на просто "проверку типа" 
`else if (obj instanceof EventHandlerContainer)` - когнитивная сложность сократится :)

2022-08-01 12:31 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
> +        Form form = null;
не кажется ли тебе, что тут и далее внизу метода - всегда нужен только один единственный точный объект  (а не все 5 переменных одновременно) на который надо проверять ` if(object instanceof Table) ...`? не настаиваю, но код станет менее запутанным по количеству условий внизу метода.

2022-08-02 09:33 UTC, marmyshev requested changes

2022-08-02 09:33 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureEventFormRegionsCheck.java
> +    private static final String MULTILEVEL_EMBEDDING_OF_REGIONS = "multilevelEmbeddingOfRegions"; //$NON-NLS-1$
в другой проверке - аналогичная константа и ее перевод - не забудь поправить

2022-08-03 11:47 UTC, marmyshev approved these changes

2022-08-03 12:28 UTC, merged