#954 Добавление типизированного значения в не типизированную коллекцию
1C-Company/v8-code-style pull request #1084
Opened 2022-07-27 09:05 UTC by muhtimur

## Что сделано

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-08-02 06:14 UTC, muhtimur commented
@1C-Company @marmyshev прошу сделать аудит

2022-08-02 09:08 UTC, marmyshev requested changes

2022-08-02 09:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +        if (collectionItemTypes.isEmpty())
Я бы предложил сделать 3 метода:

```java
// Супер-быстро проверяем что нам вообще этот метод подходит и что надо вычислять типы
Collection<String> expectedTypes = getExpectedCollectionTypes(fa, method);
if(expectedTypes == null || expectedTypes.isEmpty())
{
return;
}

// Тут получаем реальные типы коллекции - но код может быть не типизирован и типов не найти - тогда не проверяем наличие типов коллекции, естественно.
Collection<TypeItem> actualTypes getActualCollectionTypes(fa, expectedTypes);
if(!actualTypes.isEmpty() && isActualCollectionItemTypeEmpty(actualTypes))
{
// add issue...
}

```

2022-08-02 09:08 UTC, marmyshev commented
@muhtimur Надо бы тест написать :)

2022-08-02 11:00 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +            .severity(IssueSeverity.MAJOR)
Хотя может и не надо менять.... :)

2022-08-24 06:35 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +            .severity(IssueSeverity.MAJOR)
Я основывался на похожей проверке с пересечением типов коллекции и добавляемых элементов, там такой приоритет. Думаю, стоит оставить.

2022-08-24 06:35 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +        "Add", Map.of(IEObjectTypeNames.ARRAY, Set.of(0), //$NON-NLS-1$
Добавил эти методы тоже.

2022-08-24 06:35 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +        Method method = (Method)getSourceMethod(fa);
Исправил

2022-08-24 06:36 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +            IEObjectTypeNames.VALUE_LIST, Set.of(0))
Подумал над этим моментом. Для типизации коллекций, заданной в несколько строк есть свои проверки типа "Field 'Value' has no type definition". И даже если их проигнорировать и попытаться что-то добавить в коллекцию, там уже срабатывает проверка "Invocation expression type is not intersect with type". Поэтому я думаю, что данная проверка не нужна для сложных объектов.
Но тип элемента ValueList же можно задать и как примитив в одну строчку `// ValueList of Number`. Тут, я думаю, проверка срабатывать должна. Поэтому я оставил ее для Array и для ValueList, добавив недостающие методы.

2022-08-24 06:36 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +                BslPackage.Literals.EXPRESSION__TYPES);
Повесил на имя метода

2022-08-24 06:36 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +        if (collectionItemTypes.isEmpty())
Да, как-то по-идиотски написал.
Сделал три метода, но `expectedTypes` представил как коллекцию `TypeItem`, чтобы потом удобнее было вычислить типы. Надеюсь, правильно понял, как надо это сделать.

2022-08-24 06:36 UTC, muhtimur commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +        }
Вынес

2022-08-24 06:36 UTC, muhtimur commented
> @muhtimur Надо бы тест написать :)

Добавил тесты

2022-09-16 15:48 UTC, marmyshev requested changes

2022-09-16 15:48 UTC, marmyshev commented on CHANGELOG.md
> +- Добавление типизированного значения в не типизированную коллекцию
Просьба перенести на в версию 0.4

2022-09-16 15:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/TypedValueAddingToUntypedCollectionCheck.java
> +            .severity(IssueSeverity.MAJOR)
Да, извиняюсь не увидел что есть расширение для учета аннотации строгой типизации.

2022-09-16 16:26 UTC, marmyshev approved these changes

2022-09-16 18:21 UTC, merged