Добавлена проверка метода вне области
1C-Company/v8-code-style pull request #1093
Opened 2022-08-01 00:43 UTC by iArtemv

## Что сделано

- Проверяет что метод находится вне области
- Проверяет что экспортный метод находится в интерфейсных областях
- Проверяет что неэкспортный метод не находится в интерфейсных областях

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #373

2022-08-01 17:47 UTC, marmyshev requested changes

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +        String regions = String.join(",", regionNames); //$NON-NLS-1$
бесполезный код для тех методов где есть области.

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +                addIssue(resultAceptor, method, String.join(",", publicName, internalName, privateName)); //$NON-NLS-1$
Неплохо бы в разделитель добавить пробел - чтобы это казалось текстом

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +            if ((publicName.equals(regionName) || internalName.equals(regionName)) && !method.isExport())
поменяй условия &&  местами - будет быстрей.

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ModuleStructureMethodInRegionCheck_Method_should_be_placed_in_one_of_the_standard_regions=The method "{0}" should be placed in one of the standard regions: "{1}"
"{1}" - а кавычки тут нужны? есть двоеточие, текст в конце, есть запятые...

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ModuleStructureMethodInRegionCheck_Multilevel_embedding_of_regions=Multilevel embedding of regions
Думал-думал... кажется тут всё-таки не хватает слова "Разрешить многоуровневое вложение областей" :) а то будет непонятно что значит этот флаг в проверке

2022-08-01 17:47 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ModuleStructureMethodInRegionCheckTest.java
> +    private static final String PROJECT_NAME = "ModuleStructureRegionsCheck";
Тут прям кучка проверок на одну тему` ModuleStructureRegions...` предлагаю проект назвать по точнее относительно класса проверки.

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +        else if (moduleType != ModuleType.FORM_MODULE && moduleType != ModuleType.COMMAND_MODULE)
Сходу кажется что есть непокрытый сценарий. В формах и командах ведь будут экспортные или не экспортные методы и они могут быть вне областей.  Не оч понятно кто этот сценарий покрывает, в анализе такого не видел. 

Но если всё есть - тут неплохо бы оставить комментарий и ссылку на класс который это делает.

2022-08-01 17:47 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
>       * Gets the parent region of given region.
Описание нужно актуализировать

2022-08-01 20:35 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +        else if (moduleType != ModuleType.FORM_MODULE && moduleType != ModuleType.COMMAND_MODULE)
данный сценарий у нас покрыт `ExportMethodInCommandFormModuleCheck` - добавлю комментарий

2022-08-01 20:56 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureMethodInRegionCheck.java
> +        else if (moduleType != ModuleType.FORM_MODULE && moduleType != ModuleType.COMMAND_MODULE)
добавил тесты для модуля формы и команды для неэкспортных методов

2022-08-02 07:34 UTC, marmyshev approved these changes

2022-08-02 07:37 UTC, merged