Обновлена проверка областей верхнего уровня
1C-Company/v8-code-style pull request #1103
Opened 2022-08-07 03:40 UTC by iArtemv

## Что сделано

- Проверка состава областей верхнего уровня, соотвествие его стандарту
- Проверка порядка областей верхнего уровня
- Проверка дублей стандартных областей

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #532
Closes #533
Closes #488
Closes #614

2022-08-09 13:12 UTC, marmyshev requested changes
Общая проблема - неправильная работа с константами в циклах и регистрозависмое сравнение строк. 

Только часть прокомментировал - рекомендую еще раз просмотреть все алгоритмы, обратить внимание на то какие коллекции используются.

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +                ModuleStructureSection.FORM_TABLE_ITEMS_EVENT_HANDLERS.getName(scriptVariant).toLowerCase();
константное значение вычисляется в цикле

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            boolean checkDuplicates = parameters.getBoolean(CHECK_DUPLICATES_OF_STANDARD_REGIONS);
константное значение вычисляется в цикле

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            boolean checkOrder = parameters.getBoolean(CHECK_ORDER_OF_STANDARD_REGIONS);
константное значение вычисляется в цикле

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            .equals(ModuleStructureSection.FORM_COMMAND_EVENT_HANDLERS.getName(scriptVariant).toLowerCase()))
1. константное значение вычисляется в цикле
2. вместо регистро-независимого сравнения строк используется тяжелое преобразование в нижний регистр и обычное сравнение

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +        Map<String, List<RegionPreprocessor>> countRegions = new HashMap<>();
регистрозависимый ключ коллекции

2022-08-09 13:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +        List<String> topRegions = getTopRegions(allRegions, countRegions);
Очень странный метод, получающий (геттер) верхнеуровневые регионы, но при этом заполняющие еще другую коллекцию попутно - это никак не геттер.

2022-08-09 19:22 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/ModuleStructureProvider.java
> +        return ImmutableSet.copyOf(ModuleStructure.getStructureByType(moduleType)
Можешь пояснить?
нам ведь нужен порядок заданный в перечислении, а не отсортированный.
```java
ImmutableSortedSet.copyOf
Returns an immutable sorted set containing the given elements sorted by the given Comparator.
```

2022-08-09 19:39 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +        names.forEach(n -> lowerBaseNames.add(n.toLowerCase()));
toLowerCase убрал, по поводу TreeSet не совсем понял, это отсортированный сет, а мне нужен тот порядок который в модуле

2022-08-10 07:58 UTC, marmyshev approved these changes

2022-08-10 07:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            {
Много-много раз делаем одно и тоже константное действие в цикле - разбиваем строку :)

2022-08-10 07:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +    private List<String> countDoublesAndFindTopRegions(List<RegionPreprocessor> allRegions,
Тут почему-то всё остался геттер с генерацией входящих данных, хоть ты убрал слово get - смысл проблемы не поменялся :) 

Возвращаемые данные - надо сделать такими же входящими параметрами которые будут заполняться. Функцию переделать в процедуру.

2022-08-10 07:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +    private static boolean startsWith(String str, String prefix, boolean ignoreCase)
ignoreCase - бесполезный параметр - всегда true

2022-08-10 07:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            if (isTop && baseNames.stream().noneMatch(regionName::equalsIgnoreCase)
Здесь и везде выше/ниже - постоянно создаются стримы `baseNames.stream()` - они по сути константные в этом цикле - можно создать один раз

2022-08-10 08:50 UTC, merged