Добавлена проверка области объявления переменных
1C-Company/v8-code-style pull request #1105
Opened 2022-08-09 07:15 UTC by iArtemv

## Что сделано

- Проверяется что объявление переменных находится в соотвествующей области

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #534
Closes #531
Closes #200

2022-08-09 13:38 UTC, marmyshev requested changes

2022-08-09 13:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +            Optional<RegionPreprocessor> region = getTopParentRegion(variable);
А зачем в цикле делать абсолютно одинаковый поиск? разве от количества переменных в одной декларации количество областей может быть разным?

2022-08-09 13:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ModuleStructureVariablesInRegionCheck_Title=Variable declaration
Название имеет самый широкий смысл и не уточняет что делается в проверке, слова "структура модуля" или "область" могли бы как-то уточнять смысл.  В русском - аналогично

В декларации переменных, например так же не допускается отсутствие типа - но название проверки не такое общее.

2022-08-09 13:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +        }
вначале проверять бессмысленно, а вот в цикле ниже - обязательно.
после циклических действий типа EcoreUtil2.getContainerOfType() - тоже можно было бы

2022-08-09 13:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +            .extension(new StandardCheckExtension(getCheckId(), BslPlugin.PLUGIN_ID))
Предлагаю добавить сюда фильтр `ModuleTypeFilter.excludeTypes(ModuleType.COMMON_MODULE)` и другие в которых не бывает переменных в модуле.

2022-08-09 17:53 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +            .extension(new StandardCheckExtension(getCheckId(), BslPlugin.PLUGIN_ID))
ОК, в остальные проверки тоже протащу где это нужно

2022-08-09 21:05 UTC, marmyshev requested changes

2022-08-09 21:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +            region = getTopParentRegion(variables.iterator().next());
> Овер-инженеринг: 
> Задача 1: вскипятить пустой чайник.
> Шаги: налить воды, поставить на плиту, включить нагрев, дождаться.
> 
> Задача 2: вскипятить полный чайник
> Шаги: привести исходному состоянию для написанного кода задачи 1 - вылить воду - и повторить шаги задачи 1.

Почему бы не передавать в метод сразу `region = getTopParentRegion(declareStatement);`? но если уж хочется сначала таки взять первую переменную - а потом обратно прошагать текущий declareStatement и найти регион - то зачем тут итератор создавать? Можно же просто по индексу списка (если таки убрать абстрагирование типа коллекции возврата `declareStatement.getVariables();`)

Зачем тут странное условие ` if (!variables.isEmpty())`? если переменных нет - зачем исполнять весь нижестоящий код? эту проверку надо выполнить самой первой еще до любых циклический поисков методов или регионов...

2022-08-09 21:22 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureVariablesInRegionCheck.java
> +            region = getTopParentRegion(variables.iterator().next());
поправил

2022-08-10 05:55 UTC, marmyshev approved these changes

2022-08-10 06:53 UTC, merged