Добавлена проверка одного обработчика для нескольких команд
1C-Company/v8-code-style pull request #1115
Opened 2022-08-12 05:28 UTC by iArtemv

## Что сделано

- Добавлена проверка одного обработчика для нескольких команд

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #856

2022-09-16 15:17 UTC, marmyshev requested changes

2022-09-16 15:17 UTC, marmyshev commented on CHANGELOG.md
> +- Один обработчик выполнения назначен нескольким элементам
Просьба перенести на в версию 0.4

2022-10-18 15:00 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/markdown/ru/form-commands-one-action-handler.md
> +Смешение нескольких событий в одной процедуре неоправданно усложняет ее логику и снижает ее устойчивость (вместо одного предусмотренного вызова - по событию из платформы - код процедуры должен рассчи
1. Возможно, стоит заменить слово "устойчивость" на "стабильность"
2. Дефисы лишние

2022-10-18 15:01 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/markdown/ru/form-commands-one-action-handler.md
> +Если одинаковые действия должны выполняться при возникновении событий в разных команд формы, следует:
Кажется, правильно команд**ах**

2022-10-18 15:03 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/CommandHandlerChangeExtension.java
> + * The extension that registers {@link Form} for model check if an command handler
a**n** -> a

2022-10-18 15:03 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/CommandHandlerChangeExtension.java
> + * or an item contained in the form have been changed
have -> has

2022-10-18 15:05 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormCommandsSingleEventHandlerCheck.java
> + * The check for the {@link Form} that each command is assigned to a one action handler
артикль "a", кажется, лишний

2022-10-18 15:07 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormCommandsSingleEventHandlerCheck.java
> +            if (monitor.isCanceled())
Предлагаю использовать rкласс ```SubMonitor``` и метод ```SubMonitor.split()```, тогда не нужно явно проверять отменен монитор или нет.

2022-10-18 15:08 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/Messages.java
> +    public static String FormCommandsSingleEventHandlerCheck_Handler_0_command_1_assigned_to_command__2;
Вокруг "0" и "1" двойное нижнее подчеркивание

2022-10-18 15:09 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +FormCommandsSingleEventHandlerCheck_Handler_0_command_1_assigned_to_command__2=The handler {0} of command {1} is already assigned to command {2}
Не нужно ли кавычки вокруг параметров

2022-10-21 15:14 UTC, marmyshev requested changes

2022-10-21 15:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormCommandsSingleEventHandlerCheck.java
> +            .extension(new StandardCheckExtension(getCheckId(), CorePlugin.PLUGIN_ID))
нужно добавить номер стандарта (прежде из мастера обновиться)

2022-10-21 15:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/CommandHandlerChangeExtension.java
> +        definition.addModelFeatureChangeContextCollector(collector, FormPackage.Literals.FORM_ITEM_CONTAINER);
Кажется этот объект FormPackage.Literals.FORM_ITEM_CONTAINER тут лишний.

2022-10-24 08:19 UTC, marmyshev requested changes

2022-10-24 08:19 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/markdown/form-commands-single-action-handler.md
> +[Module structure](https://support.1ci.com/hc/en-us/articles/360011002360-Module-structure#2.4.3)
Не актуальная ссылка

2022-10-24 08:19 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormCommandsSingleEventHandlerCheck.java
> +        SubMonitor subMonitor = SubMonitor.convert(monitor, form.getFormCommands().size());
предлагаю избавиться от саб-монитора - т.к. нет смысла

2022-10-24 12:13 UTC, marmyshev requested changes

2022-10-24 12:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/markdown/form-commands-single-action-handler.md
> +[Module structure](https://kb.1ci.com/1C_Enterprise_Platform/Guides/Developer_Guides/1C_Enterprise_Development_Standards/)
ссылка не ведет ни на какой стандарт

2022-10-28 13:44 UTC, merged