Добавлена проверка префика метода расширения
1C-Company/v8-code-style pull request #1118
Opened 2022-08-16 05:58 UTC by iArtemv

## Что сделано

- Добавлена проверка префика метода расширения

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #751

2022-09-16 15:19 UTC, marmyshev requested changes

2022-09-16 15:19 UTC, marmyshev commented on CHANGELOG.md
> +- Проверка наличия префикса расширения в методе расширения.
Просьба перенести на в версию 0.4

2022-10-13 14:12 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/OnlyAdoptedInExtensionObjectExtension.java
> +public class OnlyAdoptedInExtensionObjectExtension
Этот класс просто сам по себе? В других классах/в файле plugin.xml не нашел ссылки на него.

2022-10-13 14:12 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ExtensionMethodPrefixCheck_Ext_method_0_should_have_1_prefix=The method {0} should have {1} prefix
Не нужно ли двойные кавычки вокруг {0} и {1}?

2022-10-13 14:12 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ExtensionMethodPrefixCheck_Description=Имя метода не содержит префикс расширения
Не просто имя метода, а префикс имени метода не совпадает с префиксом расширения

2022-10-13 14:12 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ExtensionMethodPrefixCheck_Ext_method_0_should_have_1_prefix=Имя метода {0} должно содержать префикс {1}
Аналогичный комментарий по поводу двойных кавычек и фразы "имя метода"

2022-10-13 14:12 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ExtensionMethodPrefixCheck_Title=Метод расширения не содержит в имени префикс расширения
И тут

2022-10-13 14:12 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionMethodPrefixCheckTest.java
> +        if (!project.exists() || !project.isAccessible())
А когда такое может быть? Вроде в базовом классе ```SingleProjectReadOnlyCheckTestBase``` есть логика по инициализации проекта

2022-10-14 05:07 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
Объект расширения должен расширять объект основной конфигурации, поэтому проверяется что основная конфигурация есть

2022-10-14 05:18 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/OnlyAdoptedInExtensionObjectExtension.java
> +public class OnlyAdoptedInExtensionObjectExtension
добавляется как экстеншн .extension(new OnlyAdoptedInExtensionObjectExtension())

2022-10-14 05:58 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ExtensionMethodPrefixCheck_Description=Имя метода не содержит префикс расширения
здесь во фразе имя не содержит префикс вроде норм

2022-10-14 07:21 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionMethodPrefixCheckTest.java
> +        if (!project.exists() || !project.isAccessible())
здесь нужно инициализировать еще и расширение

2022-10-14 07:25 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +package com.e1c.v8codestyle.bsl.check;
у нас вроде все проверки в публичном классе

2022-10-14 15:34 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
А если закрыть проект конфигурации в воркспейсе, то проверка не отработает?

2022-10-23 10:57 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
Согласен, проблемка

2022-10-24 08:29 UTC, marmyshev requested changes

2022-10-24 08:29 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +    private static final String CHECK_ID = "extension-method-prefix-check"; //$NON-NLS-1$
Кажется где-то уже писал про код проверки -check - мусорное слово

2022-10-24 08:43 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExtensionMethodPrefixCheck.java
> +    private static final String CHECK_ID = "extension-method-prefix-check"; //$NON-NLS-1$
поправил

2022-10-24 10:21 UTC, merged