Чтение отдельных реквизитов объекта из базы данных
1C-Company/v8-code-style pull request #1121
Opened 2022-08-17 05:18 UTC by iArtemv

## Что сделано

- Добавлена проверка чтение отдельных реквизитов объекта из базы данных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1088

2022-08-17 07:44 UTC, marmyshev requested changes

2022-08-17 07:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +        }
нельзя обращаться к этой коллекции без DFA computer - она может в текущий момент пустая.

2022-08-17 07:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +        DynamicFeatureAccess dfa = (DynamicFeatureAccess)object;
нужно проверить что это не метод - через утилиту BslUtil.getInvocation()

2022-08-17 07:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            }
в цикле добавятся много ошибок на одно место если будет несколько типов. Нужно проверить что есть хотя бы один ссылочный тип - и одни раз повесить ошибку.

2022-08-17 07:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ReadingAttributesFromDataBaseCheck_Title=Reading specific object attributes from the database
specific - тут скорее всего "отдельный" означает "единичный" - т.е. больше подходит `Reading object single attribute...` (в единственном числе)

2022-08-17 07:44 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ReadingAttributesFromDataBaseCheck/src/Catalogs/Catalog/ObjectModule.bsl
> +	Query.SetParameter("Ref", Ref);
Ref -> CatalogRef

2022-08-17 07:44 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ReadingAttributesFromDataBaseCheck/src/Catalogs/Catalog/ObjectModule.bsl
> +EndProcedure
А какой смысл несет этот код?

2022-08-17 07:44 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ReadingAttributesFromDataBaseCheck/src/Catalogs/CatalogWrong/ObjectModule.bsl
> +//  CatalogRef - CatalogRef.CatalogWrong - Catalog ref
А зачем 2 разных каталога когда всё различие только в коде?

2022-08-17 07:44 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ReadingAttributesFromDataBaseCheckTest.java
> +    private static final String PROJECT_NAME = "ReadingAttributesFromDataBaseCheck";
Предлагаю использовать какой-то существующий проект и на основе `AbstractSingleModuleTestBase`, а тесты переписать на базовый проект и абстрактные типы `CatalogRef` - проверка чисто кодовая, нет смысла плодить новый проект.

2022-08-17 07:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +    private static final String CHECK_ID = "reading-attributes-from-database"; //$NON-NLS-1$
`reading-attributes-from-database` -> `reading-attribute-from-database` - проверка находит чтение единственного аттрибута

2022-09-16 07:56 UTC, marmyshev requested changes

2022-09-16 07:56 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            }
А можешь пояснить назначение этого кода?

1. Разве здесь у свойства может быть что-то другое?
2. Если вдруг код недостаточно типизированный - и мы не можем найти свойство, но при этом тип источника "СправочникСсылка" - т.е. известный ссылочный тип и мы обращаемся к абстрактному типу у которого неизвестны свойства - то проверка не должна срабатывать?

2022-09-16 07:56 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +        switch (McoreUtil.getTypeCategory(type))
Здесь может быть выброшено исключение

2022-09-16 07:56 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            if (isRefType(type))
Тут при нахождении первого ссылочного типа считаем что ошибка. Но могут быть комбинированные типы `СправочникОбъект, СправочникСсылка` - понятно что это дичь, но может быть и менее дикое `СправочникСсылка, Структура, СтрокаТаблицыЗначений` - что как бы уже намекает на разнородность алгоритма 1С который может проверять типы... 

предлагаю этот вопрос рассмотреть. Возможно следует сделать параметр со списком типов которые  следует игнорировать при составном типе вместе со ссылкой.

2022-09-16 15:19 UTC, marmyshev requested changes

2022-09-16 15:19 UTC, marmyshev commented on CHANGELOG.md
> +- Чтение отдельных реквизитов объекта из базы данных
Просьба перенести на в версию 0.4

2022-09-16 18:52 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            }
Эт чет какой-то рудимент видимо остался не актулаьный, удалил

2022-09-16 19:24 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +        switch (McoreUtil.getTypeCategory(type))
может, но там вроде непроверяемое исключение, следует ли его перехватывать?

2022-09-16 19:28 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            if (isRefType(type))
может тогда стоит проверять только в том случае, если составной тип содержит исключительно ссылочные типы? (чтобы не усложнять настройку, все же кажется такие кейсы крайне редкие)

2022-09-19 06:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +            if (isRefType(type))
Можно сделать параметр "Разрешить доступ к полям с составными не ссылочными типами" - по умолчанию True - кому нужно будет ужесточить правила - отключат.

2022-09-19 06:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +        switch (McoreUtil.getTypeCategory(type))
предлагаю тут проверить что имя типа != null.

2022-10-21 14:34 UTC, marmyshev requested changes

2022-10-21 14:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +    private static final String ALLOW_ACCESS_FIELDS_PARAMETER_NAME = "allowAccessFields"; //$NON-NLS-1$
А что означает этот параметр? 
"allowAccessFields = разрешить доступ к полям".

Погодите, но мы же проверкой этой запрещаем... :) видимо значит что-то другое

2022-10-24 07:09 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +    private static final String ALLOW_ACCESS_FIELDS_PARAMETER_NAME = "allowAccessFields"; //$NON-NLS-1$
уточнил имя параметра

2022-10-24 08:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +    private static final String ALLOW_ACCESS_FIELDS_PARAMETER_NAME = "allowAccessFields"; //$NON-NLS-1$
смотрю в код - имя всё то же.

2022-10-24 10:24 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ReadingAttributesFromDataBaseCheck.java
> +    private static final String ALLOW_ACCESS_FIELDS_PARAMETER_NAME = "allowAccessFields"; //$NON-NLS-1$
сейчас имя allowAccessFieldsNonReferenceType

2022-10-24 20:00 UTC, marmyshev requested changes

2022-10-24 20:00 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/reading-attribute-from-database.md
> +- [Reading specific object attributes from the database](https://kb.1ci.com/1C_Enterprise_Platform/Guides/Developer_Guides/1C_Enterprise_Development_Standards/Code_conventions/Module_formatting/Modul
Какая-то левая ссылка на другой стандарт

2022-10-25 08:03 UTC, marmyshev requested changes

2022-10-25 08:03 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ReadingAttributesFromDataBaseCheckTest.java
> +    private static final String PROJECT_NAME = "ReadingAttributesFromDataBaseCheck";
Не понятно, зачем тут целый проект!?

можно же на общем модуле проверять:


```bsl
 // Parameters:
 //  Object - CatalogRef - 
 // 
 // Returns:
 //  String - 
 Function NoneComliant(Object)

     return Object.Code;

 EndFunction

 // Parameters:
 //  Object - CatalogRef, CatalogObject - 
 // 
 // Returns:
 //  String - 
 Function Comliant(Object)

     return Object.Code;

 EndFunction

 // Parameters:
 //  Object - Structure - 
 // 
 // Returns:
 //  String - 
 Function Comliant2(Object)

     return Object.Code;

 EndFunction

```
ну и тест с запросом конечно тоже можно. н

2022-10-25 08:26 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ReadingAttributesFromDataBaseCheckTest.java
> +    private static final String PROJECT_NAME = "ReadingAttributesFromDataBaseCheck";
сначала такой вариант сделал, потом чет подумал что с базой будет честнее

добавлю такой тоже для разнообразия

2022-10-25 08:26 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/resources/read-single-property-composite-non-ref.bsl
> +EndFunction
опечатка, поправил

2022-10-25 08:28 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/resources/read-single-property-composite.bsl
> +    Return RefAtt.Code;
тут реквизит составной (две ссылки), сам атрибут получается из ссылки

второй похожий тест ток с одним нессылочным типом, тогда на реквизит ругается, а на код не ругается

2022-10-25 13:27 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ReadingAttributesFromDataBaseCheckTest.java
> +        updateModule(FOLDER_RESOURCE + "read-single-property-compliant-non-ref.bsl");
поправил опечатку

2022-10-25 13:31 UTC, marmyshev requested changes

2022-10-25 14:06 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/resources/read-single-property.bsl
> +//  CatalogRef - CatalogRef.CatalogWrong - Catalog ref
Базу сменил а тест не поправил

2022-10-27 17:07 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ReadingAttributesFromDataBaseCheckTest.java
> +    private static final String PROJECT_NAME = "ReadingAttributesFromDataBaseCheck";
Решили, что простые типы пропускаем, то есть пример следующий не будет диагностирован как ошибка, но в будущем возможно доработать другую проверку, которая будет диагностировать проблемы с отсутствием свойства у типа

```
// Parameters:
 //  Object - CatalogRef, String - 
 // 
 // Returns:
 //  String - 
 Function NoneComliant(Object)

     return Object.Code;

 EndFunction
```

2022-10-28 07:30 UTC, merged