Добавлена проверка переменных расширений
1C-Company/v8-code-style pull request #1130
Opened 2022-08-24 04:43 UTC by iArtemv

## Что сделано

- Добавлена проверка переменных расширений

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #107

2022-09-16 15:21 UTC, marmyshev requested changes

2022-09-16 15:21 UTC, marmyshev commented on CHANGELOG.md
> +- Проверка наличия префикса расширения в переменной расширения.
Просьба перенести на в версию 0.4

2022-10-17 13:32 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionVariablePrefixCheckTest.java
> +        if (!project.exists() || !project.isAccessible())
Согласен, но как-то нормально непонятно как сделать не меняя родительский класс, просто метод с before аннотацией не сработает.

2022-10-27 06:26 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionVariablePrefixCheckTest.java
> +        if (!project.exists() || !project.isAccessible())
Разобрался, что не работало (не в том порядке запускал)

2022-10-27 06:27 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExtensionVariablePrefixCheckTest.java
> +        if (!project.exists() || !project.isAccessible())
Разобрался, что не работало (не в том порядке запускал)

2022-10-27 08:00 UTC, merged