Добавлена првоерка префиксов имен объектов
1C-Company/v8-code-style pull request #1131
Opened 2022-08-24 06:16 UTC by iArtemv

## Что сделано

- Добавлена првоерка префиксов имен объектов

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #324

2022-09-16 15:21 UTC, marmyshev requested changes

2022-09-16 15:21 UTC, marmyshev commented on CHANGELOG.md
> +- Проверка наличия префикса расширения в имени объекта расширения.
Просьба перенести на в версию 0.4

2022-10-13 16:59 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +package com.e1c.v8codestyle.md.check;
Возможно, этот класс должен быть в internal пакете

2022-10-13 16:59 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +    public ExtensionMdObjectNamePrefixCheck(IV8ProjectManager v8ProjectManager)
Javadoc

2022-10-13 16:59 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
Почему мы проверяем наличие проекта конфигурации?

2022-10-13 16:59 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/NonAdoptedInExtensionMdObjectExtension.java
> +    public NonAdoptedInExtensionMdObjectExtension(IV8ProjectManager v8ProjectManager)
Не хватает javadoc'а и отступа после поля ```v8ProjectManager```

2022-10-13 16:59 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +ExtensionMdObjectNamePrefixCheck_Object_0_should_have_1_prefix=The object {0} should have {1} prefix
Возможно, вокруг "{0}" и "{1}" нужны двойные кавычки

2022-10-13 19:27 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
здесь мы проверяем наличие перента у расширения

2022-10-13 19:40 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +package com.e1c.v8codestyle.md.check;
у нас вроде все проверки в текущем классе

2022-10-21 17:08 UTC, marmyshev requested changes

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .features(MD_OBJECT__NAME);
А почему например, реквизиты объекта добавленные в заимствованный объект не должны иметь префикс?

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .extension(new StandardCheckExtension(getCheckId(), CorePlugin.PLUGIN_ID))
Нужно актуализироваться из мастера и добавить код стандарта

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +        String name = mdObject.getName();
Вызов перенести вниз под if -

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +        if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
А зачем лишний вызов парента? При этом если расширение отключили от базового или базовый закрыли, удалили, не успели подключить - то проверка будет "беспричинно" работать по другому :)

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/NonAdoptedInExtensionMdObjectExtension.java
> +                if (extension instanceof IExtensionProject && ((IExtensionProject)extension).getParent() != null)
Излишняя проверка наличия базового проекта

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +    private static final String CHECK_ID = "extension-mdobject-prefix-check"; //$NON-NLS-1$
слово check - бессмысленное, предлагаю удалить (см. конвенцию)

2022-10-21 17:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +    private static final String CHECK_ID = "extension-mdobject-prefix-check"; //$NON-NLS-1$
обычно еще `md-object` пишут - прошу проверить в других проверках чтобы было однообразно

2022-10-31 11:49 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .features(MD_OBJECT__NAME);
Поправил

2022-10-31 13:41 UTC, marmyshev requested changes

2022-10-31 13:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +        return mdObject.eContainer() == null && mdObject.getObjectBelonging() != ObjectBelonging.ADOPTED;
тут надо проверять что это верхнеуровневый - IBmObject.bmIsTop()

2022-10-31 13:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            String prefix = getNamePrefix((IExtensionProject)extension);
classcast exception будет. Нельзя просто так без проверки такое писать.

2022-10-31 13:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .containment(BASIC_COMMAND)
Можно ли заменить на супце-тип `MD_OBJECT`?

2022-10-31 13:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .containment(BASIC_COMMAND)
Возможно тут нужно сделать 2 разных реактора - один на топ объект, другой на контейнменты по супер-типу.

2022-10-31 13:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            && mdObject.getObjectBelonging() != ObjectBelonging.ADOPTED;
1. проверять что это верхнеуровневый - IBmObject.bmIsTop()
2. class-cast exception - будет в `((MdObject)mdObject.eContainer())`

2022-10-31 14:03 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/ExtensionMdObjectNamePrefixCheck.java
> +            .containment(BASIC_COMMAND)
вроде работает с супер типом

2022-11-09 10:36 UTC, merged