Использование конструкции Новый Шрифт
1C-Company/v8-code-style pull request #1134
Opened 2022-08-30 03:32 UTC by iArtemv

## Что сделано

- Проверка использования конструкции Новый Шрифт

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #777

2022-09-16 15:22 UTC, marmyshev requested changes

2022-10-18 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/new-font.md
> +To change the design, you should use style elements, and not
Не уверен, но кажется, вторая запятая лишняя

2022-10-18 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/new-font.md
> +- [Элементы стиля](https://its.1c.ru/db/v8std#content:667:hdoc:1)
В английском варианте написано "Стили и элементы стиля"

2022-10-18 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +NewFontCheck_Description=To change the font, you should use style elements
Кажется, запятая лишняя

2022-10-18 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +NewFontCheck_Issue=To change the font, you should use style elements
И тут

2022-10-18 14:55 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/NewFontCheckTest.java
> +    public NewFontCheckTest()
Javadoc

2022-10-18 14:55 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/NewFontCheckTest.java
> +        updateModule(FOLDER_RESOURCE + "new-font.bsl");
nls, аналогичное замечание далее по классу

2022-10-18 14:55 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/NewFontCheckTest.java
> +    private static final String NEW_FONT = "To change the font, you should use style elements";
nls

2022-10-21 16:53 UTC, marmyshev requested changes

2022-10-21 16:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/NewFontCheck.java
> +                        String name = line.replace("\"", ""); //$NON-NLS-1$ //$NON-NLS-2$
Здесь вместо цикла и замены символов - лучше использовать операцию StringLiteral.lines(true) - и просто взять первую строку. Можно проверить еще что строк всегда = 1.

2022-10-21 16:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/NewFontCheck.java
> +    private void addResultAcceptor(Object object, ResultAcceptor resultAceptor, String name)
addResultAcceptor = "добавить принимателя результата" - как-то совсем бессмысленное название метода, не имеющее отношение к сути: "проверить имя типа и добавить ошибку"

2022-10-21 16:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/NewFontCheck.java
> +    private void addResultAcceptor(Object object, ResultAcceptor resultAceptor, String name)
Кажется, какой-то стабильный копипаст в классах которые ты делаешь - предлагаю отдельно сделать поиск и рефакторинг :)

2022-10-21 16:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/new-font.md
> +- [Styles and style elements](https://support.1ci.com/hc/en-us/articles/4403174580370-5-5-22-Styles-and-style-elements)
нужно актуализировать ссылку

2022-10-26 18:58 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/new-font.md
> +- [Элементы стиля](https://its.1c.ru/db/v8std#content:667:hdoc:1)
здесь заголовок из стандарта

2022-10-27 11:30 UTC, merged