#232 Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции"
1C-Company/v8-code-style pull request #1136
Opened 2022-08-31 19:30 UTC by olgabozhko

## Что сделано

- Добавлена проверка расположения устаревшей экспортной процедуры (функции): устаревшая процедура (функция) должна быть перенесена в перенести в область общего УстаревшиеПроцедурыИФункции, которая размещена внутри области ПрограммныйИнтерфейс.

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #232

2022-09-16 15:22 UTC, marmyshev requested changes

2022-09-16 15:22 UTC, marmyshev commented on CHANGELOG.md
> +- Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции"
Просьба перенести на в версию 0.4

2022-09-16 16:25 UTC, marmyshev requested changes
С учетом переделки логики - предлагаю удалить тестовый проект и перейти в тестах просто на проект `CommonModule`

А в остальном вроде всё ок.

2022-09-16 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +            if (defMethod != null && defMethod.isDeprecated() && (getModuleType(method) != ModuleType.COMMON_MODULE
в стандарте слово "Общий модуль" - подозреваю, противоречит сути. Поэтому кажется что условие на общий модуль тут лишнее.

Поясню:
 - экспортные должны быть в "паблике", это означает - например в менеджере или в модуле объекта тоже может быть область "паблик" - это нормально не только для общего модуля - у любых у кого может быть программный интерфейс.
 - но  экспортные могут и не быть в паблике - если это например клиентский модуль и описание оповещения (клиентский call-back для модальных функций).

Поэтому можно сразу добавить фильтр `com.e1c.v8codestyle.bsl.check.ModuleTypeFilter.onlyTypes(ModuleType...)` на типы модулей в которых может - посмотреть у каких типов есть паблик можно тут com.e1c.v8codestyle.bsl.ModuleStructure

2022-09-16 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +            && regionTop.get().getName().equals(ModuleStructureSection.PUBLIC.getNames()[1]))
тут лучше использовать com.e1c.v8codestyle.bsl.ModuleStructureSection.getName(ScriptVariant) т.к. термины явно привязаны к варианту скрипта проекта.

Вариант скрипта можно взять из сервиса `IV8ProjectManager`  - инжектить в конструктор

2022-09-16 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +        else if (regionFirst.get().getName().equals(DEPRECATED_REGION)
Предлагаю DEPRECATED_REGION - добавить в перечисление `com.e1c.v8codestyle.bsl.ModuleStructureSection`

2022-09-19 17:39 UTC, olgabozhko commented on CHANGELOG.md
> +- Устаревшая процедура (функция) расположена вне области "УстаревшиеПроцедурыИФункции"
Перенесла.

2022-09-19 17:45 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +            if (defMethod != null && defMethod.isDeprecated() && (getModuleType(method) != ModuleType.COMMON_MODULE
Поправила, спасибо за объяснение. И у меня пара вопросов)
1. для StandardCheckExtension теперь требуется указывать номер стандарта - я добавила константу, может быть, надо было как-то по другому сделать? 
2. Если уже указана #Область (#Region), но еще не указано название области, то в логе можно увидеть NPE - это какая-то известная проблема?
```
!MESSAGE Language check thrown an exception:false
!STACK 0
java.lang.NullPointerException
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1224)
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1218)
	at java.base/java.util.TreeMap.compare(TreeMap.java:1292)
	at java.base/java.util.TreeMap.put(TreeMap.java:536)
	at java.base/java.util.Map.putIfAbsent(Map.java:775)
	at com.e1c.v8codestyle.bsl.check.ModuleStructureTopRegionCheck.countDoublesAndFindTopRegions(ModuleStructureTopRegionCheck.java:278)
	at com.e1c.v8codestyle.bsl.check.ModuleStructureTopRegionCheck.check(ModuleStructureTopRegionCheck.java:135)
	at com.e1c.v8codestyle.bsl.check.ModuleStructureTopRegionCheck.check(ModuleStructureTopRegionCheck.java:125)
	...
```

2022-09-19 17:46 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +            && regionTop.get().getName().equals(ModuleStructureSection.PUBLIC.getNames()[1]))
Поправила.

2022-09-19 17:46 UTC, olgabozhko commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/DeprecatedProcedureOutsideDeprecatedRegionCheck.java
> +        else if (regionFirst.get().getName().equals(DEPRECATED_REGION)
Добавила в перечисление.

2022-10-21 15:27 UTC, marmyshev approved these changes

2022-10-21 15:28 UTC, merged