Проверка максимального кол-ва пустых строк
1C-Company/v8-code-style pull request #1137
Opened 2022-09-01 05:50 UTC by iArtemv

## Что сделано

- Добавлена проверка максимального кол-ва пустых строк подряд

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1129

2022-09-07 13:11 UTC, marmyshev requested changes
А квит-фикс по удалению будет? :)

2022-09-07 13:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +                    NodeModelUtils.findActualSemanticObjectFor(leafNode));
Предлагаю это переделать на прямое указание ошибки по координатам (кажется BslDirectIssue) - иначе позиционирование будет валиться всё на текущий блок, стейтмент или какой-то другой логически несвязный семантический элемент модуля, что по сути бессмысленно для этой проверки.

2022-09-07 13:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +            .issueType(IssueType.CODE_STYLE)
не указан уровень критичности - тривиальный

2022-09-07 13:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +            .disable()
Это расширение перекроет флаг отключения и включит проверку тут. если требуется поставлять ее всегда отключенной - то не нужно добавлять в CommonSenseCheckExtension

2022-09-07 13:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +    private static final String CHECK_ID = "consecutive-empty-lines"; //$NON-NLS-1$
тут, согласно проверке, строки могут быть не empty, но при этом blank.

А такая проверка может быть для других языков (запросов, выражений)? тогда следует добавить слово `bsl-` или `module-consecutive-blank-lines` [согласно конвенции](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/Check_Convention.md#разделение-по-типам-объектов-метаданных)

2022-09-07 13:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +                    NodeModelUtils.findActualSemanticObjectFor(leafNode));
Предлагаю подсвечивать ровно те строки которые больше чем максимальное разрешенное количество пустых - чтобы разработчик видел подчеркнутое и ровно их удалял.

2022-09-07 13:11 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ConsecutiveEmptyLinesCheckTest.java
> +        assertEquals("The sequence of empty lines between lines 1 and 4 is 2 or greater", marker.getMessage());
Здесь не нужно тестировать текст. Нужно тестировать позицию маркера где оно отображается.

2022-09-16 15:22 UTC, marmyshev requested changes

2022-09-16 15:22 UTC, marmyshev commented on CHANGELOG.md
> +- Добавлена проверка максимального количества допустимых пустых строк.
Просьба перенести на в версию 0.4

2022-09-16 19:52 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ConsecutiveEmptyLines_Parameter_title=Number of empty lines
переделал, параметр будет означать максимально допустимое количество пустых строк

2022-09-19 08:43 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +                && (endLine - startLine) > number)
поправил, в таком сцерании будет считаться что максимальное количество строк пустых 0

2022-10-04 14:04 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +    public ConsecutiveEmptyLinesCheck(BslGrammarAccess grammarAccess)
Не хватает javadoc'а

2022-10-04 14:04 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ConsecutiveEmptyLinesCheckTest.java
> +    public void testWithEmptyLines() throws Exception
Предлагаю переименовать метод в `testWithManyEmptyLines`

2022-10-04 14:04 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ConsecutiveEmptyLinesCheckTest.java
> +    public void testWithOneEmptyLines() throws Exception
Кажется, правильнее "testWithOneEmptyLine"

2022-10-10 19:54 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +                    && (endLine - startLine - 1) > numberAllowedLines)
startLine и endLine это непустые строки (например 1 и 4), чтобы определить количество непустых строк (2 и 3) нужно исключить непустую строку после вычитания.

2022-10-10 19:58 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +                        Messages.ConsecutiveEmptyLines_Sequence_of_empty_lines_between_0_and_1_is_2_or_greater,
да, тут смысл параметра сменился, переменную не переименовал. Поправил.

2022-10-10 20:11 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +        int sum = 0;
текущий вариант вроде корректней позиционирует

2022-10-10 20:17 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ConsecutiveEmptyLinesCheck.java
> +        return sum + lines[lines.length - 1].length();
Думаю тут неудачно sum засунул, поправил

2022-10-10 20:44 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java
> +    public static String ConsecutiveEmptyLines_Sequence_of_empty_lines_between_0_and_1_is_2_or_greater;
Вроде встречал стандарт, сходу не нашел, думаю два надо

2022-10-10 20:46 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ConsecutiveEmptyLines_Parameter_title=Максимальное количество пустых строк
согласен

2022-11-09 13:46 UTC, marmyshev requested changes

2022-11-09 13:46 UTC, marmyshev commented on CHANGELOG.md
> +- Проверка максимального количества допустимых пустых строк
Нужно добавить инфу о квикфиксе в секцию ниже

2022-11-09 13:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/module-consecutive-blank-lines.md
> +EndTry;
Какой-то пример сильно отличающийся от русского варианта - желательно чтобы пример акцентировал проблему, сильно лишний код не нужен.

2022-11-09 13:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/qfix/ConsecutiveEmptyLinesFix.java
> +@QuickFix(checkId = "module-consecutive-blank-lines", supplierId = "com.e1c.v8codestyle.bsl")
тут правильно использовать ссылку на константу BslPlugin.PLUGIN_ID

2022-11-09 13:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ConsecutiveEmptyLines/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.21
неправильная версия

2022-11-09 13:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ConsecutiveEmptyLines/.settings/com.e1c.v8codestyle.prefs
> +standardChecks=true
лишние файлы

2022-11-09 13:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ConsecutiveEmptyLines/.settings/com.e1c.v8codestyle.bsl.prefs
> +eclipse.preferences.version=1
лишние файлы

2022-11-09 13:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ConsecutiveEmptyLines/src/CommonModules/CommonModule/Module.bsl
> +	B = 2;
вот этого примера достаточно для документации было бы :)

2022-11-09 13:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ConsecutiveEmptyLines/.project
> +	<name>ConsecutiveEmptyLines</name>
А для чего тут эксклюзивный проект для одного микро-модуля?

2022-11-11 10:21 UTC, merged