#84 Добавлена проверка длины ресурса регистра накопления или бухгалтерии
1C-Company/v8-code-style pull request #1139
Opened 2022-09-02 14:57 UTC by muhtimur

## Что сделано

- Добавлена проверка длины ресурса регистра накопления или бухгалтерии

## Чек-лист

Общее:
- [* ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [* ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [* ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #84

2022-09-06 01:25 UTC, muhtimur commented
@1C-Company @marmyshev  @vadimeg прошу сделать аудит

2022-09-16 15:23 UTC, marmyshev requested changes

2022-09-16 15:23 UTC, marmyshev commented on CHANGELOG.md
> +- Превышена максимальная длина ресурса регистра накопления или бухгалтерии (25 знаков)
Просьба перенести на в версию 0.4

2022-09-16 15:34 UTC, muhtimur commented on CHANGELOG.md
> +- Превышена максимальная длина ресурса регистра накопления или бухгалтерии (25 знаков)
Готово

2022-09-16 15:34 UTC, marmyshev approved these changes

2022-09-16 18:20 UTC, merged