#1178 Использование экспортных переменных в модулях объектов
1C-Company/v8-code-style pull request #1179
Opened 2022-10-17 19:09 UTC by iArtemv

## Что сделано

- Проверка использования экспортных переменных в модуле объекта

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [x] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1178

2022-10-21 16:09 UTC, marmyshev requested changes

2022-10-21 16:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportVariableInObjectModuleCheck.java
> +        }
Предлагаю перенести это в расширение фильтрации ModuleTypeFilter

2022-10-21 16:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportVariableInObjectModuleCheck.java
> +        }
Кстати, а в модуле формы/команды можно переменные экспортные?

2022-10-21 16:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ExportVariableInObjectModuleCheck_Title=Export variable
Экспортная переменная... что? Чехов гордится, но тут подозреваю что будет не очень понятно для пользователей :)

аналогично в русском.

2022-10-21 16:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportVariableInObjectModuleCheck.java
> +    private static final String CHECK_ID = "export-variable-object-module"; //$NON-NLS-1$
Предлагаю поменять object-module-export-variable - как-то более правильно по смыслу (а то было бы что "модуль объекта содержится в экспортной переменной")).

Аналогично имя класса

2022-10-21 16:09 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ExportVariableInObjectModuleCheck/.settings/com.e1c.v8codestyle.prefs
> +eclipse.preferences.version=1
лишние файлы

2022-10-21 16:09 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ExportVariableInObjectModuleCheck/.settings/com.e1c.v8codestyle.autosort.prefs
> +eclipse.preferences.version=1
лишние файлы

2022-10-21 16:09 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ExportVariableInObjectModuleCheck/.settings/com.e1c.v8codestyle.bsl.prefs
> +createModuleStructure=false
лишние файлы

2022-10-21 16:09 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/ExportVariableInObjectModuleCheck/.project
> +	<name>ExportVariableInObjectModuleCheck</name>
На всякий случай проверь - может быть есть уже общий проект  со справочником, которые используется для быстрых тестов

2022-10-26 18:10 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportVariableInObjectModuleCheck.java
> +        }
Для модулей форм тоже есть ограничения, но там много исключений который автоматически непонятно как обработать, вероятно придется много объектов исключать из проверки.
Возможно для форм стоит вынести в отдельную проверку для возможности гибкой настройки либо сделать опцию для текущей проверки.

2022-10-26 18:30 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportVariableInObjectModuleCheck.java
> +    private static final String CHECK_ID = "export-variable-object-module"; //$NON-NLS-1$
поправил

2022-10-27 14:11 UTC, merged