#234 Кэширование программного интерфейса
1C-Company/v8-code-style pull request #1180
Opened 2022-10-18 18:31 UTC by iArtemv

## Что сделано

- Проверка кэширования программного интерфейса

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [x] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #234

2022-10-31 08:20 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +CachedPublicCheck_Description=Кэширование интерфейсного метода
Title и description прям совпадают:)

2022-10-31 12:10 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +CachedPublicCheck_Description=Кэширование интерфейсного метода
description при сборке заменяется информацией из markdown

2022-11-11 12:23 UTC, marmyshev requested changes

2022-11-11 12:23 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CachedPublicCheck.java
> +        Module module = EcoreUtil2.getContainerOfType(method, Module.class);
тут можно region использовать - т.к. он уже точно самый верхний и далее один контейнер обычно до модуля.

2022-11-11 12:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CachedPublicCheck/src/CommonModules/CommonModuleCached/Module.bsl
> +#EndRegion
нужен еще тест на правильное состояние в этом типе модуля

2022-11-11 12:23 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CachedPublicCheck.java
> +    private static final String CHECK_ID = "cached-public"; //$NON-NLS-1$
предлагаю улучшить понятность кода))

2022-11-22 17:17 UTC, merged