Общий модуль должен иметь программный интерфейс
1C-Company/v8-code-style pull request #1182
Opened 2022-10-18 20:04 UTC by iArtemv

## Что сделано

- Проверка что общий модуль содержить программный интерфейс

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1181

2022-11-01 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/common-module-missing-api.md
> +# The common module must have at least one export method
Вариант этой фразы на русском звучит так "Общий модуль должен иметь программный интерфейс", тут не прямой перевод

2022-11-01 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java
> +    public static String CommonModuleMissingAPICheck_Description;
Правильно ```CommonModuleMissingApiCheck_Description```. Аналогичное замечание для остальных переменных

2022-11-01 14:55 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommonModuleMissingApiCheck.java
> +                found = true;
Предлагаю тут добавить прерывание цикла

2022-11-11 12:27 UTC, marmyshev requested changes

2022-11-11 12:27 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommonModuleMissingApiCheck.java
> +        for (Method method : module.allMethods())
а зачем вешать ошибки на каждый метод модуля? проверка будет срабатывать на каждом методе.

да, потом можно повесить на первый метод, но нет смысла проверять много раз одно и то же.

2022-11-11 12:27 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CommonModuleMissingAPICheck/.project
> +	<name>CommonModuleMissingAPICheck</name>
Зачем тут нужен этот проект?

2022-11-23 08:20 UTC, marmyshev requested changes

2022-11-23 08:20 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/common-module-missing-api.md
> +## См.
Ссылки на стандарты, примеры правильно-неправильно...

2022-11-23 08:20 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommonModuleMissingApiCheck.java
> +        {
Это не до конца верное поведение - в расширении (только в заимоствованных!) - могут быть методы, которые переопределяют не-экспортные методы.

2022-11-23 08:24 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommonModuleMissingApiCheck.java
> +        {
Так вроде общий модуль проектируется без оглядки на будущие расширения, либо я не совсем понял замечание.

2023-01-23 07:01 UTC, merged