Привилегированный общий модуль должен иметь постфикс ПолныеПрава
1C-Company/v8-code-style pull request #1184
Opened 2022-10-21 12:45 UTC by iArtemv

## Что сделано

- Проверка постфикса в имени общего модуля с признаком привилегированный

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #473

2022-11-01 14:47 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/CommonModuleNamePrivilegedCheckTest.java
> +    private void updateCommonModule(IDtProject dtProject, String fqn, CommonModuleTypes type, boolean isPrivileged,
Не настаиваю, а почему не сделать сразу в исходной конфигурации два модуля (правильный и неправильный) и тогда вообще не нужен будет этот метод?

2022-11-09 13:43 UTC, iArtemv commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/CommonModuleNamePrivilegedCheckTest.java
> +    private void updateCommonModule(IDtProject dtProject, String fqn, CommonModuleTypes type, boolean isPrivileged,
Тут общий проект, на нем очень много разных тестов и большое количество различных вариантов. Если под каждый создавать объекты, база сильно разрастется.

2023-01-23 07:06 UTC, marmyshev requested changes

2023-01-23 07:06 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/plugin.xml
> +            category="com.e1c.v8codestyle.bsl"
Неправильная категория

2023-01-23 08:06 UTC, marmyshev approved these changes

2023-01-23 11:11 UTC, merged