#499 Глобальный клиентский модуль не должен содержать постфикс Клиент
1C-Company/v8-code-style pull request #1194
Opened 2022-11-01 12:01 UTC by iArtemv

## Что сделано

- Не следует добавлять постфикс Клиент в имени глобального модуля

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #499

2022-11-10 06:15 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +        builder.title(Messages.CommonModuleNameGlobal_title)
Правильное название переменной по нашим стандартам ``CommonModuleNameGlobalClientCheck_Title``, аналогичное замечание к другим переменным

2022-11-10 06:15 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +        String suffixe = ScriptVariant.ENGLISH == variant ? NAME_SUFFIX_EN : NAME_SUFFIX_RU;
suffixe -> suffix

2022-11-10 06:15 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/CommonModuleNameGlobalClientTest.java
> +public class CommonModuleNameGlobalClientTest
Возможно, более правильное название класса CommonModuleNameGlobalClient**Check**Test

2022-11-10 06:15 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/CommonModuleNameGlobalClientTest.java
> +    private void updateCommonModule(IDtProject dtProject, String fqn, CommonModuleTypes type, String newFqn)
Я бы добавил два разных модуля (валидные и не валидный) в тестовую конфигурацию и избавился бы от этого метода, время прохождения теста увеличивается с ним.

2022-11-11 11:34 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/markdown/common-module-name-global-client.md
> +3.2.1. Add the "Global" postfix for global modules. In this case, you do not need to add the "Client" postfix.
вроде тут нужна

2022-11-12 09:30 UTC, iArtemv commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/CommonModuleNameGlobalClientTest.java
> +    private void updateCommonModule(IDtProject dtProject, String fqn, CommonModuleTypes type, String newFqn)
здесь еще заодно проверяется что происходит реакция при изменении данных

2023-01-23 06:55 UTC, marmyshev requested changes

2023-01-23 06:55 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +            .description(Messages.CommonModuleNameGlobal_Description)
Косяк, использование чужих ключей от другой проверки

2023-01-23 06:55 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +            String message = MessageFormat.format(Messages.CommonModuleNameGlobal_Message, suffix);
Косяк, использование чужих ключей от другой проверки

2023-01-23 06:55 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +CommonModuleNameGlobal_Message=Global common module should not end with "{0}" suffix
Испорчен смысл для исходной чужой проверки

2023-01-23 06:55 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
> +CommonModuleNameGlobal_Message = Глобальный общий модуль не должен оканчиваться на суффикс "{0}"
Испорчен смысл для исходной чужой проверки

2023-01-23 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +    private static final String NAME_SUFFIX_EN = "GlobalClient"; //$NON-NLS-1$
А точно нужно использовать слово Глобальный в проверке? вдруг будет порядок слов другой

2023-01-23 07:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobalClientCheck.java
> +        if (name.endsWith(suffix))
А если будет "ОбщегоНазначенияГлобальныйКлиентЛокализация"? тогда проверка ошибки не найдет, это правильно?

2023-01-24 03:19 UTC, merged