Использование устаревшего метода Найти
1C-Company/v8-code-style pull request #1199
Opened 2022-11-02 06:11 UTC by iArtemv

## Что сделано

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1198

2022-11-15 09:34 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/UseNonRecommendedMethodTest.java
> +        updateModule(FOLDER_RESOURCE + "use-non-recommended-method-find.bsl");
nls

2023-03-16 04:36 UTC, marmyshev requested changes

2023-03-16 04:36 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseNonRecommendedMethodCheck.java
> +        "Найти", //$NON-NLS-1$
Наверно надо еще в описание проверок добавить варианты что на что надо заменять и почему. А то будут в недоумении разработчики

2023-03-16 05:08 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseNonRecommendedMethodCheck.java
> +        "Найти", //$NON-NLS-1$
поправил

2023-03-16 06:59 UTC, merged