#1 Перенос проверок по правам
1C-Company/v8-code-style pull request #12
Opened 2021-07-04 14:55 UTC by marmyshev

2021-08-11 17:33 UTC, DoublesunRUS requested changes

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveSetDeletionMarkPredefinedData.java
> +        return RightName.INTERACTIVE_SET_DELETION_MARK_PREDEFINED_DATA;
Я у себя переделывал, это значение хранил в строковой константе, чтобы потом каждый раз getName() не дергать.

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +        if (right != null && getRightName().getName().equals(right.getName()))
Внутри есть другие условия, значит для вложенных условий повышается когнитивная сложность. Надо по этому условию сразу выходить.

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/messages_ru.properties
> +#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)
В двух местах эта строка. Может для порядка оставлять только верхнюю?

2021-08-11 17:33 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.right.itests/META-INF/MANIFEST.MF
> +Automatic-Module-Name: com.e1c.v8codestyle.md.itests
Копипаст детектед.

2021-08-11 17:33 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasForbiddenTest.java
> +    public void testRoleHasRightInteracitveDeleteMarkedPredefinedData() throws Exception
Одинаковый код проверки во всех тестах.
Я поэтому в своём ЗнС по ролям сделал абстрактный класс с двумя методами: Проверить наличие роли и проверить отсутствие.

2021-08-11 17:33 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> +        IDtProject dtProject = openProjectAndWaitForValidationFinish(PROJECT_NAME);
В прошлом тестовом классе была надстройка для вызова проекта 1 раз. А в этом нет. Хотя я по коду не вижу чтобы конфигурация менялась.

2021-08-11 17:33 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> +        assertEquals(2, rights.getRights().size());
Проверяем что записи две, а дальше по тесту валидируем только одну. Это правильно?

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/Messages.java
> +    public static String RoleRightHasRls_Exclude_Right_Object_name_pattern;
А мы разве должны выделять слова большими буквами, раз пишем _?

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +            .issueType(IssueType.WARNING)
Может для проверки прав правильно IssueType.SECURITY?

2021-08-11 17:33 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/markdown/ru/role-right-has-rls.md
> +
Предлагаю везде по одной строке оставлять.

2021-08-11 17:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/Messages.java
> +/**
Не, для NLS не нужны - автогенерируемые

2021-08-11 17:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightHasRls.java
> +    private static final String ROLE_NAME_PATTERN_PARAMETER_DEFAULT =
паттерн - это RegEx, поэтому вертикальная черта - разделитель вариантов.

Может надо было сделать 2 параметра: role name list и role name pattern - чтобы можно было задавать удобно в первом параметре и гибко во втором.

Если что, можем добавить потом.

2021-08-11 17:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveSetDeletionMarkPredefinedData.java
> +        return RightName.INTERACTIVE_SET_DELETION_MARK_PREDEFINED_DATA;
А для чего заводить еще одну константу и хранить в памяти?

2021-08-11 17:59 UTC, marmyshev commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> +        assertEquals(2, rights.getRights().size());
Там добавляется все объекты - в т.ч. конфигурация - у Конфигурации - не бывает РЛС, как бы нечего проверять.

2021-08-11 18:01 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveSetDeletionMarkPredefinedData.java
> +        return RightName.INTERACTIVE_SET_DELETION_MARK_PREDEFINED_DATA;
Зачем функцией возвращать RightName, если тебе нужно name? не проще сразу тут String возвращать?

2021-08-11 18:02 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/markdown/ru/role-right-has-rls.md
> +
Почему? я бы понял, если бы настоятельно предложил тут написать текст описания проверки...  :)

после заголовка - пустая строка, потом тест описания, потом еще одна пустая строка - вот 3 строки в шаблоне.

2021-08-11 18:07 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/markdown/ru/role-right-has-rls.md
> +
Ну либо везде 3, либо везде 1. А почему где-то 3, а где-то 1, непонятно. :)

2021-08-11 18:09 UTC, marmyshev commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> +        IDtProject dtProject = openProjectAndWaitForValidationFinish(PROJECT_NAME);
Хотел показать этот код для SingleProjectBasicCheck - поэтому написал один раз. копипастить пока не буду, надо добиться чтобы в ЕДТ доработали

2021-08-11 18:11 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> +        IDtProject dtProject = openProjectAndWaitForValidationFinish(PROJECT_NAME);
Так сделай общий класс, потом заменишь название класса :)

2021-08-11 18:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightHasRls.java
> +    protected void check(Object object, ResultAcceptor resultAceptor, ICheckParameters parameters,
Ну ок, посмотрим в твоем запросе эту переделку :)

2021-08-11 18:19 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/markdown/ru/role-right-has-rls.md
> +
А я надеялся что придет специально обученный человек и напишет за нас. :)

2021-08-11 18:28 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/messages_ru.properties
> +#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)
Мне кажется что он теперь вставляет вверх. А если изменить через него какой-то русский и английский вариант, то он вставит наверх, отсортирует все поля. А нижний будет считать традиционным комментарием.

2021-08-11 18:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveSetDeletionMarkPredefinedData.java
> +        return RightName.INTERACTIVE_SET_DELETION_MARK_PREDEFINED_DATA;
Опасно. Нужно тогда регламентировать какое имя из двух нужно возвращать, русское или английское.
К тому же утилиты из ЕДТ работают с RightName а не с парой строк. Объект из константы  лучше чем строка. Так вот показалось мне.

2021-08-11 18:46 UTC, marmyshev commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasForbiddenTest.java
> +    public void testRoleHasRightInteracitveDeleteMarkedPredefinedData() throws Exception
В тесте должно быть очевидно что он делает: должны быть понятны начальные данные, тело теста и проверка результата. сворачивать несколько строк в одну процедуру чтобы потом человек пытался понять что делает процедура - можно, но не стоит слишком сильно увлекаться этим именно в  тестах.

2021-08-11 18:48 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +        if (right == null || !getRightName().getName().equals(right.getName()))
Вот у тебя единственная строка где ты с RightName работаешь.

2021-08-11 19:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +        if (right == null || !getRightName().getName().equals(right.getName()))
Да. Ты предлагаешь на уровне контракта API убрать объект-перечисление и заменить его на неконтроллируемую, непонятную строку, с произвольным содержанием, которую как-то дополнительно нужно регламентировать на уровне API и проверять что она пришла корректная от потребителя? :) не сильно хорошее предложение.

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/plugin_ru.properties
> +category.ritht.description = Проверки Прав ролей (Rights, файлы *.rights) по стандартам
Некодированные русские символы - опять где-ндь вылезут проблемы

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteracitveDelete.java
> + * Checks that hole has forbidden right: {@code INTERACTIVE_DELETE} for any objects.
Неверное, все же не дыра, а role :)))))

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteracitveDeleteMarkedPredefinedData.java
> + * Checks that hole has forbidden right: {@code INTERACTIVE_DELETE_MARKED_PREDEFINED_DATA} for any objects.
hole->role

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteracitveDeletePredefinedData.java
> + * Checks that hole has forbidden right: {@code INTERACTIVE_DELETE_PREDEFINED_DATA} for any objects.
hole->role

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveClearDeletionMarkPredefinedData.java
> + * Checks that hole has forbidden right: {@code INTERACTIVE_CLEAR_DELETION_MARK_PREDEFINED_DATA} for any objects.
hole->role

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RightInteractiveSetDeletionMarkPredefinedData.java
> + * Checks that hole has forbidden right: {@code INTERACTIVE_SET_DELETION_MARK_PREDEFINED_DATA} for any objects.
hole->role

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightHasRls.java
> +    public RoleRightHasRls(IV8ProjectManager v8ProjectManager, IBmModelManager bmModelManager)
JavaDoc

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> + * Abstract check that hole has some right for any object.
hole->role

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +    public RoleRightSetCheck(IV8ProjectManager v8ProjectManager, IBmModelManager bmModelManager)
JavaDoc

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +            RoleDescription description = EcoreUtil2.getContainerOfType(objectRight, RoleDescription.class);
Выше точно такой же блок по получению роли, но код другой. При этом получение IBmModel может делаться два раза, что неэффективно.
Эффективнее получать один раз перед этими ветвлениями

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +            && objectRight.eResource().getContents().get(0) instanceof RoleDescription)
Что-то из ряда вон. БМ-я модель, не нужно по ресурсам бегать, не бесплатно и ничего не дает

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +        if (project != null && project.getScriptVariant() == ScriptVariant.RUSSIAN)
Проверка на нуль V8Project-а в данном месте лишена смысла (как часть основного алгоритма). Не будут проверки работать без активного контекста в любом случае.
Т.е. если и проверять - то Assert-ом (defencive programming), но не как рабочую ситуацию.

2021-08-12 01:48 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/messages_ru.properties
> +RightInteracitveDeleteMarkedPredefinedData_description = Право роли установлено: Интерактивное удаление помеченных предопределенных данных
Некодированные русские символы - может где-то развалиться

2021-08-12 01:48 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasForbiddenTest.java
> + *
Лишний коммент-блок

2021-08-12 01:48 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasForbiddenTest.java
> +
(Минорное) Прыгает стиль - пробел перед закрывающей оперативной скобкой метода. То есть, то нет.

2021-08-12 01:48 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/right/check/itests/RoleRightHasRlsTest.java
> + *
Пустой коммент-блок

2021-08-12 06:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/plugin_ru.properties
> +category.ritht.description = Проверки Прав ролей (Rights, файлы *.rights) по стандартам
Не, я встроил конвертацию при сборке

2021-08-12 11:11 UTC, merged