#1200 Рекомендуется использовать РеквизитФормыВЗначение
1C-Company/v8-code-style pull request #1201
Opened 2022-11-02 11:28 UTC by iArtemv

## Что сделано

- Рекомендация использовать метод формы РеквизитФормыВЗначение вместо ДанныеФормыВЗначение

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1200

2022-11-15 09:42 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/using-form-data-to-value.md
> +В большинстве случаев, в модулях форм следует использовать метод формы РеквизитФормыВЗначение вместо метода ДанныеФормыВЗначение.
Запятая лишняя

2022-11-15 09:42 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/using-form-data-to-value.md
> +FormDataToValue requires the data type to be specified explicitly.Example:
Нет пробела после точки

2022-11-15 09:42 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/FormDataToValueCheckTest.java
> +    public FormDataToValueCheckTest()
javadoc

2023-03-20 04:45 UTC, marmyshev requested changes

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/FormDataToValueCheck.java
> +            .severity(IssueSeverity.MINOR)
Предлагаю понизить уровень, до информации т.к. сам стандарт - просто рекомендация.

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/FormDataToValueCheck.java
> +            .checkedObjectType(FEATURE_ACCESS);
Некорректно так подписываться на всё, включая динамические методы.

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/FormDataToValueCheck.java
> +public class FormDataToValueCheck
Имя класса не совпадает с кодом проверки. Тем более тут складывается впечатление - что речь про форму, что может вводить в заблуждение...

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/using-form-data-to-value.md
> +ТаблицаПодписей = ДанныеФормыВЗначение(ТаблицаПодписей, Тип("ТаблицаЗначений"));
Код следует обернуть в кавычки, но странно что оно дублируется ниже

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/using-form-data-to-value.md
> +ТаблицаПодписей = РеквизитФормыВЗначение("ТаблицаПодписей");
Код следует обернуть в кавычки

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/using-form-data-to-value.md
> +SignaturesTable = FormDataToValue(SignaturesTable, Type("ValueTable"));
Код следует обернуть в кавычки

2023-03-20 04:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/using-form-data-to-value.md
> +SignaturesTable = FormAttributeToValue("SignaturesTable");
Код следует обернуть в кавычки

2023-03-20 07:29 UTC, marmyshev approved these changes

2023-03-20 08:34 UTC, merged