Проверяет отсутствие кода после асинхронного вызова
1C-Company/v8-code-style pull request #1234
Opened 2023-01-16 06:47 UTC by iArtemv

## Что сделано

- Добавлена проверка отсуствия кода после асинхронного вызова

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1224

2023-01-24 06:53 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/code-after-async-call.md
> +как полностью закончилось исполнение вызванного метода
Тут в конце точка или точка с запятой не нужна?

2023-01-24 06:53 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/code-after-async-call.md
> +Процедура ПредупреждениеЗавершение(ДополнительныеПараметры) Экспорт
Возможно, что более правильное название процедуры ПредупреждениеЗавершени**я**

2023-01-24 06:53 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +        "ShowMessageBox", "ПоказатьПредупреждение", //$NON-NLS-1$ //$NON-NLS-2$
Я тут совсем не уверен, но как-то из наших платформенных артефактов этот список программно нельзя получать? Появятся новые асинхронные метода в платформе, мы их забудем сюда добавить.

2023-01-24 06:53 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +            String nameFeature = featureAccess.getName();
Под этой переменной подразумевается "имя переменной"? Если так, то кажется, более правильное название переменной `featureName`.

2023-01-24 06:53 UTC, AlmazNasibullin commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +    private Statement getStatementFromInvoc(Invocation invocation)
Можно вместо этого метода использовать метод `EcoreUtil2.getContainerOfType(EObject, Class<T>)`.

2023-01-24 06:53 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/resources/async-call-back-descr.bsl
> +Процедура ПредупреждениеЗавершение(ДополнительныеПараметры) Экспорт
Аналогичное замечание к названию метода

2023-01-24 06:53 UTC, AlmazNasibullin commented on tests/com.e1c.v8codestyle.bsl.itests/resources/code-after-async-call-existence.bsl
> +	Текст = "Текст предупреждения";
Кажется, лишнее смещение вправо

2023-01-26 07:17 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/code-after-async-call.md
> +Процедура ПредупреждениеЗавершение(ДополнительныеПараметры) Экспорт
тут именно в контексте завершение выполнения предупреждения

2023-01-26 07:19 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +            String nameFeature = featureAccess.getName();
поправил

2023-01-26 07:22 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +    private Statement getStatementFromInvoc(Invocation invocation)
да, только в данном случае получается что неизвестно какой там тип будет

2023-01-26 07:25 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +        "ShowMessageBox", "ПоказатьПредупреждение", //$NON-NLS-1$ //$NON-NLS-2$
Вроде нет

2023-03-03 02:02 UTC, marmyshev requested changes

2023-03-03 02:02 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +        "ShowMessageBox", "ПоказатьПредупреждение", //$NON-NLS-1$ //$NON-NLS-2$
Можно по контексту платформы собрать все методы у которых есть ОписаниеОповещения, или которые заканчиваются на Async - вынести это в отдельный Кэш-провайдер который по-требованию будут собирать из контекста по версии проверка и кэшировать на время вызова.

Не следует так же забывать про существование асинхронных методов у объектов платформы.

```java
interface AsyncInvocationProvider
{

   // Методы глобального контекста
   Collection<String> getAsyncInvocationNames(Version version);

   // Методы со списком типов в которых они используются
   Map<String, Collection<String>> getAsyncTypeMethodNames(Version version);

}
```

Согласен с @AlmazNasibullin  что асинхронные методы появляются в каждой новой версии платформы.

2023-03-13 11:12 UTC, marmyshev requested changes

2023-03-13 11:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +            Configuration context = configurationProvider.getConfiguration(project.getProject());
Может в качестве контекста предоставить временный ресурс-сет?

2023-03-13 11:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +                    break;
А разве первый цикл тут прерывать не надо? 

тут ошибка могла бы не возникнуть, если бы не процедура и называлась` boolean isMethodAsync(Method method) `.

2023-03-13 11:16 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +        Method method = (Method)object;
Небезопасный каст

2023-03-16 06:25 UTC, marmyshev requested changes

2023-03-16 06:25 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/resources/async-call-promise.bsl
> +   Ждать ПредупреждениеАсинх(Текст);
Кажется такой код не может работать в платформе.

Предлагаю рассмотреть 4 корректных примера:


```bsl
Асинх Процедура Тест1(Параметры)
	
	Ждать ВопросАсинх(Параметры,);
	
КонецПроцедуры

Асинх Процедура Тест2(Параметры)
	
	Обещание = ПредупреждениеАсинх(Параметры);
	Ждать Обещание;
	
КонецПроцедуры

Асинх Функция Тест3(Параметры)
	
	Возврат Ждать ПредупреждениеАсинх(Параметры);
	
КонецФункции

Асинх Функция Тест4(Параметры)
	
	Обещание = ПредупреждениеАсинх(Параметры);
	Возврат Ждать Обещание;
	
КонецФункции
```

Я комментировал-комментировал  код поиска стейтментов. Но он просто нерабочий. Следует искать `AwaitExpression` или `AwaitStatement`

2023-03-16 06:54 UTC, marmyshev requested changes

2023-03-16 06:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +            synchronized (this)
Может синхронизироваться на cashNames? тогда к провайдеру можно будет делать параллельный доступ из двух разных методов.

Либо, убрать синхронизацию - и заменить на cashNames.computeIfAbsent() - т.к. коллекция конкурентная.

2023-03-16 06:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +            synchronized (this)
Аналогично во втором методе.

2023-03-16 06:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +        Method method = (Method)object;
Я ранее указывал на небезопасный каст - но исправление довольно веселое :) 

Как в анекдоте про программиста и чайник :) https://habr.com/ru/post/64425/

вместо всего этого - надо было поменять тип параметра.

2023-03-16 06:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +        Method method = (Method)object;
Обрати внимание collectMethods - "Обработать методЫ" - а параметром передается только один метод.

2023-03-16 06:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/AsyncInvocationProvider.java
> +        }
Соррян, но я придумал :) более надежный метод проверки (вдруг если Платформа перестанет добавлять суффикс Асинх) - у метод - есть возвращаемое значение с типом "обещание",  и методы должны быть доступны только на клиенте.

Понимаю что это тяжелее при заполнении. Хз, надо ли переделывать. На твоё усмотрение.

2023-03-22 06:29 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CodeAfterAsyncCallCheck.java
> +            for (TypeItem typeItem : sourceTypes)
Здесь проверяется условие соответствия опции, что в параметр фактически передан ОписаниеОповвещения, если тип отличный, не задан парамер или задан Неопределено - то под условие опции не попадае.

2023-03-22 08:31 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/resources/async-call-promise.bsl
> +   Ждать ПредупреждениеАсинх(Текст);
вроде поправил

2023-04-16 01:46 UTC, marmyshev approved these changes

2023-04-16 01:47 UTC, merged