#262 Реализована проверка использования услов. оформления в дин. списке
1C-Company/v8-code-style pull request #1252
Opened 2023-02-28 23:44 UTC by VAGoncharov

## Что сделано

- Реализована проверка на использование условного оформления в дин. списках.

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #262 

@1C-Company @marmyshev прошу сделать аудит

2023-03-10 03:48 UTC, VAGoncharov commented
@1C-Company @marmyshev прошу сделать аудит

2023-03-13 05:52 UTC, marmyshev requested changes
По сути кода проверки - вопросов нет, но придется алгоритм построить от обратного.

Другой вопрос (имхо) - стандарт немного устарелый, хотя пока еще нужный. Этот стандарт появился из-за проблем платформы которая никак не реагировала на битые ссылки на объекты в условном оформлении - например переименовывается какой-нибудь реквизиты - условное оформление могло оставлять битые ссылки (например форма не захвачена в хранилище) и рантайм Предприятия просто игнорировал проблему - а код хотя бы не компилировался в этом случае, или форма падала при открытии - это позволяло тупо отлавливать ошибки, но нагружать миллионы процессоров ненужным кодом в процессе открытия формы. Опять же ИМХО - было бы полезней сделать проверку целостности ссылок в условном оформлении формы и настройках ДС - сделать их критичными. 

Но сейчас эту проверку предлагаю заливать! потом, например, сделать отключенной.

2023-03-13 05:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.dcs.model.settings;version="3.2.0",
Необходимо указывать закрывающую версию - 4.0

2023-03-13 05:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DynamicListConditionalAppearanceUseCheck.java
> +            .features(DYNAMIC_LIST_EXT_INFO__LIST_SETTINGS);
Не верная настройка. В данном случае ТОП-объектом topObject() будет являться DataCompositionSettings а подчиненным объектом containment() DataCompositionConditionalAppearance - соответственно фичи features() проверять - то что лежит в conditionalAppearance.getItems() 

Это модель СКД, но т.к. в данном случае только ее часть заимствована в формы - полагаю, что можно проверку оставить в текущем банде (а не выносить в отдельный по СКД, которого сейчас нет).

Так же SkipBaseFormExtension - это расширение будет не применимо для СКД, но подозреваю, что следует нечто аналогичное сделать для проверки что это не базовая форма - лучше проверить, при заимствовании формы - эти настройки тоже заимствуются в модель базовой формы или нет.

2023-03-13 05:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +
как-то немножко сортировка вышла неудачной :) заголовок следует размещать выше всех данных. Видимо файл изначально был кривоватый для редактора RBE

2023-03-13 05:52 UTC, marmyshev commented on tests/com.e1c.v8codestyle.form.itests/workspace/DynamicListConditionalAppearanceUse/.settings/Default.cset
> +    "deprecated-procedure-outside-deprecated-region": {
Файл бесполезный, нужно удалить.

2023-03-13 05:52 UTC, marmyshev commented on tests/com.e1c.v8codestyle.form.itests/workspace/DynamicListConditionalAppearanceUse/src/Catalogs/TestCatalog1/Forms/ListForm/ConditionalAppearance.dcssca
> +<ConditionalAppearance xmlns="http://v8.1c.ru/8.1/data-composition-system/settings" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dcscor="htt
Вроде в данном тесте у самой формы не проверяется условное оформление, полагаю, файл не нужный?

2023-03-13 05:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DynamicListConditionalAppearanceUseCheck.java
> +            .features(DYNAMIC_LIST_EXT_INFO__LIST_SETTINGS);
Полагаю, что для нахождения реквизита формы - понадобится сервис com._1c.g5.v8.dt.metadata.IExternalPropertyManager - который позволит получить владельца (реквизит формы) внешнего свойства (в данном случае для объекта DataCompositionSettings)

2023-03-13 05:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DynamicListConditionalAppearanceUseCheck.java
> +                formAttribute.getName()), formAttribute);
После переделки - тут следует указывать вместо formAttribute объект conditionalAppearance и третьим параметром фичи из `DATA_COMPOSITION_CONDITIONAL_APPEARANCE__ITEMS`

2023-03-14 03:15 UTC, VAGoncharov commented on tests/com.e1c.v8codestyle.form.itests/workspace/DynamicListConditionalAppearanceUse/.settings/Default.cset
> +    "deprecated-procedure-outside-deprecated-region": {
Лишние файлы удалены

2023-03-14 03:16 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +
Смержил с мастером, отсортировал. Проблема ушла.

2023-03-14 03:28 UTC, VAGoncharov commented on tests/com.e1c.v8codestyle.form.itests/workspace/DynamicListConditionalAppearanceUse/src/Catalogs/TestCatalog1/Forms/ListForm/ConditionalAppearance.dcssca
> +<ConditionalAppearance xmlns="http://v8.1c.ru/8.1/data-composition-system/settings" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dcscor="htt
Не нужен, удалил. EDT почему-то сама не удаляет файлы с пустами настройками, модулями и т.д.

2023-03-14 21:34 UTC, RedMammoth commented
Может в этой же проверке зацепить задачу https://github.com/1C-Company/v8-code-style/issues/593?

2023-03-20 07:59 UTC, VAGoncharov commented
> Может в этой же проверке зацепить задачу #593?

@RedMammoth Учитывая написанное выше, целесообразность этой проверки пока что под сомнением.

2023-03-25 15:37 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DynamicListConditionalAppearanceUseCheck.java
> +            .features(DYNAMIC_LIST_EXT_INFO__LIST_SETTINGS);
@marmyshev Замечания понятны. 

Но описанный тобою алгоритм превращает задачу в более общую: проверить все настройки компоновки данных, проверить что там есть условное оформление, если есть - вычислить владельца настройки, убедиться что это реквизит формы и указать его имя в сообщении. А если это не реквизит формы, пропускаем? У нас ведь настройки компоновки могут использоваться в отчетах, например. Где еще не вспомню, надо смотреть. Мне сейчас не понятно, что оптимальней - проверять все DYNAMIC_LIST_EXT_INFO на формах или вычислять владельца DataCompositionSettings.

2023-03-25 18:04 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DynamicListConditionalAppearanceUseCheck.java
> +            .features(DYNAMIC_LIST_EXT_INFO__LIST_SETTINGS);
+ С сервисом IExternalPropertyManager пока что проблемка, "Service wait timed out after 60 000 milliseconds" при попытке воспользоваться сервисом через Inject. Нашел эту проблему в группе телеги в 2020 году, возможно с тех пор не поменялось ничего.

Воспользоваться сервисом удалось так:
`
        DataCompositionConditionalAppearance dcca = (DataCompositionConditionalAppearance)object;
        if (monitor.isCanceled() || dcca.getItems() == null || dcca.getItems().isEmpty())
        {
            return;
        }

        IBmModel bmModel = bmModelManager.getModel(dcca);
        IExternalPropertyManager manager = ExternalPropertyManagerProvider.INSTANCE.getExternalPropertyManager(bmModel);
        if (manager == null)
        {
            throw new IllegalStateException("ExternalPropertyManagerProvider not initialized");
        }
        DynamicListExtInfo dl = manager.getOwner((EObject)dcca, DynamicListExtInfo.class);

        if (monitor.isCanceled() || dl == null)
        {
            return;
        }

        FormAttribute formAttribute = EcoreUtil2.getContainerOfType(dl, FormAttribute.class);
        if (monitor.isCanceled() || formAttribute == null)
        {
            return;
        }
`

2023-04-16 18:52 UTC, marmyshev reviewed
Предлагаю исправить локализацию сообщений. В остальном нет вопросов - можно заливать!

2023-04-16 18:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DataCompositionConditionalAppearanceUseCheck.java
> +                "Form attribute", formAttribute.getName()), dcca, DATA_COMPOSITION_CONDITIONAL_APPEARANCE__ITEMS);
Строку "Form attribute" нужно локализировать.  Я предлагаю завести просто 2 различных ключа с разным текстом, и подставлять в 1 имя реквизита, в другой имя формы.

2023-04-16 18:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DataCompositionConditionalAppearanceUseCheck.java
> +                Messages.DataCompositionConditionalAppearanceUseCheck_Dynamic_list_use_conditional_appearance, "Form",
Строку "Form" нужно локализировать. Я предлагаю завести просто 2 различных ключа с разным текстом, и подставлять в 1 имя реквизита, в другой имя формы.

2023-04-17 15:41 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DataCompositionConditionalAppearanceUseCheck.java
> +                "Form attribute", formAttribute.getName()), dcca, DATA_COMPOSITION_CONDITIONAL_APPEARANCE__ITEMS);
Забыл это сделать. Исправлено. Спасибо!

2023-04-17 22:08 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/DataCompositionConditionalAppearanceUseCheck.java
> +                "Form attribute", formAttribute.getName()), dcca, DATA_COMPOSITION_CONDITIONAL_APPEARANCE__ITEMS);
Немного не то сделал)) см. как я переделал

2023-04-18 06:28 UTC, merged