#385 Проверка имени переменной
1C-Company/v8-code-style pull request #1253
Opened 2023-03-01 00:06 UTC by VAGoncharov

## Что сделано

- Проверка имени переменной (стандарт 454)

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #385 #538 

@1C-Company @marmyshev прошу сделать аудит

2023-03-10 03:47 UTC, VAGoncharov commented
@1C-Company @marmyshev прошу сделать аудит

2023-03-13 09:57 UTC, marmyshev requested changes

2023-03-13 09:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +    private int minLength;
Все проверки State-less, то есть нельзя хранить в инстанс проверке какие-либо данные. Это нужно получать из параметра, которые проекто-зависимые.

2023-03-13 09:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +            .checkedObjectType(MODULE)
Нужно подписаться на Variable и DeclareStatement - т.к. может быть частичный пересчет процедуры (например) при котором валидируются только локальные переменные.

2023-03-13 09:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +    private static final String MIN_NAME_LENGTH_PARAM_DEFAULT = MIN_NAME_LENGTH_DEFAULT.toString(); //$NON-NLS-1$
Видел такой прием в нескольких проверках - не очень полезно хранить и константу числом и строку. Достаточно что-то одно.

2023-03-13 09:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +            resultAceptor.addIssue(msg, variable);
нужно/желательно всегда указывать фичу объекта - `NAMED_ELEMNET__NAME` в которой ошибка.  и ниже аналогично...

2023-03-13 13:03 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +    private static final String MIN_NAME_LENGTH_PARAM_DEFAULT = MIN_NAME_LENGTH_DEFAULT.toString(); //$NON-NLS-1$
Переделал

2023-03-13 13:03 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +    private int minLength;
Переделал.

2023-03-13 13:12 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +            resultAceptor.addIssue(msg, variable);
Поправл.

2023-03-13 14:46 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/VariableNameInvalidCheck.java
> +            .checkedObjectType(MODULE)
@marmyshev Переделал проверку. Под подписку Variable попадают только параметры методов, поэтому пришлось добавить StaticFeatureAccess и вытягивать ImplicitVariable оттуда. Также добавил исключение для переменных, относящихся к ForStatement, стандарт допускает там односимвольные переменные и т.д.

Я так понимаю, в проверке ExportVariableInObjectModuleCheck подписка на явные переменные тоже реализована не совсем корректно, т.к. достаточно подписаться на DeclareStatement?

2023-03-20 07:42 UTC, marmyshev approved these changes

2023-03-20 07:43 UTC, marmyshev commented
@VAGoncharov конфликт мержа, а так - можно заливать

2023-03-20 07:49 UTC, VAGoncharov commented
> @VAGoncharov конфликт мержа, а так - можно заливать

@marmyshev конфликт устранен.

2023-03-20 10:45 UTC, merged