#525 Реализована проверка "Проведение документа в прив. режиме"
1C-Company/v8-code-style pull request #1256
Opened 2023-03-05 03:57 UTC by VAGoncharov

## Что сделано

Реализована проверка "Проведение / отмена проведения в привилегированном режиме". Реализован unit-тест, добавлена пользовательная документация с описанием проверки. Добавлено описание в файл CHANGELOG.md.

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #525 #420

@1C-Company @marmyshev прошу сделать аудит

2023-03-10 04:16 UTC, VAGoncharov commented
@1C-Company @marmyshev прошу сделать аудит

2023-03-13 06:18 UTC, marmyshev requested changes

2023-03-13 06:18 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DocumentPostInPrivilegedModeCheck.java
> +        if (monitor.isCanceled() || document.getPosting().getName().equals(Posting.DENY.getName()))
тут лучше `document.getPosting() == Posting.DENY`

2023-03-13 06:18 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DocumentPostInPrivilegedModeCheck.java
> +        if (monitor.isCanceled() || document.getPosting().getName().equals(Posting.DENY.getName()))
Тут стоит добавить общую проверку что у документа есть регистры для проведения - только в этом случае может быть проведение - `com._1c.g5.v8.dt.metadata.mdclass.Document.getRegisterRecords().isEmpty()` - фичу не забудь добавить в список `.features(...` чтобы реагировала на добавление регистра

2023-03-13 08:38 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/DocumentPostInPrivilegedModeCheck.java
> +        if (monitor.isCanceled() || document.getPosting().getName().equals(Posting.DENY.getName()))
Готово. Так же доработан юнит-тест под этот случай.

2023-03-13 08:45 UTC, marmyshev approved these changes

2023-03-14 10:28 UTC, merged