Feature/596 form item visible settings by roles
1C-Company/v8-code-style pull request #1257
Opened 2023-03-10 03:38 UTC by VAGoncharov

## Что сделано

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #596 #221#220 #219

2023-03-13 06:57 UTC, marmyshev requested changes
В общем, всё ок. Пару мелочей

2023-03-13 06:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemVisibleSettingsByRolesCheck.java
> +                eContainer);
Нужно указывать проблемную фичу и проблемный объект. В данном случае - это галка которую снял разработчик `ADJUSTABLE_BOOLEAN__COMMON` (а целевой объект adjBoolean можно не указывать в качестве сокращения) - тогда ошибка будет отображаться ровно на проблеме.

2023-03-13 06:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +FormItemVisibleSettingsByRoles_Property_name_visible=visible
Для локализации это не очень хорошо - выносить несколько ключевых слов отдельно по одному слову. В разных языках могут быть разные падежи, словоформы, порядок слов и т.д.
Если так оставлять - то в `Use role-based setting "{0}" for form item "{1}"` нужно  хотя бы взять в кавычки как нечто что не относится к текущему предложению.

2023-03-13 07:52 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/messages.properties
> +FormItemVisibleSettingsByRoles_Property_name_visible=visible
Поправил, теперь свойства прописаны без склонения - "Visible", "Edit", "Use". В диагностическом сообщении свойство и склонение прописаны в кавычках.

2023-03-13 12:01 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemVisibleSettingsByRolesCheck.java
> +                eContainer);
Фича добавлена.

2023-03-20 21:13 UTC, marmyshev requested changes

2023-03-20 21:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemVisibleSettingsByRolesCheck.java
> +                eContainer,
Фичу указал, а объект поменять забыл :) у контейнера ведь нет такой фичи. Там где-то должны сыпаться исключения в лог... (емнип)

2023-04-16 19:27 UTC, merged