#398 Использован оператор "Перейти"
1C-Company/v8-code-style pull request #1262
Opened 2023-03-12 07:47 UTC by VAGoncharov

## Что сделано

- Реализована проверка на использование оператора "Перейти" в коде.

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #398

2023-03-13 06:09 UTC, marmyshev requested changes

2023-03-13 06:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseGotoOperatorCheck.java
> +            .checkedObjectType(BLOCK);
А почему нельзя тут указать сразу GotoStatement и LabeledStatement? тогда необходимость в проходе циклом по модели отпадет - т.к. этот проход всё равно делает общий механизм валидатор...

2023-03-13 06:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +BeginTransactionCheck_Begin_transaction_is_incorrect = Begin transaction is incorrect
Есть проблемка с форматированием (или кто-то вручную вставлял ключи, или результат мержа), мне кажется, лучше ее отдельно поправить - т.к. будет влиять на все реквесты.

2023-03-13 06:15 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseGotoOperatorCheck.java
> +            .checkedObjectType(BLOCK);
Я пробовал изначально указать GotoStatement и LabeledStatement. LS ловит нормально, но вот на GTS валидатор реагировать отказывался напрочь. В причинах такого поведения пока что разобраться не удалось.

2023-03-13 12:02 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +BeginTransactionCheck_Begin_transaction_is_incorrect = Begin transaction is incorrect
Готово.

2023-03-26 15:46 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseGotoOperatorCheck.java
> +            .checkedObjectType(BLOCK);
@marmyshev Код проверки переделал на правильный (изначально делал так), но столкнулся с проблемой, что валидатор не отлавливает GotoStatement, только UblabeledStatement. Причина не понятна. Пробовал из интереса подписаться на UnlabeledStatement, Statement - результата так же никакого. В чем может быть проблема?

Отлавливать GoTo получается только, обойдя Block через allStatement().

2023-04-17 22:13 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UseGotoOperatorCheck.java
> +            .checkedObjectType(BLOCK);
В ЕДТ ошибка - скоро пофиксят.

2023-04-17 22:14 UTC, marmyshev approved these changes

2023-05-22 20:45 UTC, merged