#1119 Реализована проверка "Unknown-form-parameter-access"
1C-Company/v8-code-style pull request #1263
Opened 2023-03-12 15:24 UTC by VAGoncharov

## Что сделано

- Реализована проверка "Unknown-form-parameter-access".

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1119

2023-03-13 12:12 UTC, marmyshev requested changes

2023-03-13 12:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UnknownFormParameterAccessCheck.java
> +        EObject moduleOwner = module.getOwner();
Так делать не очень корректно (включая алгоритм ниже по сбору всех параметров в форме).

Лучше - инжектить сервис DynamicFeatureAccessComputer в конструктор. Потом вызвать метод 

`com._1c.g5.v8.dt.bsl.resource.DynamicFeatureAccessComputer.resolveObject(FeatureAccess, Environments)` - если коллекция пустая или сразу добавить такой метод, легко проверяющий что фичи пусты:

   ```java
 private static boolean isEmptySource(List<FeatureEntry> features)
    {
        if (features.isEmpty())
            return true;

        return features.stream().allMatch(e -> {
            if (e.getFeature() instanceof ContainingSourceDerivedProperty)
            {
                return e.getFeature().eGet(CONTAINING_SOURCE_DERIVED_PROPERTY__CONTAINING_SOURCE, false) == null;
            }
            else if (e.getFeature() instanceof DerivedProperty)
            {
                return e.getFeature().eGet(DERIVED_PROPERTY__SOURCE, false) == null;
            }
            return false;
        });
    }
```

Такой код можно использовать не только в модуле формы - но и в общем модуле куда, например, форма может передаваться в виде параметра (я не предлагаю щас такое доделывать, хотя можно, но код будет подготовлен):

```bsl
Форма.Параметры.МойПараметр = ...;
```

2023-03-13 12:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/plugin.xml
> +            class="com.e1c.v8codestyle.bsl.check.UnknownFormParameterAccessCheck">
Если будешь переделывать на инжектинг - тут нужно указать фабрику `com.e1c.v8codestyle.internal.bsl.ExecutableExtensionFactory:`

2023-03-14 10:03 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/UnknownFormParameterAccessCheck.java
> +        EObject moduleOwner = module.getOwner();
@marmyshev Переделал. Пример увидел в проверке SelfReferenceCheck, проверку скопипастил оттуда. У метода есть комментарий:
// TODO replace this method with BslUtil after 2022.2+
В BslUtil аналогичного не нашел (возможно, плохо искал). Как появится там, можно будет поставить отдельный ишуз на переделку двух проверок.

2023-03-20 08:01 UTC, marmyshev requested changes
За исключеним мелочей - всё ок!

Сразу предлагаю: заведи задачу на квик-фикс по этой проверке - создание параметра формы по коду! Если сможешь сам сделать его - тоже будет классно! (взять имя параметра из кода и возможный тип определить - по ним добавить параметр). Это UI квикфикс - т.е. должен быть интерактивный в редакторе формы (если там всё доделано с открытием редакторов?). Располагать нужно в `com.e1c.v8codestyle.bsl.ui` 

Считаю, что будет очень полезно выпустить эту проверку сразу с квикфиксом!

2023-03-20 08:25 UTC, VAGoncharov commented
Поставил ишуз по квикфиксу для проверки - #1301

2023-03-20 21:02 UTC, merged