#1117 Доработана проверка SelfReferenceCheck
1C-Company/v8-code-style pull request #1271
Opened 2023-03-14 19:10 UTC by VAGoncharov

## Что сделано

- Доработана проверка SelfReferenceCheck: добавлена опция, позволяющая пропускать проверку для модулей объектов, наборов записей, менеджеров значений.
- Типы проверяемых модулей ограничены. Проверяются только общие модуля, модули объектов, наборов записей, менеджеров значений, модули форм.
- Доработан unit-тест
- Поправлена пользовательская документация

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1171 

@1C-Company @marmyshev прошу сделать аудит

2023-03-20 08:32 UTC, marmyshev requested changes

2023-03-20 08:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +        }
Эта операция сильно дороже, чем та что идет дальше по коду. Предлагаю спустить ниже.

2023-03-20 08:37 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
@marmyshev Если я правильно помню, "ЭтотОбъект" мы можем использовать только в приведенных типах модулей: ОбщийМодуль, МодульОбъекта, МодульНабораЗаписей, МодульФормы и МодульЗначения (константы, например). В остальных не можем - там ни edt, ни конфигуратор не даст написать ЭтотОбъект и при проверке ругнется. Поэтому проверка тут и сужается.

2023-03-20 09:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
Да, ты прав, не все типы модулей нужно проверять. Но тогда, например, забыт модуль команды (там точно можно). 

Предлагаю, сделать исследование (вручную) по типам модулей где явно запрещено использовать обращение "ЭтотОбъект" - и здесь в проверке использовать `ModuleTypeFilter.except()` с явным указанием исключаемых модулей. Это нужно чтобы исключить только те что явно не могут иметь такого обращения, и не забыть какие-то другие.

2023-03-20 10:08 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
@marmyshev Ты прав, пропустил в синтаксис-помощнике модуль команд. Добавил. Остальное сверил, вроде ничего не забыл.
Я выше неправильно выразился. В перечисленных модулях написание "ЭтотОбъект" не имеет смысла и там это будет просто локальная переменная. Данный кусок кода относится скорее не к ишузу #1171 , а к оптимизации этой проверки. Если хочешь, могу создать отдельный ишуз и быстро туда влить оптимизацию.

По поводу except - у нас 15 типов модулей, а указано к проверке 6. Указывать onlyTypes мне показалось оптимальней. Если все равно считаешь, что лучше переделать на except - переделаю.

2023-03-20 10:08 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +        }
Готово.

2023-03-20 20:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
> Если все равно считаешь, что лучше переделать на except - переделаю.

Да, считаю правильней. Я еще раз прошу провести проверку так: "Я, Вадим Гончаров, лично проверил в таких-то типах модулей: .... (список) и ЭтотОбъект не поддерживается на уровне контекста, поэтому проверять не надо" :) 

Знаешь, новые типы модулей периодически добавляются. Но если контекст не поддерживает обращение к ЭтотОбъект - то значит проверка сработает в холостую и ничего не найдет. Хуже будет если проверка не будет находить ошибки.

2023-03-20 20:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +        }
Вроде ничего по сути не поменялось. 

`Module module = EcoreUtil2.getContainerOfType(dynamicFeatureAccess, Module.class);` - это вот самое затратное - т.е. ты от каждого свойства в модуле сначала проходишь вверх по всей иерархии модуля, а потом только проверяешь, вообще оно тебе надо было это свойство?! На каждом свойстве в коде - миллоин-миллиард бесполезных циклов вверх по структуре модуля.

2023-03-20 20:56 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
<img width="473" alt="image" src="https://user-images.githubusercontent.com/4069973/226463941-bb3aac15-8478-4e04-816b-c95586bd6638.png">
Скрин из АПК

2023-03-21 04:55 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +                ModuleType.VALUE_MANAGER_MODULE, ModuleType.RECORDSET_MODULE, ModuleType.FORM_MODULE))
Ок. Переделал на exclude.

2023-03-21 05:12 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/SelfReferenceCheck.java
> +        }
Теперь понятней. Сначала проверяем, что свойство - "ЭтотОбъект", и только потом затратный цикл.

2023-04-17 03:19 UTC, merged