#498 Реализована проверка OptionalParameterBeforeRequired
1C-Company/v8-code-style pull request #1273
Opened 2023-03-15 12:00 UTC by VAGoncharov

## Что сделано

- Реализована проверка "Необязательный параметр расположен перед обязательным"

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [x] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #498

@1C-Company @marmyshev прошу сделать аудит

2023-03-15 20:44 UTC, marmyshev commented
@VAGoncharov на всякий случай глянь в `com.e1c.v8codestyle.bsl.check.MethodTooManyPramsCheck` чтобы не было пересечений по функциональности (там что-то на эту же тему было)

2023-03-16 01:21 UTC, VAGoncharov commented
> @VAGoncharov на всякий случай глянь в `com.e1c.v8codestyle.bsl.check.MethodTooManyPramsCheck` чтобы не было пересечений по функциональности (там что-то на эту же тему было)

Посмотрел. И там и тут проверяются параметры методов, поэтому есть пересечение по подписке и способу обхода коллекции параметров. Но семантически проверки разные, как и их коды. Предлагаешь объединить в одну?

2023-03-20 08:49 UTC, marmyshev requested changes

2023-03-20 08:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/OptionalParameterBeforeRequiredCheck.java
> +        Integer indexOfRequiredParam = null;
Здесь вместо объекта - правильнее использовать простой тип с начальным значение `-1`, тогда не будет boxing-unboxing, далее по коду - проверка на то что больше нуля...

2023-03-20 08:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/OptionalParameterBeforeRequiredCheck.java
> +    private static final String CHECK_ID = "bsl-optional-parameter-before-required"; //$NON-NLS-1$
Вот как-то везде напрашивается пропущенное (но подразумеваемое) слово "метод". Но! т.к.  параметры бывают не только у методов, но и у вызовов (Invocation) - т.о. создается неоднозначность контекста для слова "параметр".

Предлагаю `method-optional-parameter-before-required` - и соответственно везде в заголовках и описаниях добавить слово... имя класса.

2023-03-20 09:15 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/OptionalParameterBeforeRequiredCheck.java
> +        Integer indexOfRequiredParam = null;
Готово.

2023-04-16 19:52 UTC, marmyshev approved these changes

2023-04-17 02:32 UTC, merged