#546 - "РольДоступна" и "Пользователи.РолиДоступны" ссылаются на несуществующие роли конфигурации
1C-Company/v8-code-style pull request #1274
Opened 2023-03-19 11:09 UTC by VAGoncharov

## Что сделано

- Проверка, что функции "РольДоступна" и "Пользователи.РолиДоступны" ссылаются на несуществующие роли конфигурации.

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #546 

@1C-Company @marmyshev прошу сделать аудит

2023-03-20 09:18 UTC, marmyshev requested changes
Предлагаю переделку кода поиска, см. ниже. И придётся раздели на 2 реквеста - в плагин по БСП...

2023-03-20 09:18 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/InvocationRoleCheckAccessExistRoleCheck.java
> +        for (Role role : configuration.getRoles())
Так делать очень-очень дорого. Предлагаю использовать `IScopeProvider` - сервис, можно инжектить:

```java

private final IScopeProvider scopeProvider;

QualifiedName roleName = QualifiedName.create(literal.lines(true).get(0));
IScope typeScope = scopeProvider.getScope(inv, MdClassPackage.Literals.CONFIGURATION__ROLES);
IEObjectDescription element = typeScope.getSingleElement(roleName);
if (element == null)
{
     resultAcceptor.addIssue(message, literal, STRING_LITERAL__LINES);
 }
```

Там есть уже готовый индекс, который может переиспользоваться по всем проверкам по всем модулям. В текущей проверке (без части про БСП) - будет всегда одна роль проверяться.

2023-03-20 09:33 UTC, VAGoncharov commented
@marmyshev Создал ишуз https://github.com/1C-Company/ssl-support/issues/103. Из текущей проверки вычищу все, что связано с БСП.

2023-03-21 14:15 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/InvocationRoleCheckAccessExistRoleCheck.java
> +        for (Role role : configuration.getRoles())
Переделал. Указанный пример работать не будет, в QualifiedName нужно подсовывать "Role."+имя роля из параметра функции.

Как я понимаю, можно сделать более корректно, сгенерировав строку для QualifiedName через ITopObjectFqnGenerator:

```java
String fqn = topObjectFqnGenerator.generateStandaloneObjectFqn(MdClassPackage.Literals.ROLE, roleName);
return scope.getSingleElement(qualifiedNameConverter.toQualifiedName(fqn));
```

2023-04-01 14:11 UTC, VAGoncharov commented
@marmyshev Проверки, относящиеся к БСП, вынесены в отдельную ветку для ssl-support https://github.com/1C-Company/ssl-support/pull/105

2023-04-16 20:01 UTC, marmyshev requested changes
По сути замечаний нет. Поправить одну мелочь, и можно заливать.

2023-04-16 20:01 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/IsInRoleMethodRoleExistCheckTest.java
> +    }
Вместо копипаста - нужно переопределись метод getModuleFileName() - там вернуть имя модуля COMMON_MODULE_FILE_NAME

2023-04-17 16:10 UTC, VAGoncharov commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/IsInRoleMethodRoleExistCheckTest.java
> +    }
Готово

2023-04-17 22:10 UTC, marmyshev approved these changes

2023-04-17 22:11 UTC, merged