#1275 Пользовательская документация для проверки ql-temp-table-index
1C-Company/v8-code-style pull request #1302
Opened 2023-03-20 14:54 UTC by VAGoncharov

## Что сделано

- Доработана пользовательская документация для проверки ql-temp-table-index.

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1275 

@1C-Company @marmyshev прошу сделать аудит

2023-03-20 20:41 UTC, marmyshev requested changes

2023-03-20 20:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-temp-table-index.md
>  ## Правильно
Для разработчиков эта тема оказалась холиварной. Поэтому нужно добавить как можно больше подробных примеров о том как правильно или неправильно.

Можно за основу (как идею для примера) взять файлы тестов. и посмотреть в код проверки если там есть нюансы

https://github.com/1C-Company/v8-code-style/blob/master/tests/com.e1c.v8codestyle.ql.itests/resources/temp-table-has-index.ql

https://github.com/1C-Company/v8-code-style/blob/master/tests/com.e1c.v8codestyle.ql.itests/resources/temp-table-has-no-index-top.ql

https://github.com/1C-Company/v8-code-style/blob/master/tests/com.e1c.v8codestyle.ql.itests/resources/temp-table-has-no-index.ql

2023-03-21 18:59 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-temp-table-index.md
>  ## Правильно
Посмотрел примеры и ничего из них не понял. Просто берутся какие-то абстрактные ВТ и индексируются/не индексируются.
Если делать примеры, то надо делать конкретный сквозной пример. Вот у нас есть таблица, заведомо большая. В ней такие-то поля. Далее что-то делаем с этой ВТ, отбираем данные в секции ГДЕ или соединяемся с другой таблицей. В таких-то случая надо делать индекс вот такой и соединяться вот так (потому что потому), в таких-то - по другому, а в этом случае индекс излишен.

На ИТС все эти примеры есть с разжевыванием, есть книжки. Только это такой объем, что в краткое описание документации явно не влезет. И даже там подчеркивается, что каждый случай индивидуален и надо думать головой, а не бездумно клепать индексы во все подряд.

Я все это к тому, что несколько ссылок на проф. ресурсы еще могут как-то просветить человека, а примеры в маленькой доке только создадут иллюзию понимания. Считаю, что лучше повставлять доп. ссылки.
К тому же, разработчики мелких баз все равно оптимизациями не занимаются, а разработчики крупных баз знают основы и без EDT.

2023-03-24 20:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-temp-table-index.md
>  ## Правильно
Попробую с другой стороны :)

Из текущего описания которое ты скопировал из стандарта - совсем не понятно: как такие как-бы индивидуальные случаи проверка проверяет каким-то непонятным общим правилом (алгоритмом).

Да, стандарт может описывать широкую "идею" которую на практике можно воплотить несколькими проверками с каким-то точным алгоритмом.  А может быть такое - что никакого алгоритма придумать нельзя по стандарту - тогда он остается без проверок.

У проверки есть четкие алгоритм того что она ищет и что считается не правильным. Из текущего описания это не будет понятно. Я предлагаю это добавить.

Например: 
- если указано ограничение числа записей `ВЫБРАТЬ ПЕРВЫЕ 999 ...` - то мы считаем что таблица маленькая, поэтому индексировать не нужно.
- Индексы нужны только тогда когда мы помещаем во временную таблицу

Текущая проверка, возможно не покрывает весь стандарт - и это нормально))

2023-03-26 14:32 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-temp-table-index.md
>  ## Правильно
Добавил первые примеры в русскую документацию, если в таком формате устроит - добавлю для английской.

2023-03-26 14:34 UTC, VAGoncharov commented on bundles/com.e1c.v8codestyle.ql/markdown/ru/ql-temp-table-index.md
>  ## Правильно
В проверке вызывает вопросы параметр MAX_TOP = 1000;. 1000 записей это ни о чем, СУБД будет проще сделать скан таблицы и на 2000, да и на 5000 записей. Предлагают отдельным ишузом сделать MAX_TOP параметризуемым, значение по-умолчанию - 10 000 или оставить как есть.

2023-04-16 18:56 UTC, merged