G5V8DT-24189 При добавлении обработчика события или команды автоматически размещать его в соответствующей области
1C-Company/v8-code-style pull request #1369
Opened 2023-10-16 09:57 UTC by Kudesunik

https://github.com/1C-Company/v8-code-style/issues/1040

2023-10-17 07:48 UTC, MaksimDzyuba requested changes

2023-10-17 07:48 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.bsl.model.util;version="4.7.0",
не указана верхняя граница

2023-10-17 07:48 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/ModuleRegionInformation.java
> +    public static ModuleRegionInformation create(IDocument document, INode node, INode nodeAfter)
публичные статичные методы, должны находиться до конструктора

2023-10-18 07:20 UTC, Kudesunik commented on bundles/com.e1c.v8codestyle.bsl.ui/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.bsl.model.util;version="4.7.0",
Исправлено

2023-10-18 07:21 UTC, Kudesunik commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/ModuleRegionInformation.java
> +    public static ModuleRegionInformation create(IDocument document, INode node, INode nodeAfter)
Перенесено

2023-10-30 21:32 UTC, MaksimDzyuba requested changes

2023-10-30 21:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleOffsets.java
> +     * Start offset of module region
Gets

2023-10-30 21:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleOffsets.java
> +    public int getEndOffset()
Gets

2023-10-30 21:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleOffsets.java
> +    public int getBeforeEndOffset()
gets

2023-10-30 21:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleRegionInformation.java
> +     * @param insertPosition
java-doc  и ниже тоже

2023-10-30 21:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/services/BslModuleRegionsService.java
> +                if (eventOwner instanceof NamedElement && eventOwner.eClass().getName().equals("Table")) //$NON-NLS-1$
а чего тут такая странная проверка, если это про com._1c.g5.v8.dt.form.model.Table, то, достаточно написать так 
eventOwner.eClass() = FormPackage.Literals.TABLE

2023-10-30 21:34 UTC, MaksimDzyuba commented
Я переподвесил ветку к edt-2023-3, так как по мастеру собираем тут мы именно релиз

2023-11-14 09:45 UTC, merged