Падает тест RefLinkPartCheckTest #1376
1C-Company/v8-code-style pull request #1380
Opened 2023-11-24 09:10 UTC by ukolabrother

## Что сделано

Исправлен ресурс для теста. В ресурсе неправильно описаны ссылки

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #1376

2023-11-24 10:02 UTC, vadimeg commented
Еще надо @Ignore убрать у теста

2023-11-24 10:04 UTC, vadimeg requested changes
Нужно открыть тест

2023-11-24 10:10 UTC, ukolabrother commented
> Нужно открыть тест

@Ingore у теста нет

2023-11-24 10:13 UTC, vadimeg commented
> > Нужно открыть тест
> 
> @Ingore у теста нет

А, это же мастер. При переносе в edt-2023-3 надо будет убрать не забыть, там есть

2023-11-24 10:14 UTC, vadimeg approved these changes

2023-12-12 07:17 UTC, merged

2023-12-12 18:57 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/resources/doc-comment-ref-link.bsl
> +//  LinkToMethod - See NonComplaint
Вопрос: а почему изменено тут?

Вроде бы ссылка на метод правильная. Добавили поддержку скобок в конце метода в модель док-комментов?

2023-12-12 19:16 UTC, ukolabrother commented on tests/com.e1c.v8codestyle.bsl.itests/resources/doc-comment-ref-link.bsl
> +//  LinkToMethod - See NonComplaint
Ссылка на метод не должна содержать скобки

2023-12-12 19:29 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/resources/doc-comment-ref-link.bsl
> +//  LinkToMethod - See NonComplaint
Так если содержит скобки - это как раз ошибка которая должна была детектироваться проверкой.

Ты убрал скобки, теперь ссылка правильна, а название ссылки "NonCommliant" говорит что должна быть ошибка.

То есть либо нужно было заменить на правильную ссылку (See Compliant), либо пофиксить проверку и тест чтобы находилась эта проблема NonCompliant()

2024-01-22 10:51 UTC, ukolabrother commented on tests/com.e1c.v8codestyle.bsl.itests/resources/doc-comment-ref-link.bsl
> +//  LinkToMethod - See NonComplaint
Я ошибся, скобки можно ставить теперь. 
Парсинг ссылок в EDT был изменен, так как была зарегистрирована ошибка. Если после ссылки поставить спецсимвол, например "," или ";", то ссылка "ломалась". Ошибка была исправлена. Но скобки тоже являются спецсимволом и теперь игнорируются при парсинге ссылки. Поэтому тест перестал показывать на 7 строку. Мое исправление ресурса добавило ссылку на несуществующий метод и проверка диагностирует эту ошибку.