Добавить валидацию некорректных ссылок в комментариях для метода
1C-Company/v8-code-style pull request #1389
Opened 2023-12-12 07:27 UTC by ukolabrother

## Что сделано

Реализована валидация несуществующих ссылок в комментариях в теле метода (инлайн документирующие и свободные)

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

LT 1011
Closes #

2023-12-12 18:09 UTC, marmyshev commented
А в чем смысл этих изменений?

Почему убрана подписка на объект ссылок в модели док комментов?

ПО правильному- нужно делать хаб который будет проверять инлайн-комментарии как модель, а там есть ли ссылки или типы, или ещё что-то- уже задача отдельных проверок.

2023-12-12 18:10 UTC, marmyshev requested changes
Вопросы по самой идее.

2023-12-12 19:18 UTC, ukolabrother commented
О каком хабе идет речь? Есть пример подобного подхода?
Если ссылка размещена в свободном комментарии или в инлайн-документирующем, то она не будет отправлена на проверку в предыдущей версии валидатора. Только документирующий комментарий над методом

2023-12-12 19:40 UTC, marmyshev commented
Посмотри реализацию doc-comment-hub - в EDT.
Это отдельная проверка которая включается/выключается.  Для инлайн и
произвольных комментариев - нужно делать такие же хабы.
Это также возможность для пользователей отключить валидацию в тех типах
подчиненных моделей которые им не нужны.

Имхо, нужно делать 2 дополнительных хаба (или один дополнительный но с 2
параметрами) которые загружают модель (парсят) и отправляют на валидацию:
doc-comment-inline-hub - только для типизирующих комментариев которые в
строке с переменными - это явно влияющие комментарии на типизацию (коммент
добавляется в виртуальную секцию Return)
doc-comment-arbitrary-hub - для всех других комментариев в модуле, которые
парсятся и загружаются в модель док-комментов "как есть" - то есть
фактически будут в docComment.getDescription()

По правильному, эти хабы нужно создавать в ЕДТ, но можно и в Код-стайле.

Тогда все остальные проверки по модели док-комментов - будут автоматически
запускаться на этих моделях.

2024-06-26 10:51 UTC, closed without merging

2024-06-26 10:52 UTC, ukolabrother commented
В EDT реализовано добавление комментариев из тела модуля в проверку. Тест проверяющий комментарии внутри метода тут https://github.com/1C-Company/v8-code-style/pull/1407