#1 перенос сборки и проверок по метаданным
1C-Company/v8-code-style pull request #2
Opened 2021-03-10 14:27 UTC by marmyshev

2021-03-10 15:26 UTC, EightM commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +    public static final String NAME_SUFFIX_PARAMETER_NAME = "nameSuffix"; //$NON-NLS-1$
Повторяющиеся публичные константы, которые встречаются в разных классах

2021-03-10 15:28 UTC, EightM commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        if (excludeNamePattern != null && name.matches(excludeNamePattern))
Вызов matches на строке, приведет к постоянной компиляции регулярного выражения, что при большом количестве вызовов метода check, может вызвать заметную деградацию производительности

2021-03-10 15:31 UTC, EightM commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleType.java
> +    public static final Map<EStructuralFeature, Boolean> TYPE_SERVER = Map.of(
Зачем public?

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> + * @author Dmitriy Marmyshev
JavaDoc

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +    public static final String CHECK_ID = "common-module-name-client"; //$NON-NLS-1$
Константы приватные, публикация ID в качестве API - пока лишена смысла, соответственно нет необходимости расширять API

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +public class CommonModuleNameClient
Класс финальный, наследоваться от конечной проверки смысла нет, а вот проблемы вызвать может при неаккуратном наследовании

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        CommonModule commonModule = (CommonModule)object;
У нас для этого есть спец. компонент TopObjectFilterExtension, объединяет декларацию параметра и собственно логику фильтрации. 
Поскольку он и используется, этот код - избыточный

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +                MessageFormat.format(Messages.CommonModuleNameClient_message, String.join(", ", nameSuffixs)); //$NON-NLS-1$
В принципе, есть практика декларации наличия параметров в имени локализованного поля, но не настаиваю - все равно никто соблюдать не будет, а человекочитабельность падает

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java
> + *
JavaDoc

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java
> +public class CommonModuleNameClientServer
final - аналогично CommonModuleNameClient

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java
> +    public static final String CHECK_ID = "common-module-name-client-server"; //$NON-NLS-1$
private для всех констант - аналогично CommonModuleNameClient

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java
> +                EXCLUDE_NAME_PATTERN_PARAMETER_NAME,
Данный компонент делался конфигурируемым с прицелом на то, что понадобится различная пользовательская семантика для параметра (на уровне UI настроек). Если это не нужно (а есть подозрение, что это так, раз идет копипаста по факту) - можем упростить.

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClientServer.java
> +        String nameSuffix = parameters.getString(NAME_SUFFIX_PARAMETER_NAME);
Фильтрация по суффиксу - уже во второй проверке (глядя дальше - еще больше). Возможно стоит вынести в компонент, раз так часто используется?

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
> + * @author Dmitriy Marmyshev
JavaDoc

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
> +public class CommonModuleNameGlobal
final

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
> +        String nameSuffix = parameters.getString(NAME_SUFFIX_PARAMETER_NAME);
Снова контроль суффикса

2021-03-10 15:34 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
> +        List<String> nameSuffixs = List.of(nameSuffix.replace(" ", "").split(",")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
Сам параметр будет доступным в общем контексте, даже если отсечение выше будет перенесено в компонент, так что проблем нет сделать и стандартную фильтрацию, и саму логику проверки.

2021-03-10 15:50 UTC, EightM commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages_ru.properties
> +MdObjectNameLength_Maximum_name_length_description = Максимальная длинна имени
Опечатка "длинна"

2021-03-10 15:52 UTC, otymko commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        builder.title(Messages.CommonModuleNameClient_title)
А использование builder внутри проверки это навязанный дизайн? Почему не пойти через аннотации к классу проверки? Или это невозможно реализовать?

2021-03-10 16:01 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        builder.title(Messages.CommonModuleNameClient_title)
Там крайне высокий уровень иерархичности процесса конфигурирования, с четкими контекстами, в которых допустимы те или иные конструкции. На уровне аннотаций это будет: а) выглядеть просто некрасиво и нечитабельно
б) без всяческого контроля контекста при работе в редакторе Java по допустимости той или иной конструкции в том или ином контексте в) дороже в реализации

В результате выбрана именно эта схема для стандартной реализации ,которая ни в коем случае не является базовым API, это решение верхнего уровня для разработки простых проверок.

Есть ли желание кое-что перевести на аннотации? Да, есть, возможно мы выделим несколько более простых базовых классов для разработки еще более простых проверок (или типичных), и там как раз аннотации будут предпочтительнее.

2021-03-10 16:05 UTC, EightM commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java
> +        if (mdObject instanceof Configuration)
Почему исключается имя конфигурации? На неё ведь распространяются те же ограничения, о чем и говорит конфигуратор, если попытаться присвоить имя конфигурации длиннее 80 символов

2021-03-10 16:17 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/CorePlugin.java
> +    public synchronized Injector getInjector()
Вот так лучше не делать, возможны локи на загрузке бандлов (не фатальные, но тормозящие процесс). 
Сейчас в EDT все критические точки переведены на DCL, примеры везде, например в V8CorePlugin

2021-03-10 16:17 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameClientServerTest.java
> +        Marker marker = getFirstMarker(CommonModuleNameClientServer.CHECK_ID, id, dtProject);
Для тестов не стоит оно того. 
Данный тест: 
- Прекрасно отвалится в случае переименования идентификатора в классе проверки
- По сути своей не является проверкой case-а "проверка X должна существовать в тестируемой системе", поэтому не имеет смысла явно использовать ее идентификатор.

Поэтому в тестах волне разумно использовать символическую копию ее идентификатора.
Также стоит рассмотреть альтернативный вариант написание тестов (сейчас такой применяется во внутренних тестах), с явной инстанциацией проверки и получения ее идентификатора прямо из этой же инстанции. Возможно так будет проще

2021-03-10 16:17 UTC, otymko commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java
> +        if (name != null && name.length() > max && max > 0)
А `mdObject.getName()` может быть null?

2021-03-10 16:36 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java
> +        if (name != null && name.length() > max && max > 0)
При работе стандартных механизмов EDT - нет (импорт не пропустит, редактирование и рефакторинг - тоже), но в любом расширении сломать - не проблема.
Достаточно провести прямое изменение модели через БМ. 
Так что ответ - да, может.

2021-03-10 17:09 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameGlobal.java
> +        if (commonModule.isGlobal() && commonModule.getReturnValuesReuse().equals(ReturnValuesReuse.DONT_USE)
Можно и ==
Тут присутствует профессиональная деформация при работе с EMF и его автогенеренными классами. Когда немного понимаешь, что там внутри - начинаешь автоматически ждать подлянку. Но на самом деле - да, причем не только реальные enum-ы, но и feature-ы и прочие моменты декларативной модели можно по ==

2021-03-10 17:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java
> +        if (mdObject instanceof Configuration)
Длинна имени конфигурации не виляет на длинну пути файла в выгрузке - а 80 символов - это именно из-за ограничения длинны пути в Windows было сделано. Надо уточнить в стандарте и в Конфигураторе - влияет или нет.

2021-03-10 19:12 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        if (excludeNamePattern != null && name.matches(excludeNamePattern))
Это уйдет в компонент фильтрации по TopObjectFilter... (забыл почистить) но там код тот же. 
Да, не избежать этого - потому что мы не знаем в каком проекте будет следующий вызов.

@tretyakevich Но было бы неплохо чтобы можно было объявлять параметр типа `Pattern`  чтобы не выполнять постоянно компиляцию регэкса?

2021-03-10 20:04 UTC, artbear requested changes

2021-03-11 01:24 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +        if (excludeNamePattern != null && name.matches(excludeNamePattern))
> Это уйдет в компонент фильтрации по TopObjectFilter... (забыл почистить) но там код тот же.
> Да, не избежать этого - потому что мы не знаем в каком проекте будет следующий вызов.
> 
> @tretyakevich Но было бы неплохо чтобы можно было объявлять параметр типа `Pattern` чтобы не выполнять постоянно компиляцию регэкса?

Я запишу в пожелания. Здесь одним новым типом параметра не обойдешься, нужно будет хранить состояние в памяти для всех подобных параметров. Сейчас это принципиально не делалось, потому что накладные расходы на создание контекста для проверки низкие, поэтому выгодно создавать их из прототипа для каждой новой сессии проверки.

2021-03-11 05:58 UTC, sergeysuvorov commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/CommonModuleNameClientServerTest.java
> +@SuppressWarnings("nls")
Лучше в настройках проекта, содержащего тест, указать, чтобы эклипс не выдавал предупреждение при отсутствии маркера non-nls.

2021-03-12 15:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +                MessageFormat.format(Messages.CommonModuleNameClient_message, String.join(", ", nameSuffixs)); //$NON-NLS-1$
Ну тут либо надо полный текст фразы в snake_case и тогда да, надо указывать параметр, либо символическое сокращение  - и параметр уже бесзсмысленно. В таких однотипных классах - имхо лучше второй вариант - проще будет локализацию отслеживать/править.

2021-03-12 15:59 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/CommonModuleNameClient.java
> +public class CommonModuleNameClient
Пока повременим с общим классом))
Но если будет много общего кода и общего поведения - надо будет делать.

2021-03-12 16:22 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdObjectNameLength.java
> +        if (mdObject instanceof Configuration)
Конфигуратор ругается.

2021-03-12 17:40 UTC, merged