Реализация пунктов 2 и 3 стандарта 488: Стандартные роли
1C-Company/v8-code-style pull request #31
Opened 2021-07-27 16:20 UTC by DoublesunRUS

Реализованы проверки по стандарту 488: https://its.1c.ru/db/v8std#content:488:hdoc
- проверки полных прав и администратора системы, указанных в пункте 2.
- проверки 12 стандартных ролей указанных в пункте 3.

Closes #20

2021-08-29 06:35 UTC, marmyshev commented
@DoublesunRUS ping! конфликты...

2021-09-05 09:49 UTC, marmyshev requested changes

2021-09-05 09:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/internal/right/CorePlugin.java
> +import com._1c.g5.v8.dt.md.ExternalDependenciesModule;
Нельзя так делать.

2021-09-05 09:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleNameChangeExtension.java
> +            if (bmObject instanceof RoleDescription && ((BmChangeEvent)bmEvent).isFqnChanged())
небезопасный каст к BmChangeEvent

2021-09-05 09:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleNameExtension.java
> +public class RoleNameExtension
Название слишком общее - по смыслу очень не подходит. "Расширение имени роли" - о чем говорит? нужно догадаться (или прочитать в джавадоке) что это исключение ролей по списку имен. Может так и назвать расширение?

2021-09-05 09:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleNameExtension.java
> +    public static final String ROLE_NAMES_LIST_PARAMETER_NAME = "roleNamesList"; //$NON-NLS-1$
Ни о чем не говорящее название параметра в рамках проверки - этот параметр ведь будет в общем списке всех параметров по проверке - что за список имен? исключения или включения? Предлагаю сохранить прежнее - т.к. его могли уже использовать в настройках - либо об этом надо явно писать в документации что параметр переименовывается.

2021-09-05 09:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/SaveUserDataRight.java
> +    public SaveUserDataRight(IV8ProjectManager v8ProjectManager, IBmModelManager bmModelManager)
джавадоки на конструктор (и далее аналогично)

2021-09-05 09:49 UTC, marmyshev commented on tests/com.e1c.v8codestyle.right.itests/workspace/StandartRoles/.settings/com.e1c.g5.v8.dt.formatter.bsl.prefs
> +whitespaceMethodParamsDelimited=true
кажется это тут не нужно в ролях

2021-09-05 09:55 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/internal/right/CorePlugin.java
> +import com._1c.g5.v8.dt.md.ExternalDependenciesModule;
А я то думаю, чего это вдруг какой-то импорт подтянулся, хотя я ничего не делал. :)

2021-09-05 12:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +        Role mdObject = RightsModelUtil.getOwner(description, model);
Это порча логики. Здесь должен быть объект пава, а не роль.

2021-09-06 08:30 UTC, tretyakevich approved these changes
В целом заметных замечаний нет.
Однако нужно будет внимательно следить за развитием всего этого. Сейчас есть достаточно большой объем однотипных проверок, которые отличаются только конфигурацией проверяемых прав. 
С т.з. производительности особых проблем быть не должно, но вот с т.з. управления кодом - уже может появится, особенно если что-то будет добавляться (много классов с однотипным кодом).

Поэтому пока рекомендаций по рефакторингу не будет, но если объем еще подрастет - надо будет смотреть, насколько это удобно, и не перейти ли к альтернативе (небольшое количество проверок со сложной логикой и разными маркерами)

2021-09-09 14:35 UTC, marmyshev requested changes

2021-09-09 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/ActiveUsersRight.java
> +    private static final String CHECK_ID = "active-users-right"; //$NON-NLS-1$
тут и далее - надо бы местами поменять 

"right-active-users"; - право: активные пользователи

см. ранее в проверках так же сделано

2021-09-09 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/RoleRightSetCheck.java
> +     * {@inheritDoc}
А зачем тут удалять описание? вышестоящего конструктора ведь нет...

2021-09-09 14:35 UTC, marmyshev commented on tests/com.e1c.v8codestyle.right.itests/src/com/e1c/v8codestyle/internal/right/itests/CheckRights.java
> +                    throw new ClassCastException(MessageFormat.format("Не удалось получить {0} по Fqn {1}",
Русские символы в коде - по соглашению запрещены. Аналогично ниже по коду...

2021-09-09 14:35 UTC, marmyshev commented on CHANGELOG.md
> +- Права на корень конфигурации есть только у стандартных ролей
их ведь 17?

2021-09-09 14:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.right/markdown/ru/active-users-right.md
> +# active-users-right
Было бы неплохо тут указать человеческое название (можно взять из title), аналогично для английских вариантов.

Я ленился делать это когда перенос делал т.к. там надо было всё снулая писать...

2021-09-09 20:59 UTC, merged

2021-09-17 07:38 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/ExcludeRoleByPatternExtension.java
> +        final CheckParameterDefinition parameterDefinition =
а зачем эти final, какой в них смысл?

2021-09-17 09:44 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.right/src/com/e1c/v8codestyle/right/check/ExcludeRoleByPatternExtension.java
> +        final CheckParameterDefinition parameterDefinition =
Затрудняюсь ответить на этот вопрос.
Я наверное откуда-то этот код взял.