Проверка на запросы в цикле
1C-Company/v8-code-style pull request #32
Opened 2021-07-28 14:07 UTC by DoublesunRUS

1. Ищутся все методы, в которых есть запросы
2. В цикле ищутся все методы, которые вызывают методы, в которых есть запросы
3. Обходятся все циклы. Для каждого оператора цикла проверяется, что он не является выполнением запроса или вызовом метода с запросом.

Closes #17

2021-08-09 14:54 UTC, marmyshev requested changes
Было бы еще неплохо проверить это на ERP 2 (как самая большая кодовая база) - чтобы понять сколько там ошибок и все ли они достоверные (т.е. нет ли каких-то особенностей в коде).

2021-08-09 14:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +            for (Statement statement : EcoreUtil2.eAllOfType(loopStatement, SimpleStatement.class))
Аналогичное предложение: может быть сделать искать все `FeatureAccess` где из них  `StaticFeatureAccess` которые являются вызовами методов из  списка `methodsWithQuery`? а так же `DynamicFeatureAccess` которые являются методами `BslUtil.getInvocation(dfa) != null` и совпадают по именам с `queryExecutionMethods` - потом их уже проверить что это действительно вызовы запроса (в типизированном коде) или если включен параметр (возможно будущий из моего предложения выше?) проверять нетипизированный код - тогда без разницы.

Далее по коду - не понятно зачем вешать на левый или правые части стейтмента - тогда можно было бы вешать сразу на `FeatureAccess` и на ее фичу `FEATURE_ACCESS__NAME` - будет подсвечиваться вызов метода в теле цикла в котором есть запрос.

Этот метод тогда переименовать и он может возвращать просто список `private Collection<FeatureAccess> getExecutionsOfQueryInLoop(...)` на который нужно повесить ошибки.

Кажется код станет проще и быстрее.

2021-08-09 14:54 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/QueryInLoop/.settings/Default.cset
> +  "settings": {}
предлагаю этот файл удалить чтобы не наводить в будущем каких-то особенностей при наличии пустых настроек.

2021-08-09 14:54 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/QueryInLoop/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.16
Версию нужно 8.3.19 - на более низких не будем тестировать. В проекте будем использовать одну единую версию для всех проектов тестов. и централизованно поднимать если нужно.

2021-08-09 14:54 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/QueryInLoopCheckTest.java
> +                    // Методы без ошибок, пропускаем
1. русские комментарии в коде запрещены
2. Лучше добавить в коммент тут что потом проверим что не осталось ошибок, но не настаиваю

2021-08-09 14:54 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/QueryInLoopCheckTest.java
> +                    throw new WrongParameterException(
кажется тут больше подходит `IllegalStateException` по смыслу

2021-08-09 14:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/query-in-loop.md
> +https://its.1c.ru/db/pubqlang#content:150:hdoc
1. по стандарту маркдауна - 1 строчка отсупа после заголовка
2. нужна ссылка на английский материал из https://1c-dn.com/library/methodology/ например или откуда-то еще если есть

2021-08-09 14:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/query-in-loop.md
> +https://its.1c.ru/db/pubqlang#content:150:hdoc
хотя вот нашел https://1c-dn.com/library/sample_queries_for_operations_with_hierarchical_catalogs/ - где прям ошибка будет))

2021-08-09 14:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/query-in-loop.md
> +https://its.1c.ru/db/pubqlang#content:150:hdoc
по стандарту маркдауна - 1 строка пустая после заголовка

2021-08-09 14:54 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/QueryInLoop/src/CommonModules/CommonModule/Module.bsl
> +EndFunction
Было бы неплохо добавить еще пример для нетипизированного кода (в этом методе есть типизированный вызов - поэтому входящий параметр типизируется расчетно).

Но не настаиваю.

2021-08-09 15:08 UTC, DoublesunRUS commented
> Было бы еще неплохо проверить это на ERP 2 (как самая большая кодовая база) - чтобы понять сколько там ошибок и все ли они достоверные (т.е. нет ли каких-то особенностей в коде).

@marmyshev 
Особенности в коде ЗУП есть. Например когда обходится порция объектов, то в тексте запроса есть "ВЫБРАТЬ ПЕРВЫЕ", и цикл бесконечный. Например "Пока Истина Цикл". Но в статье на ИТС я не нашел какого-то стандарта как делать исключения правильно.
То есть определять порционные запросы каким-то образом надо, но не хотелось бы делать много исключений.
Предлагаю сделать одно исключение опционально. Разрешить для циклов Пока Истина Цикл выполнять запрос вызывая код, но ругаться если в таком бесконечном цикле вызываются процедуры с другими запросами.

2021-08-09 15:19 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        if (!isQueryTypeSource(source))
Да, расчет только на типизированный код. В ЗУП даже для типизированного кода почти 900 запросов в цикле.
А как предлагается искать нетипизированный код? Искать у любой переменной вызов Выполнить(), ВыполнитьПакет()? Не будет ли там много ложных срабатываний?

2021-08-09 15:27 UTC, marmyshev commented
> Предлагаю сделать одно исключение опционально. Разрешить для циклов Пока Истина Цикл выполнять запрос вызывая код, но ругаться если в таком бесконечном цикле вызываются процедуры с другими запросами.

Ну тут можно будет ставить локальные исключения `// @skip-check query-in-loop - порционный запрос` - но это потребует доработки кода, что "настоящие программисты" очень не любят 😂

Да, давай тогда этот кейс сделай параметром "Разрешить порционные циклы" - по умолчанию "истина", тогда кому не надо  такое - тот отключит. Но в этом случае надо как-то очень точно анализировать что запрос именно "порционный", чтобы не было ложных срабатываний. Эти кейсы надо бы в документации четко описать - чтобы не было вопросов у разработчика, почему тут ошибка не нашлась.

2021-08-09 15:32 UTC, marmyshev commented
Было бы очень неплохо - в реквесте публиковать сколько в типовых конфигурациях (ЗУП, БП, ERP итд) нашлось таких ошибок.

1. С одной стороны: сразу понятна полезность проверки
2. С другой стороны, если ошибок тысячи/сотнитысяч - то вероятность, что что-то не так в проверке, на это обратить внимание. В любом случае - такая проверка бесполезна при включении по-умолчанию, т.к. столько ошибок никто в здравом уме править не будет по умолчанию.

2021-08-09 15:37 UTC, DoublesunRUS commented
> Да, давай тогда этот кейс сделай параметром "Разрешить порционные циклы" - по умолчанию "истина", тогда кому не надо такое - тот отключит. Но в этом случае надо как-то очень точно анализировать что запрос именно "порционный", чтобы не было ложных срабатываний. Эти кейсы надо бы в документации четко описать - чтобы не было вопросов у разработчика, почему тут ошибка не нашлась.

Поэтому мне и кажется что надо разрешать бесконечные циклы "Пока Истина Цикл". Так как в них явно предусмотрен выход по условию.

2021-08-09 15:38 UTC, DoublesunRUS commented
> Было бы очень неплохо - в реквесте публиковать сколько в типовых конфигурациях (ЗУП, БП, ERP итд) нашлось таких ошибок.
> 
> 1. С одной стороны: сразу понятна полезность проверки
> 2. С другой стороны, если ошибок тысячи/сотнитысяч - то вероятность, что что-то не так в проверке, на это обратить внимание. В любом случае - такая проверка бесполезна при включении по-умолчанию, т.к. столько ошибок никто в здравом уме править не будет по умолчанию.

С одной стороны 1С:Специалист по платформе не получить при одном запросе в цикле. А с другой выключим проверку по умолчанию, чтобы разработчики типовых не сильно от этого расстраивались. :)

2021-08-09 15:44 UTC, marmyshev commented
> > Да, давай тогда этот кейс сделай параметром "Разрешить порционные циклы" - по умолчанию "истина", тогда кому не надо такое - тот отключит. Но в этом случае надо как-то очень точно анализировать что запрос именно "порционный", чтобы не было ложных срабатываний. Эти кейсы надо бы в документации четко описать - чтобы не было вопросов у разработчика, почему тут ошибка не нашлась.
> 
> Поэтому мне и кажется что надо разрешать бесконечные циклы "Пока Истина Цикл". Так как в них явно предусмотрен выход по условию.

Просто "бесконечный цикл с запросом" - это ошибка. А "порционный бесконечный цикл" - это что-то другое, но как разделять - я об этом как раз писал.

Если ты предлагаешь не проверять просто "бесконечные циклы с запросом" (если порционность слишком сложно или дорого определять) - то это быстро сделать - можно пойти супер-простым путем - параметр называть "Проверять запросы в бесконечных циклах" (по умолчанию "ложь").

2021-08-09 15:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        if (!isQueryTypeSource(source))
Вот я и предлагаю сделать это параметризированным. По умолчанию это будет отключено.

Конкретный проект, будет себе включать это, если захочет. Если оценит что для него лучше искать в нетипизированном коде, чем пропускать такие ошибки наружу.

2021-08-09 21:36 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        if (!isQueryTypeSource(source))
Синтаксис помощник показывает 11 разных вариантов где может встретиться слово Выполнить. Я предлагаю первую версию выпустить для типизированного кода. А потом уже смотреть, нужен ли кому-то нетипизированный.

2021-08-09 21:51 UTC, DoublesunRUS commented
Типовой ЗУП суммарно содержит 20 тыс. ошибок и предупреждений. Будет теперь не 20 тыс., а 21 тыс. Я предлагаю для разработчиков типовых ничего не отключать. Пусть используют новый гибкий механизм подавления ошибок чтобы подавлять проверки в тех объектах, над которыми они не работают.

А вот тем кто только начинает новые проекты в EDT, надо включить все проверки. Чтобы они сразу разрабатывали правильно.

2021-08-10 07:25 UTC, marmyshev commented
> Пусть используют новый гибкий механизм подавления ошибок чтобы

Поясни, ты предлагаешь что ты сам пойдешь ко всем разработчикам всех типовых и будешь их убеждать в доработки старого кода? Т.е. ты предлагаешь ничего не делать - даже параметры настройки проверки?

2021-08-10 07:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        Type queryType = (Type)EcoreUtil2.cloneWithProxies((TypeItem)EcoreUtil.resolve(proxyType, object));
Вот тут не понял что предлагается. Считать что proxyType и есть Type? Предварительно его проверив?

2021-08-10 07:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        Type queryType = (Type)EcoreUtil2.cloneWithProxies((TypeItem)EcoreUtil.resolve(proxyType, object));
1. нужно удалить клонирование объекта
2. нужно проверить что `if (proxyType instanceof Type) Type queryType = (Type)EcoreUtil.resolve(proxyType, object);`

2021-08-10 07:52 UTC, DoublesunRUS commented
> > Пусть используют новый гибкий механизм подавления ошибок чтобы
> 
> Поясни, ты предлагаешь что ты сам пойдешь ко всем разработчикам всех типовых и будешь их убеждать в доработки старого кода? Т.е. ты предлагаешь ничего не делать - даже параметры настройки проверки?

Я говорю о том, что сейчас в типовой конфигурации больше 20 тыс. ошибок. И если разработчики типовой не собираются их править, то они их уже как-то выключили. Ровно таким же образом им нужно будет выключать и новые проверки. Я считаю неправильным поставлять именно эту проверку выключенной по умолчанию, так как не вижу чем она отличается от десятка других.

2021-08-10 08:02 UTC, marmyshev commented
> > > Пусть используют новый гибкий механизм подавления ошибок чтобы
> > 
> > 
> > Поясни, ты предлагаешь что ты сам пойдешь ко всем разработчикам всех типовых и будешь их убеждать в доработки старого кода? Т.е. ты предлагаешь ничего не делать - даже параметры настройки проверки?
> 
> Я говорю о том, что сейчас в типовой конфигурации больше 20 тыс. ошибок. И если разработчики типовой не собираются их править, то они их уже как-то выключили. Ровно таким же образом им нужно будет выключать и новые проверки. Я считаю неправильным поставлять именно эту проверку выключенной по умолчанию, так как не вижу чем она отличается от десятка других.

Понял мысль, но кажется есть недопонимание.

1. Я не предлагаю поставлять эту проверку выключенной совсем
2. Я предлагаю ее параметризировать - чтобы была разного рода гибкость в настройке
3. Я предлагаю значения параметров этой проверки - по умолчанию делать таким образом - чтобы массовые срабатывания (которые могут быть ложно-положительными) были по умолчанию отключены в параметрах, чтобы проверка в своем базовом варианте находила только самые достоверные ошибки.

количество текущих легаси-ошибок  в типовых - в этих вопросах (имхо) не должно быть аргументом за то чтобы НЕ делать параметры в этой проверке.

2021-08-10 08:14 UTC, marmyshev commented
Еще, тут прокомментирую, но наверное можно делать в рамках отдельной задачи.

бывают какие-то типовые процедуры которые выполняют запросы, лежащие в общем модуле: например `ОбщегоНазначения.ЗначениеРеквизитаОбъекта()` и прочие.

Поэтому было бы неплохо, указывать в параметрах вызовы каких-то общих процедур специфичных для проекта - список процедур через запятую, что считать вызовом запроса.

2021-08-10 09:49 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        }
Тут у меня была идея что если при определении statementsWithQueryInLoop возникает monitor.cancel, то возвращать пустой список. И соответственно в процедуре выше сразу выходить.

2021-08-10 09:51 UTC, marmyshev requested changes

2021-08-10 09:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +    private static final String PARAM_CHECK_QUERIES_FOR_INFINITE_LOOPS = "checkQueriesForInfiniteLoops"; //$NON-NLS-1$
может быть check Query in infinite loop?  кажется более правильно

2021-08-10 09:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +/**
Джавадок обязателен

2021-08-10 09:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +    protected IRuntimeVersionSupport versionSupport;
- private final
- инжектор нужно перенести в конструктор

2021-08-10 09:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        for (SimpleStatement statement : EcoreUtil2.eAllOfType(module, SimpleStatement.class))
Может быть тут сразу искать Invocation и проверять что это вызов нужного нам метода DynamicFeatureAccess из нашего списка? а уже потом считать типы - это будет очень быстро отсеивать все неподходящие вызовы методов.

2021-08-10 09:51 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/QueryInLoop/src/Configuration/Configuration.mdo
> +  <compatibilityMode>8.3.16</compatibilityMode>
Режим совместимости зачем-то оставлен?

2021-08-10 11:07 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        if (!(methodAccess instanceof DynamicFeatureAccess))
Нет, тут нельзя сразу проверять что имя метода - "выполнить" от запроса. По крайней мере в текущей реализации.
Потому что в сложных конструкциях вида Запрос.Выполнить().Выбрать(), сначала мы получим метод Выбрать(), затем он рекурсивно будет искать Выполнить(), а когда уже поймет что это первый метод от запроса, то проверит его на совпадение.

2021-08-10 11:36 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +            return isQueryExecutionExpression(source, queryExecutionMethods);
Рекурсии тут не получится, рано или поздно мы упремся в то, что больше нет выражения и получим Ложь.
Но не работает другой пример:
ПолучитьЗапрос().Выполнить().Выбрать()
Я для него добавил новую проверку и доработал код чтобы проверка находила такие проблемы.

2021-08-11 09:08 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/QueryInLoopCheckTest.java
> +    private static final String PARAM_CHECK_QUERIY_IN_INFINITE_LOOP = "checkQueryInInfiniteLoop"; //$NON-NLS-1$
нужно разместить в шапке класса

2021-08-11 09:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +            if (Boolean.FALSE.equals(checkQueriesForInfiniteLoops) && isInfiniteWhileLoop(loopStatement))
а зачем здесь боксинг checkQueriesForInfiniteLoops и сравнение с объектом?  можно `(!checkQueriesForInfiniteLoops)`

2021-08-11 09:11 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        Set<String> queryExecutionMethods, Boolean checkQueriesForInfiniteLoops, IProgressMonitor monitor)
а зачем здесь боксинг checkQueriesForInfiniteLoops? можно же сразу в параметрах написать `boolean checkQueriesForInfiniteLoops`

2021-08-11 09:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        Boolean checkQueriesForInfiniteLoops = parameters.getBoolean(PARAM_CHECK_QUERIY_IN_INFINITE_LOOP);
1. зачем боксинг?
2. имя переменной можно бы обновить

2021-08-11 09:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        Set<String> queryExecutionMethods, Boolean checkQueriesForInfiniteLoops, IProgressMonitor monitor)
имя переменно можно бы обновить :)

2021-08-11 09:16 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        }
предлагаю тут объединить - чтобы метод getMethodsWithQuery сразу возвращал всю структуру данных, они ведь по раздельности не нужны, верно?

2021-08-11 09:21 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +    private Set<FeatureAccess> getFaWithQueryInLoop(Module module, Map<String, String> methodsWithQuery,
1. getFaWithQueryInLoop - может лучше `getQueryInLoopCallers`? fa, dfa, sfa - как-то не очень удачные сокращения
2. `Set<FeatureAccess>` будет требовать вычисления hash по объектам для проверки уникальности в коллекции. По логике алгоритма получения FA - может ли быть такое что 2 раза встречается 1 и тот же объект? если не может - предлагаю в методе возвращать `Collection< FeatureAccess>` а объект result можно сделать ArrayList

2021-08-11 09:24 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +                StaticFeatureAccess calledMethod = isMethodWithQuery(method, result);
`isMethodWithQuery` - подозрительное название. либо должно возвращать булево либо должно называться `getMethodWithQuery`

2021-08-11 09:28 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +                String errorPath = methodsCalledFromQuery.get(featureAccess.getName());
кажется тут нужно добавлять к errorPath в начало - позицию в модуле для featureAccess по общей функции - тогда всё будет красиво :)

2021-08-11 09:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        ICompositeNode node = NodeModelUtils.findActualNodeFor(object);
Попробуй заменить параметр `EObject object` на `FeatureAccess object` и использовать метод NodeModelUtils.findActualNodeForFeature(object, FEATURE_ACCESS__NAME); может быть он будет возвращать другую более низкоуровневую ноду в которой позиция в строке будет правильно. Предположение...

2021-08-11 09:42 UTC, marmyshev commented
@DoublesunRUS По скольку проверка тяжелая и потенциально опасная (ввиду тысяч/сотентысяч срабатываний) предлагаю пока временно ее поставлять отключенной. Почему:
1. Сможем ее залить сейчас и протестировать на типовых конфигурациях ее производительность, может придумаем как оптимизировать
2. Проекты типа ERP смогут сами осознанно сейчас ее включать, если хотят. Т.к. щас нет возможности легко отфильтровать легаси-код и код библиотек - это будет полезно.
3. В будущем, можем ее включить по умолчанию, если всё будет хорошо.

2021-08-11 10:00 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +                String errorPath = methodsCalledFromQuery.get(featureAccess.getName());
А зачем? У нас ведь сама ошибка указывает на эту функцию. Я посмотрел, мне показалось что так красивее.

2021-08-11 10:19 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/QueryInLoopCheck.java
> +        ICompositeNode node = NodeModelUtils.findActualNodeFor(object);
Не получилось. Оставил номер строки без позиции. Так и быстрее. Плюс проще пользоваться. Нажал Ctrl-L, ввел номер строки и перешел куда надо.

2021-08-11 11:31 UTC, merged