#40 Перенос проверки ОбменДанными.Загрузка в обработчиках событий
1C-Company/v8-code-style pull request #41
Opened 2021-08-13 10:39 UTC by marmyshev

Closes #40

2021-08-13 11:02 UTC, DoublesunRUS requested changes

2021-08-13 11:02 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EventDataExchangeLoadCheck/src/Catalogs/Products/ObjectModule.bsl
> +		return;
Return написано не канонически.

2021-08-16 18:29 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventDataExchangeLoadCheck.java
> +        return DEFAULT_NAMES.contains(method.getName());
мне кажется, что в регистронезависимом языке так не правильно проверять, да в 99% случаев это сработает, но можно же сделать совсем чисто

2021-08-16 18:30 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventDataExchangeLoadCheck.java
> +        return module.getModuleType().equals(ModuleType.OBJECT_MODULE)
это же перечисление их можно сравнивать через ==

2021-08-18 07:26 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventDataExchangeLoadCheck.java
> +        checkCalls.addAll(СALL_FOR_CHECK);
Да, т.к. в параметре содержатся функции внутри которых проверяется на ОбменДанынми.Загрузка - это произвольные пользовательские функции. Но никто не мешает по-честному написать проверку в коде

2021-08-18 07:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EventDataExchangeLoadCheck.java
> +        return DEFAULT_NAMES.contains(method.getName());
Сделал коллекцию регистронезависимой

2021-08-18 08:56 UTC, merged