#36 Проверка наличия представления списка или объект у метаданных
1C-Company/v8-code-style pull request #445
Opened 2021-09-09 18:19 UTC by marmyshev

2021-09-09 21:18 UTC, DoublesunRUS requested changes

2021-09-09 21:18 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/markdown/ru/mdo-object-list-presentation.md
> +Для каждого объекта метаданных (справочник, документ и т.д.) для фичи представления объекта и фичи представление списка проверяется наличие заполненного текста для одной из фич, для кода из основного
Нет слова фича в русском языке. :)

2021-09-09 21:18 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdoObjectListPresentationCheck.java
> +            .features(INFORMATION_REGISTER__RECORD_PRESENTATION, INFORMATION_REGISTER__LIST_PRESENTATION);
Раз уж тут два topObject, может явно каждый отдельно через builder вызывать?
Чтобы было красивее.

2021-09-09 21:18 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +MdoObjectListPresentationCheck_title=Neither Object presentation nor List presentation is not filled
Если в ResourceBundleEditor поставить пробел в описании для обоих языков, затем записать, затем удалить пробел и снова записать. То RBE отформатирует оба файла с сообщениями единообразно.

2021-09-09 21:18 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/MdoObjectListPresentationCheckTest.java
> + */
Это что за огрызок комментария?

2021-09-09 21:18 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.md.itests/workspace/MdoObjectListPresentation/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
Лишние настройки

2021-09-09 21:18 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdoObjectListPresentationCheck.java
> +        }
Раз уж тут есть вставка для расширений, то предлагаю и в тест добавить расширение. И проверять что код работает правильно.

2021-09-10 11:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +MdoObjectListPresentationCheck_title=Neither Object presentation nor List presentation is not filled
Он форматирует только если меняешь английский текст через него :(

2021-09-10 19:07 UTC, merged