#394 Реализована проверка ПустойБлокИсключения
1C-Company/v8-code-style pull request #447
Opened 2021-09-10 10:13 UTC by EightM

Close #394

2021-09-10 10:32 UTC, DoublesunRUS requested changes

2021-09-10 10:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +EmptyExceptStatementCheck_description = Empty except statement
ResourceBundleEditor Plugin умеет автосортировать строки, если через его эти файлы редактировать.

2021-09-10 10:32 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/EmptyExceptStatementCheckTest.java
> +    public void testEmptyExceptStatement() throws CoreException
Раньше Дима был против CoreException, требовал просто Exception.

2021-09-10 10:32 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.17
Все проекты должны быть на 19 платформе

2021-09-10 10:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +It is incorrect to hide the issue from the user and administrator
Не хватает пустых строк между заголовком и текстом.
В русском описании они есть.

2021-09-10 10:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/empty-except-statement.md
> +В случаях когда отсутствующий код в блоке исключения является особенностью проектирования, есть возможность
Нет пустой строки

2021-09-10 10:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +            .issueType(IssueType.WARNING)
А почему Предупреждение?
Это разве не стандарт кодирования?

2021-09-10 10:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +        var tryExceptStatement = TryExceptStatement.class.cast(object);
Checkstyle, который входит в состав плагина, должен не пропускать такое.
Ты проверку checkstyle не запускал?

2021-09-10 10:32 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/src/Configuration/Configuration.mdo
> +  <defaultLanguage>Language.Русский</defaultLanguage>
Вроде Дима против русского языка.

2021-09-10 10:34 UTC, marmyshev requested changes

2021-09-10 10:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +EndTry;
а почему это не правильно? вроде в русской версии - это как раз правильный вариант.

2021-09-10 10:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +## Compliant Solution
Местами Правильный-Неправильны вариант специально поменял?

2021-09-10 10:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +        if (monitor.isCanceled() || !(object instanceof TryExceptStatement))
при подписке на 1 объект - !(object instanceof TryExceptStatement) такую проверку не обязательно делать

2021-09-10 10:38 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/src/Configuration/Configuration.mdo
> +  <defaultLanguage>Language.Русский</defaultLanguage>
В тестах 1C - без разницы конечно (ну может чуть-чуть лучше если будет английский :) 

 А в java коде - нельзя.

2021-09-10 11:38 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +EmptyExceptStatementCheck_description = Empty except statement
Отредактировал и отсортировал через плагин

2021-09-10 11:38 UTC, EightM commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/EmptyExceptStatementCheckTest.java
> +    public void testEmptyExceptStatement() throws CoreException
Изменил обратно на Exception

2021-09-10 11:39 UTC, EightM commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.17
Заменил проект на 19 платформу

2021-09-10 11:39 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +It is incorrect to hide the issue from the user and administrator
Добавил пустые строки

2021-09-10 11:39 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/empty-except-statement.md
> +В случаях когда отсутствующий код в блоке исключения является особенностью проектирования, есть возможность
Добавил

2021-09-10 11:39 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +            .issueType(IssueType.WARNING)
Изменил на CODE_STYLE

2021-09-10 11:39 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +        var tryExceptStatement = TryExceptStatement.class.cast(object);
Не запускал. Теперь буду :)

2021-09-10 11:40 UTC, EightM commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/src/Configuration/Configuration.mdo
> +  <defaultLanguage>Language.Русский</defaultLanguage>
Решили, что допустимо

2021-09-10 11:40 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +EndTry;
Запутался в английских терминах. Поправил

2021-09-10 11:40 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/markdown/empty-except-statement.md
> +## Compliant Solution
Запутался в английских терминах. Поправил

2021-09-10 11:40 UTC, EightM commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +        if (monitor.isCanceled() || !(object instanceof TryExceptStatement))
Убрал проверку

2021-09-10 12:11 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/.project
> +	<name>edt</name>
назови проект EmptyExceptStatement

2021-09-10 12:31 UTC, EightM commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/.project
> +	<name>edt</name>
Поправил

2021-09-10 12:31 UTC, EightM commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/EmptyExceptStatement/src/CommonModules/ОбщийМодуль1/Module.bsl
> +	КонецПопытки;
Добавил в кейс комментарий и пустую строку

2021-09-10 13:03 UTC, marmyshev approved these changes

2021-09-10 13:39 UTC, merged

2021-09-17 07:30 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +    private static final String CHECK_ID = "empty-except-statement";
nls

2021-09-17 16:10 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/EmptyExceptStatementCheck.java
> +    private static final String CHECK_ID = "empty-except-statement";
Я уже добавил