#1 Перенос подсистемы проверок строгой типизации
1C-Company/v8-code-style pull request #448
Opened 2021-09-10 18:32 UTC by marmyshev

Closes #1

2021-09-11 10:58 UTC, DoublesunRUS requested changes

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/statement-type-change.md
> +
Единственное место где нет описания.

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/structure-consructor-value-type.md
> +	// come code...
Тут и далее видимо имелось в виду some code

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/StrictTypeUtil.java
> +    public static boolean hasStrictTypeAnnotation(IFile file) throws CoreException, IOException
Нет javadoc

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/StrictTypeUtil.java
> +                if (!line.startsWith(IBslCommentToken.LINE_STARTER) && !line.isEmpty())
Может эффективнее на пустую строку вначале проверить?

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +    protected AbstractTypeCheck(IResourceLookup resourceLookup, IBslPreferences bslPreferences,
А тут не надо указывать @Inject?

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +        {
Единственное условие, повышается когнитивная сложность, так как есть вложенные конструкции. Надо сразу выходить из метода.

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +            {
Опять единственное условие, внутри есть вложенные конструкции. Надо выходить из метода

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +        else
Ненужный else

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/DynamicFeatureAccessMethodNotFoundCheck.java
> +     */
Это не наследуемый комментарий?

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/FunctionCtorReturnSectionCheck.java
> +        }
Может в одно условие объединить?

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/FunctionCtorReturnSectionCheck.java
> +            }
Если declaredType.isEmpty() то можно сразу на следующий элемент цикла уходить. Не вычислять types и types2.

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/InvocationParamIntersectionCheck.java
> +            }
Может объединить два условия?

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/SimpleStatementTypeCheck.java
> +                Messages.SimpleStatementTypeCheck_Allow_local_Variable_reset_to_Undefined_type);
В остальных местах параметр через отдельный вызов builder.

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/SimpleStatementTypeCheck.java
> +        {
Единственное условие.

2021-09-11 10:58 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/messages_ru.properties
> +#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)
ResourceBundle Editor современный не ставит эту строку внизу, только вверху.
Внизу можно удалять

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/META-INF/MANIFEST.MF
>   com._1c.g5.v8.dt.validation.marker;version="4.0.0",
Нет ограничения

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/resources/strict/doc-comment-field-type.bsl
> +	// emtpy
empty

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/resources/strict/method-param-value-type.bsl
> +	// emtpy
empty

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/resources/strict/property-return-type.bsl
> +Function CostomAction() Export
Custom

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/resources/strict/variable-value-type.bsl
> +	// emtpy
empty

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/CommonModuleStrictTypesTest.java
> + */
Нет шапки

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/strict/check/itests/CommonModuleStrictTypesTest.java
> + */
Нет javadoc

2021-09-11 10:58 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CommonModule/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
Ненужная сортировка

2021-09-11 14:07 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +    protected AbstractTypeCheck(IResourceLookup resourceLookup, IBslPreferences bslPreferences,
1. Это не публичный конструктор - инжектинг работать не будет
2. В абстрактном классе - инжектинг бесполезен - т.к. конструироваться будет из другого класса.

2021-09-17 15:37 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +        else
Почему ненужный?  можно просто возврат или иначе возврат - разницы ведь никакой, усложнения тоже нет.

2021-09-17 15:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/SimpleStatementTypeCheck.java
> +                Messages.SimpleStatementTypeCheck_Allow_local_Variable_reset_to_Undefined_type);
Вроде разницы никакой. Но отдельный вызов делается - когда в цепочке возвращается специализированный билдер под какой-нибудь коллектор.

2021-09-17 16:01 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/DynamicFeatureAccessMethodNotFoundCheck.java
> +     */
Вроде бы комментарий другой. Он же не повторяется.

2021-09-17 17:27 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/check/AbstractTypeCheck.java
> +        else
else ведь тоже +1 к когнитивной сложности.

2021-09-21 10:02 UTC, merged

2021-09-22 08:06 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/dynamic-access-method-not-found.md
> +Система строгой типизации кода проверяет что динамически вызываемый метод существует в объекте
проверяет что -> проверяет, что

2021-09-22 08:06 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/function-return-value-type.md
> +Система строгой типизации кода проверяет что каждая функция возвращает типизированное значение
проверяет что -> проверяет, что

2021-09-22 08:06 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/structure-consructor-value-type.md
> +Проверяет строковый литерал в конструкторе структуры что каждый ключ имеет типзированное значение.
проверяет что -> проверяет, что

2021-09-22 08:06 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/structure-consructor-value-type.md
> +Ключи структуры инициализируются без какого-либо значения по умолчанию что устанавливает пустой тип значения для ключа структуры на всё время жизни.
по умолчанию что -> по умолчанию, что

2021-09-22 08:06 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/variable-value-type.md
> +Система строгой типизации кода проверяет что каждая переменная имеет тип значения
проверяет что -> проверяет, что