#454 НСтр формат строкового литерала
1C-Company/v8-code-style pull request #455
Opened 2021-09-12 21:06 UTC by marmyshev

Closes #454

2021-10-03 08:39 UTC, DoublesunRUS requested changes

2021-10-03 08:39 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/bsl-nstr-string-literal-format.md
> +The string literal in first parameter should not be emty.
empty

2021-10-03 08:39 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/bsl-nstr-string-literal-format.md
> +# НСтр формат строкового литерала
А где русский вариант?

2021-10-03 08:39 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/AbstractSingleModuleTestBase.java
> + * Clients my override the name of the project and path to the module, module id, and the way how to get the module
may

2021-10-03 08:39 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/AbstractSingleModuleTestBase.java
> + * (for example manage module, object module, form module and etc).
manager?

2021-10-04 02:24 UTC, tretyakevich approved these changes

2021-10-04 02:24 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/AbstractSingleModuleTestBase.java
> + * Abstract test base for loading project and usually update it's single module from {@code test.bsl} resource.
Abstract test base which loads a project and updates its single module from a {@code test.bsl} resource if necessary

2021-10-04 02:24 UTC, tretyakevich commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/AbstractSingleModuleTestBase.java
> +     * Clients should override this method if whey need to get module form different path
whey -> they

2021-10-04 09:17 UTC, merged