#319 Метод или переменная доступны на Клиенте
1C-Company/v8-code-style pull request #456
Opened 2021-09-13 07:51 UTC by marmyshev

Closes #319

2021-09-16 13:35 UTC, DoublesunRUS requested changes
А где тесты?

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        boolean isClietnEvent = isClietnEvent(eObject, module);
Client

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        Environments chechingEnvs = bslPreferences.getLoadEnvs(eObject).intersect(Environments.MNG_CLIENTS);
checking

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        "ОбработкаПолученияДанныхВыбора"); //$NON-NLS-1$
А этого списка событий точно нет в недрах EDT?

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        if (!isValidModule(module) || monitor.isCanceled())
Поменять условия местами.

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +            || type == ModuleType.OBJECT_MODULE || type == ModuleType.RECORDSET_MODULE;
А эффективнее это сделать нельзя? Может сравнивать на вхождение в массив?

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java
> +    public static String AccessibilityAtClientInObjectModuleCheck_Method_accessible_at_Client;
почему финальное слово Client с большой буквы?

2021-09-16 13:35 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +AccessibilityAtClientInObjectModuleCheck_title = Метод или переменная доступны на Клиенте
Может здесь указывать еще и имя? Чтобы из сообщения об ошибке было понятно о чем речь.

2021-09-16 14:14 UTC, popoffvg commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        }
Тут регистрозависимое сравнение. Можно ошибиться в одной букве и проверка не сработает.

2021-09-17 19:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +            || type == ModuleType.OBJECT_MODULE || type == ModuleType.RECORDSET_MODULE;
То есть предлагаешь вместо 4 сравнений: сделать массив, вычисление размера массива, новую переменную итератора, операции инкрементации итератора цикл и 4 сравнения? 👍

2021-09-17 19:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        "ОбработкаПолученияДанныхВыбора"); //$NON-NLS-1$
К сожалению нет даже констант с именами.

2021-09-17 19:45 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java
> +    public static String AccessibilityAtClientInObjectModuleCheck_Method_accessible_at_Client;
AtClient - это как бы "НаКлиенте" - может чтоит взять в кавычки как зарезервированное слово-сочетание, хоть так и не правильно говорить...

2021-09-17 19:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +AccessibilityAtClientInObjectModuleCheck_title = Метод или переменная доступны на Клиенте
Там 2 разных сообщения для метода и переменной. А это имя проверки

2021-09-18 08:20 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/Messages.java
> +    public static String AccessibilityAtClientInObjectModuleCheck_Method_accessible_at_Client;
Ну тогда может быть так и писать AtClient?

2021-09-18 08:21 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +            || type == ModuleType.OBJECT_MODULE || type == ModuleType.RECORDSET_MODULE;
Я на всякий случай спросил, может есть более эффективный способ это проверять.

2021-12-13 17:18 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AccessibilityAtClientInObjectModuleCheck.java
> +        "PresentationFieldsGetProcessin",  //$NON-NLS-1$
Я никакого обобщенного типа для всех модулей менеджеров не нашел. Из платформы поставляются типы под каждый менеджер отдельно.

2021-12-14 07:59 UTC, merged

2021-12-15 23:32 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +AccessibilityAtClientInObjectModuleCheck_description = Метод или переменная доступны НаКлиенте в модулях менеджера или объекта
а почему тут не фигурируют другие модули, которые есть в условии - набора записей и сеанса?

2021-12-18 18:26 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +AccessibilityAtClientInObjectModuleCheck_description = Метод или переменная доступны НаКлиенте в модулях менеджера или объекта
Модуль набора записей - это тоже самое что и "модуль объекта".

Про сеанс как мы выяснили - это неактуальность стандарта - из проверки исключен.