#1 перенос правил контрибутинга
1C-Company/v8-code-style pull request #5
Opened 2021-03-13 13:00 UTC by marmyshev

2021-03-13 14:15 UTC, tretyakevich commented on Check_Convention.md
> +3. Ссылку на стандарт следует указывать в секции "См."
Что имеется ввиду?

2021-03-13 14:15 UTC, tretyakevich commented on Check_Convention.md
> +- Любые значения (текстовые, числовые, с большой вариабельностью, кроме Булево) следует задавать через параметры
Жестковато. Тут скорее фокус именно на вариабельности с т.з. логики проверки, а не на любые

2021-03-15 08:06 UTC, DoublesunRUS commented on Check_Convention.md
> +//@skip-ckeck check-method-never-used
cKeck вместо check

2021-03-15 08:07 UTC, DoublesunRUS commented on Check_Convention.md
> +//@skip-ckeck method-never-used
cKeck вместо check

2021-03-15 08:11 UTC, DoublesunRUS commented on Check_Convention.md
> +2. имена параметров пишутся в `CamelCase`, с маленькой буквы
В предыдущем тесте подробно объяснялось что такое cabalCase, тут хотелось бы такого же объяснения про CamalCase.

2021-03-15 08:37 UTC, nixel2007 commented on Check_Convention.md
> +1. Cebab-case (кебаб-кейс) - с маленькой буквы, без пробелов, использовать тире между словами. Не следует использовать `CamelCase` т.к. он менее читабильный.
```suggestion
1. cebab-case (кебаб-кейс) - с маленькой буквы, без пробелов, использовать тире между словами. Не следует использовать `CamelCase` т.к. он менее читабельный.
```

2021-03-15 08:37 UTC, nixel2007 commented on Check_Convention.md
> +3. Преффикс вендора (`v8codestyle`) в коде проверки не используется
```suggestion
3. Префикс вендора (`v8codestyle`) в коде проверки не используется
```

2021-03-15 08:38 UTC, nixel2007 commented on Check_Convention.md
> +4. Константа с кодом проверки должна быть приватной
из описания выше вообще не следует, что код проверки должен быть в константе

2021-03-15 08:39 UTC, nixel2007 commented on Check_Convention.md
> +Не следует отражать в коде проверки - только лишь имен найденных объектов.
```suggestion
Код проверки не должен состоять лишь из имен найденных объектов. 
```

2021-03-15 08:40 UTC, nixel2007 commented on Check_Convention.md
> +Это чуть более атуально для проверок по модулю - т.к. это будет везде визуально читаться.
```suggestion
Это чуть более актуально для проверок по модулю - т.к. это будет везде визуально читаться.
```

2021-03-15 08:40 UTC, nixel2007 commented on Check_Convention.md
> +//@skip-ckeck check-method-never-used
```suggestion
//@skip-check check-method-never-used
```

2021-03-15 08:40 UTC, nixel2007 commented on Check_Convention.md
> +//@skip-ckeck method-never-used
```suggestion
//@skip-check method-never-used
```

2021-03-15 08:42 UTC, nixel2007 commented on Check_Convention.md
> +Тип найденной диагностики
слово "диагностика" встречается только здесь.

2021-03-15 08:42 UTC, nixel2007 commented on Check_Convention.md
> +Тип найденной диагностики
```suggestion
Тип найденной проблемы
```

2021-03-15 08:43 UTC, nixel2007 commented on Check_Convention.md
> +2. имена параметров пишутся в `CamelCase`, с маленькой буквы
```suggestion
2. имена параметров пишутся в `camelCase`, с маленькой буквы
```

2021-03-15 08:44 UTC, nixel2007 commented on Check_Convention.md
> +### Компоненты расширяющие функциональность
```suggestion
### Компоненты, расширяющие функциональность
```

2021-03-15 08:45 UTC, nixel2007 commented on Check_Convention.md
> +При регистрации проверки, следует указывать все фичи от которых зависит логика проверки - это означает, что при изменении любого из второстепенных свойств объекта будет выполнена перевалидация по тек
```suggestion
При регистрации проверки следует указывать все фичи, от которых зависит логика проверки - это означает, что при изменении любого из второстепенных свойств объекта будет выполнена перевалидация по текущей проверке.
```

2021-03-15 08:45 UTC, nixel2007 commented on Check_Convention.md
> +1. Для каждого варианта ошибочного состояния необходим тест, если тестовые ситуации слишком разные желательно различные тесты
```suggestion
1. Для каждого варианта ошибочного состояния необходим тест. Если тестовые ситуации слишком разные, желательно написать различные тесты
```

2021-03-15 13:38 UTC, artbear requested changes
есть предложения по доработке.

но еще не все прочитал )

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +Вначале, хотим поблагодарить Вас за желание участвовать в проекте!
```suggestion
Сразу же хотим поблагодарить Вас за желание участвовать в проекте!
```

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +Будьте благоразумны, если что-либо здесь не описано.
>Будьте благоразумны, если что-либо здесь не описано.
странное предложение.

```suggestion
Если какой-то совет или полезное действие не задокументировано, пожалуйста, создайте `issue`  
```

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +2. Информация в документации проекта
```suggestion
2. Поищите информация в документации проекта
```

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +#### Прежде чем зарегистрировать
```suggestion
#### Прежде чем зарегистрировать ошибку
```

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +#### Прежде чем зарегистрировать
только что был раздел 2го уровня, и сразу же появился раздел 4го уровня

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +4. Опишите ожидаемое поведение
Предлагаю добавить простые шаблоны для Гитхаба

3 вида ишью - ошибка, пожелание, проблема

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +    * Не используйте "метки" в заголовке - для этого существуют сами метки (labels)
```suggestion
    * Не используйте "метки" в заголовке - для этого используются метки (labels) на гитхабе
```

есть проблема с метками гитхаба - их может ставить только контрибьютор с правами в проекте, т.е. не каждый контрибьютор.

и здесь пригодятся шаблоны ишью - в них можно автометки указывать.

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +4. Опишите ожидаемое поведение
с простым чек-листом аналогично текущему списку.

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +3. Убедитесь совместно с авторами проекта, что ваше предложение не противоречит идеологии Стандартов 1С и 1C:EDT. При этом авторы проекта всегда рады обсуждению новых идей, всегда на стороне участник
```suggestion
3. Убедитесь совместно с авторами проекта, что ваше предложение не противоречит идеологии Стандартов 1С и 1C:EDT. При этом авторы проекта всегда рады обсуждению новых идей, всегда на стороне участников, предлагающих улучшения, но при этом постараются максимально разъяснить случаи отказа в принятии идеи/реквеста, если таковые возникнут.
```

- Нет запятой в `на стороне участников, предлагающих улучшения, `
- в конце добавлено `таковые`

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +* Установите в своем PR флажок "allow edits from maintainers"
также хорошо бы сделать шаблоны гитхаба для ПР и вставить туда чек-лист отсюда

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +#<НОМЕР ЗАДАЧИ> Короткое сообщение что сделано
```suggestion
Короткое сообщение о том, что сделано, без номера задачи
```

- обычно места на первой строке маловато
- и хочется показать полезную информацию, а не забивать длинным номером задачи

поэтому номер задачи лучше указать в самом конце длинного сообщения или хотя бы в его начале, если уж так критично.

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +Длинное сообщение что сделано
```suggestion
Длинное сообщение что сделано

#<НОМЕР ЗАДАЧИ> 
```

2021-03-15 13:38 UTC, artbear commented on CONTRIBUTING.md
> +1. Начинаем с номера задачи (например, #12311). Идентификатор необходим для интеграции с задачами GitHub
ну и тут про номер задачи в начале короткой строки

2021-03-15 13:40 UTC, artbear commented on CONTRIBUTING.md
> +* Проверьте [Wiki](https://github.com/1C-Company/v8-code-style/wiki) на наличие описания, что не является ошибкой
@marmyshev точно хотите вести отдельную Вики?
это же неудобно -отдельный проект фактически, в локальном проекте нет этой документации и т.п.

2021-03-15 13:40 UTC, artbear commented on CONTRIBUTING.md
> +Лицензирование расширений размещенных в данном проекте осуществляется на условиях свободной (открытой) лицензии Eclipse Public License - v 2.0 (полный текст лицензии - https://www.eclipse.org/legal/e
```suggestion
Лицензирование расширений, размещенных в данном проекте, осуществляется на условиях свободной (открытой) лицензии Eclipse Public License - v 2.0 (полный текст лицензии - https://www.eclipse.org/legal/epl-2.0/)
```

2021-03-15 13:42 UTC, artbear commented on CONTRIBUTING.md
> +## У меня есть вопрос
т.к. документация длинновата, хорошо бы добавить оглавление для 2-3 уровня.

удобно сделать в vsc с помощью плагина Markdown all in one

2021-03-15 13:46 UTC, artbear commented on Check_Convention.md
> +## Проверка не по стандарту
информацию из этого раздела лучше перенести в корневой readme

Т.к. именно там описаны назначения и ограничения проекта, а эта информация относится к ним.

2021-03-15 13:51 UTC, nixel2007 commented on CONTRIBUTING.md
> +#<НОМЕР ЗАДАЧИ> Короткое сообщение что сделано
Номера задачи из конца сообщения очень неудобно линкуются и не все инструменты связывания коммитов с чем-либо корректно разбирают ссылки из подробного описания. Есть конвенция (номер задачи в начале краткого сообщения), не вижу особого смысла от нее отходить.

2021-03-15 13:55 UTC, artbear commented on Check_Convention.md
> +2. Формат текста: существительное, именительный падеж
примеры ниже не подходят под этот формат "существительное" )

1. Переменная "Ключ" не была инициализирована
2. Конфигурация содержит некорректный режим блокировки данных
3. Метод "РазностьКоллекций" пустой
4. Метод ""ОповещениеЗагрузкиФайлов" не используется
5. Длина имени объекта метаданного должна быть, меньше чем `80` - "ОченьДлинноеИмя...."

```suggestion
2. Формат текста: предложение с указанием имен, на которых выявлена проблема
```

2021-03-15 16:10 UTC, marmyshev commented on CONTRIBUTING.md
> +3. Убедитесь совместно с авторами проекта, что ваше предложение не противоречит идеологии Стандартов 1С и 1C:EDT. При этом авторы проекта всегда рады обсуждению новых идей, всегда на стороне участник
"таковые" - это конечно речевая вкусовщина :)

2021-03-15 16:13 UTC, marmyshev commented on CONTRIBUTING.md
> +Будьте благоразумны, если что-либо здесь не описано.
Тут прям сильно меняеся смысл - хочет, подчеркнуть, что "правил" на все случаи жизни не напасёшься и здравый смысл никто не отменял. К нему придется опилировать в спорных случаях)

2021-03-15 16:24 UTC, marmyshev commented on CONTRIBUTING.md
> +#<НОМЕР ЗАДАЧИ> Короткое сообщение что сделано
Тут важно чтобы номер был первый.
Даже 6 символов - это `#2345 ` (с пробелом) - от обычных 120 или даже 80 - в заголовке - это очень мало съедается, а задач уже до 10К позволяет.

@artbear может есть еще какие-то аргументы в дополнение? хотелось бы обсудить.

2021-03-15 16:25 UTC, marmyshev commented on CONTRIBUTING.md
> +## У меня есть вопрос
Согласен. Жалко GH сам не может генерить(( как некоторые другие...

2021-03-15 16:27 UTC, marmyshev commented on Check_Convention.md
> +## Проверка не по стандарту
В проекте не только "проверки" будут, но и другие инструменты "помогающие" работать по стандартам. Поэтому тут надо оставить конкретно про проверки. А в ридми или контрибьюшн добавить общие ограничения.

2021-03-15 16:32 UTC, marmyshev commented on Check_Convention.md
> +2. Формат текста: существительное, именительный падеж
Да, пункт немного не полностью описан. Но под правило которое на самом деле подразумевалось - все примеры подходят: Переменная, Конфигурация, Метод, Длина - всё существительные, именительный подеж.

Наверное, в дополнение надо написать, что текст должен отвечать на вопрос:
1. Какой объект содержит ошибку? (т.е. в одной строке может быть несколько очень разных объектов.
2. В чем именно ошибка? 

При этом, указание самого наименования объекта - не обзятельно, но желательно - если оно не портит фразу...

2021-05-21 12:33 UTC, merged