#449 Добавлена проверка Аннотация написана канонически
1C-Company/v8-code-style pull request #782
Opened 2021-09-15 15:43 UTC by DoublesunRUS

Добавлена проверка Аннотация написана канонически

2021-09-17 16:43 UTC, marmyshev requested changes

2021-09-17 16:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        PRAGMAS = pragmas;
А зачем тут такая константа? Если есть `Symbols.ANNOTATION_SYMBOLS.contains(annotation)` и там как раз регистро-независимость - тыж сам был против таких констант.

2021-09-17 16:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        if (!pragma.getSymbol().equals(canonicalSymbol))
Предлагаю, добавить тут коммент, что нужно именно регистро-зависимое сравнение строки.

2021-09-17 16:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +                .format(Messages.CanonicalPragmaCheck_Pragma_0_is_not_written_canonically, pragma.getSymbol());
Предлагаю добавить тогда в сообщение еще канонический вариант как должно было быть.

2021-09-17 16:43 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/plugin.xml
> +            class="com.e1c.v8codestyle.internal.bsl.ExecutableExtensionFactory:com.e1c.v8codestyle.bsl.check.CanonicalPragmaCheck">
Назначение этих изменений непонятно в этом реквесте.

2021-09-17 16:43 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CanonicalPragma/.project
> +	<name>CanonicalPragma</name>
А зачем этот проект если он не закружится в тесты? или я не увидел... 
кажется для этих тестов достаточно просто расширение без базового проекта загружать

2021-09-17 16:44 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/plugin.xml
> +            class="com.e1c.v8codestyle.internal.bsl.ExecutableExtensionFactory:com.e1c.v8codestyle.bsl.check.CanonicalPragmaCheck">
По алфавиту проверки в файле

2021-09-17 16:45 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CanonicalPragma/.project
> +	<name>CanonicalPragma</name>
А как EDT без базового проекта ИзменениеИКонтроль сделает? Она же должна сверяться с эталоном.

2021-09-17 16:46 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        PRAGMAS = pragmas;
У меня идея такова.
Ключ - регистронезависимое, значение - каноническое.
Получаем по регистронезависимому ключу каноническое написание.

2021-09-17 16:47 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +                .format(Messages.CanonicalPragmaCheck_Pragma_0_is_not_written_canonically, pragma.getSymbol());
Как сообщение об ошибке именно предлагаешь поменять?

2021-09-17 17:28 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        PRAGMAS = pragmas;
Ну так это ведь уже есть в самой коллекции - объект по equals регистронезависимый - но у него есть свойство getString() которое регистрозависимая строка.

Твой ведь аргумент - когда платформа добавит новую аннотацию - тебе поддерживать?

2021-09-17 17:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        PRAGMAS = pragmas;
Или хотяб можно было сделать трансформацию исходной коллекции в то что тебе нужно.

Типа

Private final Map... PRAGMA = ANNOTATION_SYMBOLS.stream().map(Collectors.toMap(e -> e, e -> e.getString()));

Имхо, считаю что можно было бы и без такого обойтись, но это лучше чем самому создавать коллекцию

2021-09-17 17:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +                .format(Messages.CanonicalPragmaCheck_Pragma_0_is_not_written_canonically, pragma.getSymbol());
Нужно чтобы было сообщение:

У вас ошибки тут "..." бла-бла, а правильно так "..." вот..

Чтобы из сообщения было максимально легко догадаться как исправить

2021-09-17 17:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/plugin.xml
> +            class="com.e1c.v8codestyle.internal.bsl.ExecutableExtensionFactory:com.e1c.v8codestyle.bsl.check.CanonicalPragmaCheck">
Зачем? Разве в этом есть хоть какой-то смысл с точки зрения плагина?

2021-09-17 17:35 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CanonicalPragma/.project
> +	<name>CanonicalPragma</name>
Может я не увидел, а где в тесте ты загружаешь базовую конфигурацию в воркспейс?

2021-09-17 17:37 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/CanonicalPragma/.project
> +	<name>CanonicalPragma</name>
Я думал что EDT сама это делает. Ведь у неё есть ссылка на базовый проект.
Мне в любом случае расширение надо было создать в режиме разработчика, а там я это делал через создание основной конфигурации.

2021-09-18 07:51 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CanonicalPragmaCheck.java
> +        PRAGMAS = pragmas;
Про getString() не понял. Стоит задача - получить каноническое описание аннотации. Из Set нельзя получить какой-то элемент, если не сконвертировать этот сет во что-то еще. А если нужно конвертировать, то нет смысла его использовать.

```
PRAGMA = ANNOTATION_SYMBOLS.stream().map(Collectors.toMap(e -> e, e -> e.getString()));
```

Этот код Eclipse считает невалидным.

2021-09-18 10:22 UTC, marmyshev approved these changes
Там только не по русски фраза написана

2021-09-18 10:22 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +CanonicalPragmaCheck_description = Проверка аннотация написана канонически
```suggestion
CanonicalPragmaCheck_description = Проверяет что аннотация метода написана канонически
```

2021-09-18 10:30 UTC, merged