#458 Использование &ИзменениеИКонтроль вместо &Вместо
1C-Company/v8-code-style pull request #785
Opened 2021-09-18 16:40 UTC by DoublesunRUS

Использование &ИзменениеИКонтроль вместо &Вместо

Closes #458

2021-09-18 19:05 UTC, marmyshev requested changes
Название класса проверки и теста соответственно

2021-09-18 19:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ChangeAndValidateInsteadOfAround.java
> +public class ChangeAndValidateInsteadOfAround
Слово Check можно бы добавить

2021-09-18 19:57 UTC, merged

2021-09-22 07:59 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ChangeAndValidateInsteadOfAroundCheck_Use_ChangeAndValidate_instead_of_Around = It's recommended to use pragma &ChangeAndControl instead of &Around
она же называется "ChangeAndValidate"

2021-09-22 07:59 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ChangeAndValidateInsteadOfAroundCheck_description = Checks that pragma &ChangeAndControl is used when there is no call ProceedWithCall
она же называется "ChangeAndValidate"

2021-09-22 07:59 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ChangeAndValidateInsteadOfAroundCheck.java
> +        for (StaticFeatureAccess sfa : EcoreUtil2.eAllOfType(method, StaticFeatureAccess.class))
быстрее было бы искать invocation, у которых MethodAccess это StaticFeatureAccess с определенным именем