Feature/431 mdo sheduled job description
1C-Company/v8-code-style pull request #786
Opened 2021-09-18 18:25 UTC by kuzja086

2021-09-18 18:32 UTC, DoublesunRUS requested changes

2021-09-18 18:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobDescriptionCheck.java
> +    }
Конструктор который ничего не делает, не нужен.

2021-09-18 18:32 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/ScheduledJobDescriptionCheckTest.java
> + */
Нет комментария

2021-09-18 18:32 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.md.itests/workspace/ScheduledJobs/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
Плагин по умолчанию добавляет этот файл, надо удалять.

2021-09-18 18:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/.settings/org.eclipse.core.resources.prefs
> +encoding//src/com/e1c/v8codestyle/md/check/messages_ru.properties=UTF-8
Лишнее

2021-09-18 18:32 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobDescriptionCheck.java
> +package com.e1c.v8codestyle.md.check;
нет шапки

2021-09-18 18:34 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobDescriptionCheck.java
> +        if (monitor.isCanceled() || !(object instanceof EObject))
Ненужная проверка на EObject.
У тебя проверка и так ограничена типом ScheduledJob. Значит ничего другого там не придет.

2021-09-18 18:39 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/.settings/org.eclipse.core.resources.prefs
> +encoding//src/com/e1c/v8codestyle/md/check/messages_ru.properties=UTF-8
Можно в настройках изменить.

- ResourceBundle Editor
   - Кодировка `*.properties` файлов UTF-8 `Preferences -> General -> Content types -> Text -> Java properties File` измените `Default encoditng = UTF-8`
   - Отключить конвертацию юникода в ХХХ `Preferences -> ResourceBundle Editor -> Formatting -> Convert unicode values to \uXXXX`

2021-09-18 18:51 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle/plugin.launch
> -<?xml version="1.0" encoding="UTF-8" standalone="no"?>
А это изменение зачем?

2021-09-18 18:51 UTC, DoublesunRUS commented on targets/default/default.target
>  <!-- EDT -->
А это изменение зачем?

2021-09-18 18:53 UTC, marmyshev requested changes

2021-09-18 18:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/mdo-scheduled-job-description.md
> +predefined sheduled job.
```suggestion
Description of predefined Scheduled jobs should not be set. 
Instead, it is enough to set only synonym for a predefined scheduled job.
```

2021-09-18 18:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobDescriptionCheck.java
> + * The Class MdScheduledJobDescriptionCheck.
это можно стереть - автогенерируемая строка.

2021-09-18 18:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobDescriptionCheck.java
> +        if (predefined && !StringUtils.isBlank(description))
тут можно было бы сразу в `if(mdObject.isPredefined() && !...` но не настаиваю :)

А `Boolean predefined ` - с большой буквы писать Boolean - тогда когда тебе нужно проверять это как объект на null например. В EMF обычно не имеет смысла - т.к. там всегда есть какое-то значение.

2021-09-18 18:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/plugin.launch
> -    <booleanAttribute key="automaticValidate" value="false"/>
А зачем удаление файла? просьба откатить

2021-09-18 18:53 UTC, marmyshev commented on targets/default/default.target
> -<unit id="com._1c.g5.v8.dt.diagram.framework.feature.feature.group" version="0.0.0"/>
Какой-то косяк с изменением таргета? смысла в изменениях нет.

2021-09-18 18:53 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/itests/ScheduledJobDescriptionCheckTest.java
> + */
Копирайт

2021-09-21 10:14 UTC, marmyshev approved these changes

2021-09-21 10:15 UTC, merged

2021-09-22 08:01 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +MdScheduledJobDescriptionCheck_description = The description of the predefine sheduled job is set
sheduled  -> scheduled

2021-09-22 08:01 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +MdScheduledJobDescriptionCheck_message = The description of the predefine sheduled job is set
sheduled -> scheduled

2021-09-22 08:01 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/messages.properties
> +MdScheduledJobDescriptionCheck_title = The description of the predefine sheduled job is set
sheduled -> scheduled