#178 Реализована проверка "Использования ДЛЯ ИЗМЕНЕНИЯ"
1C-Company/v8-code-style pull request #811
Opened 2021-09-28 16:55 UTC by EightM

close #178

2021-09-28 17:09 UTC, DoublesunRUS requested changes

2021-09-28 17:09 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.core.platform;version="10.4.0",
Нет ограничения версии

2021-09-28 17:09 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.wiring.binder;version="1.1.0",
Аналогично

2021-09-28 17:09 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +        }
Проверка первой строкой не нужна

2021-09-28 17:09 UTC, DoublesunRUS commented on tests/com.e1c.v8codestyle.ql.itests/workspace/ForUpdateUsing/.settings/com.e1c.v8codestyle.autosort.prefs
> +eclipse.preferences.version=1
Ненужный файл

2021-09-28 17:09 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +    public ForUpdateUsingCheck(IConfigurationProvider provider)
JavaDoc

2021-09-28 18:21 UTC, marmyshev requested changes

2021-09-28 18:21 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +public class ForUpdateUsingCheck
Название по английски как-то не очень корректно.

в названии ты вот правильно пишешь " Using "FOR UPDATE" "

а класс решил наоборот назвать. Предлагаю переименовать: `UsingForUpdateCheck` (см. выше JavaDoc - тоже)

2021-09-28 18:21 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +    private static final String CHECK_ID = "ql-for-update-using"; //$NON-NLS-1$
аналогично, если согласен с переименованием - `ql-using-for-update`

2021-09-28 18:21 UTC, marmyshev commented on tests/com.e1c.v8codestyle.ql.itests/src/com/e1c/v8codestyle/ql/check/itests/ForUpdateUsingTest.java
> +        long id = object.bmGetId();
Просто глянь TempTableHasIndexTest - может будет удобнее тестировать не через форму - а просто загрузить QL ресурс и направить валидатор. Я хотел сделать пустой проект для таких целей. Правда может показаться что действий чуть больше. Но скорость работы теста будет значительно выше.

Не настаиваю конечное :)

2021-09-28 18:24 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.core.platform;version="10.4.0",
Какой версией ограничивать сверху?

2021-09-28 18:25 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +        }
Почему?

2021-09-28 18:26 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +    public ForUpdateUsingCheck(IConfigurationProvider provider)
Джава док для чего? Для конструктора?

2021-09-28 18:51 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.core.platform;version="10.4.0",
11

2021-09-28 18:51 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.wiring.binder;version="1.1.0",
2

2021-09-28 18:53 UTC, DoublesunRUS commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +        }
Если проверку прервали в самом начале, то она просто не запустится.
Если у тебя нет долгих алгоритмов, проверяй в самом конце перед добавлением ошибки

2021-09-29 10:49 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.core.platform;version="10.4.0",
добавил

2021-09-29 10:49 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/META-INF/MANIFEST.MF
> + com._1c.g5.wiring.binder;version="1.1.0",
добавил

2021-09-29 10:49 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +        }
убрал вообще по совету Димы

2021-09-29 10:49 UTC, EightM commented on tests/com.e1c.v8codestyle.ql.itests/workspace/ForUpdateUsing/.settings/com.e1c.v8codestyle.autosort.prefs
> +eclipse.preferences.version=1
удалил

2021-09-29 10:49 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +public class ForUpdateUsingCheck
Поправил

2021-09-29 10:51 UTC, EightM commented on bundles/com.e1c.v8codestyle.ql/src/com/e1c/v8codestyle/ql/check/ForUpdateUsingCheck.java
> +    private static final String CHECK_ID = "ql-for-update-using"; //$NON-NLS-1$
Поправил

2021-09-29 10:51 UTC, EightM commented on tests/com.e1c.v8codestyle.ql.itests/src/com/e1c/v8codestyle/ql/check/itests/ForUpdateUsingTest.java
> +        long id = object.bmGetId();
Посмотрел. В текущей проверка так оставлю, в будущих уже по другому

2021-09-29 10:52 UTC, EightM commented
> @EightM добавишь запись в CHANGELOG?

Добавил

2021-10-01 10:43 UTC, merged