На проверку
1C-Company/v8-code-style pull request #864
Opened 2021-11-02 08:44 UTC by wwall

## Что сделано
Добавлена проверка на то что синоним, имя или комментарий содержат букву Ё (если язык по умолчанию равен ru)
## Чек-лист

Общее:
- [X] ветка PR обновлена из `master` и нет конфликтов
- [X] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [X] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [X] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [X] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [X] Пользовательская документация на доп.инструменты написана (на русском)
- [X] Описание проверок - на двух языках

## Закрываемые задачи

Closes #462 

@1C-Company @marmyshev прошу сделать аудит

2021-11-02 10:31 UTC, wwall commented
@1C-Company @marmyshev прошу сделать аудит

2021-11-03 14:48 UTC, marmyshev commented
@wwall Обновись из мастера - я поправил проблемку

2021-11-04 17:53 UTC, marmyshev requested changes
Спасибо за реквест!

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +    private static final String CHECK_ID = "md-cyryllic-yo-letter"; //$NON-NLS-1$
cyryllic  -> cyrillic

2021-11-04 17:53 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/MdCyrillicYoLetterInPropertyTest.java
> +     * Test MD-Object has cyryllic yo letter in name
cyryllic  -> cyrillic

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .features(MD_OBJECT__NAME);
Надо регистрировать все фичи которые проверяются - коммент, синоним - всё что через `object.get...()`

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .checkTop()
А что, реквизиты не будут теперь проверяться?

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .checkTop()
Кстати, еще есть стандартные реквизиты... но возможно стоит сделать отдельным реквестом

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        String languageCode = project.getDefaultLanguage().getLanguageCode();
Это не совсем достоверно. Конфигурация может быть на английском, но иметь русский язык как дополнительный. Или некоторые есть любители основной язык поменять на что-то другое (когда конфигурация действительно на русском была написана, но потом поменяли) - синонимы русский наверное, правильно было бы проверять всё равно.

2021-11-04 17:53 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/MdCyrillicYoLetterInPropertyTest.java
> +    private static final String CHECK_ID = "md-cyryllic-yo-letter"; //$NON-NLS-1$
cyryllic -> cyrillic

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/ru/md-cyryllic-yo-letter.md
> +# Имя, комментарий или синоним не дожны содержать букву "Ё".
cyryllic -> cyrillic

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/md-cyryllic-yo-letter.md
> +# The name, comment, or synonym should not contain the letter "Ё".
cyryllic -> cyrillic

2021-11-04 17:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        String languageCode = project.getDefaultLanguage().getLanguageCode();
Но на твоё усмотрение. Переделка не сложная.

2021-11-08 07:26 UTC, wwall commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .features(MD_OBJECT__NAME);
т.е. должно быть так 
.features(MD_OBJECT__NAME, MD_OBJECT__SYNONYM, MD_OBJECT__COMMENT);
?

2021-11-08 07:26 UTC, wwall commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .checkTop()
А как регистрировать реквизиты? Есть пример?

2021-11-08 07:27 UTC, wwall commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        String languageCode = project.getDefaultLanguage().getLanguageCode();
Тогдаполучается на язык не обращаем внимания, и только синоним вытаскиваем по ключу "ru"?

2021-11-08 13:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .features(MD_OBJECT__NAME);
да

2021-11-08 13:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        String languageCode = project.getDefaultLanguage().getLanguageCode();
Нужно пройти по коллекции всех языков конфигурации и проверить, есть ли там "ru", если есть - то проверяем синоним по ключу.  Если не нашли - сразу выход.

Далее еще проверить дефолтный язык = ru? тогда проверяем ещё имя и комментарий.

> Или некоторые есть любители основной язык поменять на что-то другое (когда конфигурация действительно на русском была написана, но потом поменяли) 

Предлагаю на этот кейс забить, т.к. не гоже так делать, ну и отличить этот случая от конфигураций на других языках - не понятно как.

2021-11-11 15:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .checkTop()
<img width="605" alt="image" src="https://user-images.githubusercontent.com/4069973/141321935-df2e6a28-cdfe-45dd-89ca-8416b59adf9f.png">

нужно проверять сам верхнеуровневый МД-объект и все МД-объекты подчиненные.

2021-11-15 08:23 UTC, marmyshev commented
@wwall как дела с реквестом?

2021-11-15 10:58 UTC, wwall commented
> @wwall как дела с реквестом?

@marmyshev, перезжал на новый компьютер. Завтра будет исправленный реквест

2021-11-18 15:15 UTC, marmyshev requested changes

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .features(MD_OBJECT__NAME, MD_OBJECT__SYNONYM, MD_OBJECT__COMMENT);
А зачем это? чем не подходит пример на скрине выше?

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +    public MdCyrillicYoLetterInProperty(IV8ProjectManager v8ProjectManager)
на публичный конструктор нужен документирующий комментарий

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        Boolean hasRuLangSynonym = false;
тут нужно `boolean hasRuLangSynonym = false;` с маленькой буквы

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        Boolean hasRuLang = project.getDefaultLanguage().getLanguageCode().equals(LANG_RU);
Boolean ->  boolean

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        Boolean hasRuLang = project.getDefaultLanguage().getLanguageCode().equals(LANG_RU);
hasRuLang -> `isRuDefaultLanguage` - может быть так будет более понятно?

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        if (Boolean.TRUE.equals(hasRuLang))
`if (hasRuLang)`

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +        if (Boolean.TRUE.equals(hasRuLangSynonym))
`if (hasRuLangSynonym)`

2021-11-18 15:15 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            if (ruSynonym != null && isContainsYoLetter(ruSynonym))
проверка `ruSynonym != null` - тут лишняя - т.к. функция isContainsYoLetter должна корректно учитывать null (собственно она учитывает корректно в StringUtils.isNotEmpty(text) )

2021-11-18 15:15 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/hs_err_pid170258.log
> +
зачем дампы падений JVM в репе? 😊

2021-11-18 15:15 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/MdCyrillicYoLetterInPropertyTestRu.java
> +public class MdCyrillicYoLetterInPropertyTestRu
А почему бы 2 тест-класса не объединить в 1? там ведь можно использовать разные проекты - проект каждый раз загружается для каждого теста.  Если нет - то советую в обоих тестах переключиться с CheckTestBase на SingleProjectReadOnlyCheckTestBase - тесты будут быстрее.

2021-11-18 15:15 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/MdCyrillicYoLetterInPropertyEn/.settings/Default.cset
> +}
не очень нужный файл

2021-11-18 15:15 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/MdCyrillicYoLetterInPropertyRu/.settings/Default.cset
> +  "settings": {}
не очень нужный файл

2021-12-23 21:47 UTC, marmyshev requested changes
Нужно обновиться из мастера

2021-12-23 21:47 UTC, marmyshev commented on CHANGELOG.md
> +- Имя, комментарий или синоним не дожны содержать букву "Ё"
Перенести в раздел версии 0.2

2022-01-11 21:30 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdCyrillicYoLetterInProperty.java
> +            .extension(new TopObjectFilterExtension())
```suggestion
            .extension(new TopObjectFilterExtension())
            .extension(new StandardCheckExtension(getCheckId(), CorePlugin.PLUGIN_ID))
```

2022-01-26 20:49 UTC, marmyshev commented
@wwall ping!

2022-06-24 12:30 UTC, marmyshev commented
@wwall ping!

2023-03-20 12:22 UTC, closed without merging