#374 #486 Проверка на пустые области и вложенные стандартные
1C-Company/v8-code-style pull request #866
Opened 2021-11-02 11:03 UTC by marmyshev

## Что сделано

Добавлены 2 проверки:
- Проверка что область не пустая
- Проверка что стандартная область структуры модуля не является вложенной

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #374 
Closes #486

2021-11-16 06:15 UTC, tretyakevich requested changes

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/IModuleStructureProvider.java
> +    SortedSet<String> getModuleStructureRegions(ModuleType moduleType, ScriptVariant scriptVariant);
Непонятно, зачем возвращать настолько конкретный тип. По идее должна возвращаться Collection. 
Факт того, что возврат идет в порядке описания областей - должен быть отражен в JavaDoc. Возврат SortedSet не равноценен с т.з. документации (а вдруг отсортировано по совершенно неизвестному критерию).

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> + * @author Dmitriy Marmyshev
Публичный пакет - нужна документация по применимости с т.з. проверок, разрабатываемых на базе данной

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +    protected boolean isEmpty(RegionPreprocessor region)
Документация - публичный метод

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +    protected ModuleType getModuleType(EObject context)
Документация - публичный метод

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractModuleStructureCheck.java
> +    protected Optional<RegionPreprocessor> getParentRegion(RegionPreprocessor object)
Документация - публичный метод

2021-11-16 06:15 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            .module()
Не совсем логично получается, общий предок тогда по сути своей не задает природу модульной проверки.

2021-11-19 11:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ModuleStructureTopRegionCheck.java
> +            .module()
Тут 2 раза перекрывать метод за ради одного вызова `.module()` в абстрактом модуле - показалось бессмысленным. Я думаю ни у кого не возникнет желания наследоваться от этой абстракции но при этом делать что-то для других метаданных... (бред же!?)

2021-11-19 13:05 UTC, merged