#427 Добавлена проверка использования метода РольДоступна
1C-Company/v8-code-style pull request #883
Opened 2021-12-17 22:05 UTC by iArtemv

## Что сделано

Добавлена проверка использования метода РольДоступна

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #427

2021-12-18 15:05 UTC, marmyshev requested changes
Обязательно нужен параметр со списком (или регэкс шаблоном) на исключение ролей из проверки.
Нельзя просто так запрещать- есть технические роли для программного управления - их можно было бы вносить в список исключений

2021-12-18 15:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/IsInRoleCheck.java
> +        if (monitor.isCanceled() || !(object instanceof StaticFeatureAccess))
Это лишний код, бесполезный

2021-12-18 15:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +IsInRoleCheck_Use_AccessRight=Use the "AccessRight" method
Сообщение как-то выглядит не полно.
Может: Используйте функцию "ПравоЛоступа()" вместо "РольДоступна()"

2021-12-19 05:57 UTC, marmyshev requested changes

2021-12-19 05:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/isinrole-using.md
> +If AccessRight("Add", Metadata.Catalogs.Client) Тогда ...
Тогда - Then

2021-12-19 05:57 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/isinrole-using.md
> +
Нужна ссылка на английский стандарт с 1c-dn.com или 1ci.com

2021-12-24 06:33 UTC, marmyshev commented on CHANGELOG.md
> +- Использован метод "РольДоступна()".
Перенести в раздел версии 0.2

2021-12-28 16:44 UTC, marmyshev requested changes

2021-12-28 16:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/IsInRoleCheck.java
> +        if (name.equalsIgnoreCase(NAME_RU) || name.equalsIgnoreCase(NAME))
Нет проверки на то, что это метод - а тут может быть локальная переменная или параметр. Я в исходном  сообщении об этом писал.

можно проверить через утилиту `com._1c.g5.v8.dt.bsl.model.util.BslUtil.getInvocation(FeatureAccess) != null`

2021-12-28 16:44 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/IsInRoleCheck.java
> +            .checkedObjectType(STATIC_FEATURE_ACCESS);
Напомню

> Обязательно нужен параметр со списком (или регэкс шаблоном) на исключение ролей из проверки.
Нельзя просто так запрещать- есть технические роли для программного управления - их можно было бы вносить в список исключений

Иначе проверку тупо отключат, пользы не принесет. Программно-проверяемые роли есть во многих конфигурациях...

2021-12-28 17:03 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/IsInRoleCheck.java
> +            .checkedObjectType(STATIC_FEATURE_ACCESS);
в процессе))

2021-12-30 16:03 UTC, merged