#887 Функциональные опции
1C-Company/v8-code-style pull request #891
Opened 2021-12-24 14:36 UTC by marmyshev

## Что сделано

- Добавлены функциональные опции по проекту:
   - Включение проверок по стандартам
   - Проверки не по стандартам
   - Авто-сортировака метаданных
   - Авто-создание структуры модуля
   - Авто-добавление аннотации строгой типизации

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #887

2021-12-25 16:42 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/Messages.java
> +    static
именя полей после _ по-разному, вроде надо с большой

2021-12-25 16:46 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/StrictTypesProjectOptionProvider.java
> +
лишняя пустая строка

2021-12-25 16:52 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/messages.properties
> +
В предложении Template... есть опечатки, my - вероятно may, и что-то должно быть во множественном числе (возможно так Templates for each module type may be customized with a license.

2021-12-25 16:59 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.ui/src/com/e1c/v8codestyle/internal/ui/UiPlugin.java
> +public class UiPlugin
нет автора

2021-12-25 17:01 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.ui/src/com/e1c/v8codestyle/internal/ui/ProjectOptionsDtNewWizardPage.java
> +        GridLayoutFactory.swtDefaults().numColumns(1).applyTo(composite);
может быть такое что колонки не будет?

2021-12-25 17:06 UTC, iArtemv commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/check/CheckUtils.java
> +{
java doc

2021-12-25 17:43 UTC, iArtemv commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/messages.properties
> +StandardChecksProjectOptionProvider_description=Enables all checks by standarts for this project. You can manually enable, disable and configure them later in project properties.
standards

2021-12-27 02:40 UTC, tretyakevich requested changes

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionProvider.java
> +    int getOrder();
Так делать в любом расширяемом решении с самого начала не стоит.
Если без этого никак - то не нужно просто расширения таким образом делать. Нужно делать один централизованный реестр, с единым списком опций в нужном порядке. А в расширениях - ссылку на код.

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionProvider.java
> +    boolean getOption(IProject project);
Название не соответствует никаким стандартным соглашениям. isEnabled, поскольку у тебя есть слово Option в названии интерфейса

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionProvider.java
> +    void saveOption(IProject project, boolean value, IProgressMonitor monitor);
Тоже странновато. Не вижу смысла каждую опцию сохранять уникальным образом. Еще один факт в сторону единого реестра опций.
Если что - сейчас не стоит задачи сделать общий механизм. В таком виде он в любом случае не применим за пределами одной библиотеки.

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/ProjectOption.java
> +    public String getOptionId()
JavaDoc-ов нет здесь и далее

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionManager.java
> +    boolean getOption(IProject project, String optionId);
Неверная семантика. У тебя есть объект "Опция". Если в методе есть слово опция - то и возвращать нужно опцию.
Которая. кстати, должна уметь возвращать свое значение.
Если нужен шорткат - то опять же isEnabled

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionManager.java
> +    void save(IProject project, ProjectOption option, boolean enable, IProgressMonitor monitor);
Ну и здесь - у тебя нельзя получить нужную опцию ни коим образом, кроме как списком всех опций.
А вот чтобы сохранить - нужна опция. 

В общем я бы рекомендовал выбрать что-то одно. Либо у тебя вообще объект "Опция" как таковой уходит, и все его данные получаются через сервис специфичными методами. Что может быть не очень удобно на UI.
Либо объект остается, но он же является основным субъектом операций. 
Вариант "активной" опции не рассматриваю, усложнит решение.

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/check/CheckUtils.java
> +    public static final String PREF_KEY_STANDARD_CHECKS = "standardChecks"; //$NON-NLS-1$
Ну вот и вылезло наглядное доказательство того, что рано еще вводить независимые провайдеры. Вот этим ты залез в их потроха и связал все решение.
Поэтому моя оценка - убирать все эти излишества, делать централизованный реестр опций для код-стайла, заодно решив вопрос с ордерами и прочим.

2021-12-27 02:40 UTC, tretyakevich commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/StandardChecksProjectOptionProvider.java
> +        for (CheckUid checkUid : standardCheckRegistry.getChecks())
Вот это совсем плохо. Ты тут не опцию сохраняешь (опция по всем описаниям и виду - это просто флаг, включаемый/выключаемый). И ты в ее включение добавляешь совершенно чуждую логику, мало того - с неизвестным жизненным циклом.

2021-12-27 09:57 UTC, MaksimDzyuba requested changes

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.autosort/src/com/e1c/v8codestyle/internal/autosort/messages.properties
> +AutoSortProjectOptionProvider_description = Allows automatically to sort top metadata objects of configuration on add new or rename existing.
"objects of configuration on" а зачем последнее on, не понимаю, кажется, что есть описка

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.autosort/src/com/e1c/v8codestyle/internal/autosort/messages.properties
> +AutoSortProjectOptionProvider_description = Allows automatically to sort top metadata objects of configuration on add new or rename existing.
возможно "on add" -> "on adding"

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/messages_ru.properties
> +ModuleStructureProjectOptionProvider_Description = Все стандартные области будут автоматически добавлены в новый модуль. Шаблоны для каждого типа модуля могут быть кастомизировани лицензией или други
странное слово "кастомизировани"

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/messages_ru.properties
> +StrictTypesProjectOptionProvider_description = Эта аннотация будет добавлена в заголовок модуля чтобы активировать строгую проверку типов модуля.
"в заголовок модуля чтобы" -> "в заголовок модуля, чтобы"

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/ProjectOption.java
> +    private int getHashCode()
порядок следования методов

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/ProjectOption.java
> +        result = prime * result + ((optionId == null) ? 0 : optionId.hashCode());
мне не нравится, как тут это написано, ну есть же готовые средства, как это делать, 
зачем "final int prime = 31;" вот зачем final?
Предлагаю все же пользоваться методом java.util.Objects.hash(Object...)

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/check/CommonCheckRegistry.java
> +    public static CommonCheckRegistry getInstance()
java-doc

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/check/StandardCheckRegistry.java
> +    public static StandardCheckRegistry getInstance()
java-doc

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/ProjectOptionManager.java
> +        if (providers == null)
а ты тут не делал проверку  через findBugs, мне кажется что в этом методе он покажет ошибку, так как providers  не volatile, а значит возможно нарушение синхронизациии

2021-12-27 09:57 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/messages_ru.properties
> +CommonChecksProjectOptionProvider_description = Проверки здравого смысла для проекта 1С, не регламентированного стандартами 1С.
кажется, что это как-то не очень "Проверки здравого смысла", можешь пояснить, что хотел вложить в эту фразу?

2021-12-27 10:34 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/messages_ru.properties
> +CommonChecksProjectOptionProvider_description = Проверки здравого смысла для проекта 1С, не регламентированного стандартами 1С.
Например, проверки на неиспользуемую переменную или пустой модуль - это не регламентируется стандартом каким-то, но напрямую следует из здравого смысла что так делать не следует.

Согласен, фраза не очень удачная. Может быть есть предложения как объединить такие проверки в один термин?

2021-12-27 10:35 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/ProjectOption.java
> +        result = prime * result + ((optionId == null) ? 0 : optionId.hashCode());
Это генератор Эклипса. согласен.

2021-12-27 12:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/StandardChecksProjectOptionProvider.java
> +        for (CheckUid checkUid : standardCheckRegistry.getChecks())
Вроде бы это обсуждалось - на включении ФО - включаем проверки, на выключении ФО - выключаем проверки. 
А флаг ФО отдельно сохраняется выше. 

Либо я не понял, что имеется ввиду, что тут плохого?

2022-01-11 12:03 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.ui/src/com/e1c/v8codestyle/internal/ui/ProjectOptionsDtNewWizardPage.java
> +        GridLayoutFactory.swtDefaults().numColumns(1).applyTo(composite);
колонки будут - но какое количество? просто страховка

2022-01-11 12:06 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/IProjectOptionManager.java
> +    void save(IProject project, ProjectOption option, boolean enable, IProgressMonitor monitor);
Добавил метод получения опции по ID

2022-01-11 12:07 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/StandardChecksProjectOptionProvider.java
> +        for (CheckUid checkUid : standardCheckRegistry.getChecks())
Обсудили что оставляем пока текущий вариант

2022-01-11 12:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/messages_ru.properties
> +CommonChecksProjectOptionProvider_description = Проверки здравого смысла для проекта 1С, не регламентированного стандартами 1С.
Переделал фразу немного, надеюсь будет более понятно

2022-01-11 12:09 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/internal/bsl/messages_ru.properties
> +ModuleStructureProjectOptionProvider_Description = Все стандартные области будут автоматически добавлены в новый модуль. Шаблоны для каждого типа модуля могут быть кастомизировани лицензией или други
переделал фразу

2022-01-11 12:10 UTC, marmyshev commented on bundles/com.e1c.v8codestyle/src/com/e1c/v8codestyle/internal/StandardChecksProjectOptionProvider.java
> +        for (CheckUid checkUid : standardCheckRegistry.getChecks())
вынес сохранение в отдельный джоб

2022-01-11 21:21 UTC, merged