Вызов "Заблокировать()" находится вне попытки.
1C-Company/v8-code-style pull request #908
Opened 2022-01-03 20:31 UTC by iArtemv

## Что сделано

Добавлена проверка "Вызов "Заблокировать()" находится вне попытки"

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #396

2022-01-11 12:54 UTC, marmyshev requested changes

2022-01-11 12:54 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java
> +        checkRollbackTransaction(object, resultAceptor, exceptStatements);
А зачем здесь проверка транзакции? вроде бы на транзакции есть отдельный стандарт. Если нет причин (особых) - предлагаю здесь только блокировку в попытке проверять.

2022-01-11 13:51 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java
> +        checkRollbackTransaction(object, resultAceptor, exceptStatements);
Такое требование описано в текущей закрываемой задаче (и соотвественно в правилах на которые идет ссылка в задаче). Поэтому если задачу закрываем, проверка вроде как должна быть.

https://its.1c.ru/db/v8std#content:783:hdoc:1.3
_при использовании вложенных транзакций (см. п. 1.4) в конце блока Исключение рекомендуется добавить оператор ВызватьИсключение.  В противном случае исключение не будет передано выше по стеку вызовов, там не сработает обработка исключения, внешняя транзакция не будет явным образом отменена и платформа вызовет исключение «В данной транзакции происходила ошибка»_

Есть еще задачи #567 #568 - там вроде отличные проверки будут.

2022-01-11 16:56 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java
> +        checkRollbackTransaction(object, resultAceptor, exceptStatements);
Предлагаю тут все задачи рассмотреть и спроектировать нарезку проверок по транзакциям. ну и дата-лок тоже записать. Сможешь завести отельную задачу на анализ со ссылками на те что нужно делать в ЕДТ и спроектировать количество проверок уже согласно модели модуля ЕДТ (не обязательно должна совпадать с проверками АПК)

2022-01-11 21:32 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java
> +            .issueType(IssueType.WARNING)
```suggestion
            .issueType(IssueType.WARNING)
            .extension(new StandardCheckExtension(getCheckId(), BslPlugin.PLUGIN_ID))
```

2022-01-12 17:31 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/LockOutOfTryCheck.java
> +        checkRollbackTransaction(object, resultAceptor, exceptStatements);
завел задачу #919

2022-02-12 17:30 UTC, marmyshev commented
@iArtemv закрываем реквест?

2022-02-12 17:35 UTC, iArtemv commented
закрыл

2022-02-12 17:35 UTC, closed without merging