Найдена экспортная процедура или функция в модуле команды
1C-Company/v8-code-style pull request #910
Opened 2022-01-05 14:33 UTC by iArtemv

## Что сделано

Проверка ограничений на использование экспортных процедур и функций в модуле команды

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-01-05 14:42 UTC, NikitaMikhaylovSB commented
А есть пояснения, что именно проверка делает?
Это вот это? https://its.1c.ru/db/v8std#content:544:hdoc
А как тогда с методами вида ПоказатьВопрос через оповещения будет?

2022-01-05 20:29 UTC, iArtemv commented
> А есть пояснения, что именно проверка делает? Это вот это? https://its.1c.ru/db/v8std#content:544:hdoc А как тогда с методами вида ПоказатьВопрос через оповещения будет?

Хороший вопрос:) надо бы учесть этот момент

2022-01-11 16:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +                nonCheckNames.add(literal.getLines().get(0).replace("\"", "")); //$NON-NLS-1$ //$NON-NLS-2$
у литерала можно использовать метод `literal.lines()` которое возвращает без кавычек

2022-01-11 16:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +            }
Лучше для поиска использовать module.eContents() - с проверкой на NotifyDescription

2022-01-11 16:49 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +            .checkedObjectType(METHOD);
кажется, что будет в этом случае делать один проход по помодулю

2022-01-11 16:50 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> + *     Viktor Gukov - initial API and implementation
Ты Виктор?

2022-01-11 16:50 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExportMethodInCommandModuleCheckTest.java
> + *     Viktor Gukov - initial API and implementation
Ты Виктор?

2022-01-11 16:51 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/CommonCommands/CommonCommand1/CommandModule.bsl
> +Procedure OfferDiscussionsCompletion(Result, Param) Export
пример по сути идентичный тому что выше

2022-01-11 16:51 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +        if (type != ModuleType.COMMAND_MODULE)
формы еще нужно проверять

2022-01-11 16:52 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/export-method-in-command-module.md
> +Do not embed export procedures and functions in modules of commands and common command.
про формы еще

2022-01-11 16:53 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/export-method-in-command-module.md
> +Не следует размещать экспортные процедуры и функции в модулях команд и
про формы не забыть

2022-01-11 21:33 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +            .issueType(IssueType.WARNING)
```suggestion
            .issueType(IssueType.WARNING)
            .extension(new StandardCheckExtension(getCheckId(), BslPlugin.PLUGIN_ID))
```

2022-01-12 12:02 UTC, iArtemv commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/CommonCommands/CommonCommand1/CommandModule.bsl
> +Procedure OfferDiscussionsCompletion(Result, Param) Export
оставил для разнообразия + добавил тест для формы

2022-01-12 14:23 UTC, marmyshev requested changes

2022-01-12 14:23 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandModuleCheck.java
> +    private static final String CHECK_ID = "export-method-in-command-module"; //$NON-NLS-1$
кажется теперь код проверки стал не релевантным. Формы ведь тоже...

Аналогично имя класса и имя класса тестов. и тестовый проект - "Commands" он же не команды проверяет - а экспортные методы в модулях...

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/src/com/e1c/v8codestyle/bsl/check/itests/ExportMethodInCommandModuleCheckTest.java
> +    private static final String PROJECT_NAME = "Commands";
тестовый проект - "Commands" он же не команды проверяет - а экспортные методы в модулях...

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.21
версия должна быть 8.3.19

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
бесполезный файл

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/Catalogs/Products/Commands/TestCommand/CommandModule.bsl
> +	//OpenForm("Products.Products.ListForm", FormParameters, CommandExecuteParameters.Source, CommandExecuteParameters.Uniqueness, CommandExecuteParameters.Window, CommandExecuteParameters.URL);
зачем этот код?

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/Catalogs/Products/Commands/Command/CommandModule.bsl
> +	//OpenForm("Catalog.Catalog.ListForm", FormParameters, CommandExecuteParameters.Source, CommandExecuteParameters.Uniqueness, CommandExecuteParameters.Window, CommandExecuteParameters.URL);
зачем этот код?

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/CommonCommands/CommonCommand/CommandModule.bsl
> +	//OpenForm("CommonForm.", FormParameters, CommandExecuteParameters.Source, CommandExecuteParameters.Uniqueness, CommandExecuteParameters.Window, CommandExecuteParameters.URL);
Зачем этот код?

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/src/CommonCommands/CommonCommand1/CommandModule.bsl
> +	//OpenForm("CommonForm.", FormParameters, CommandExecuteParameters.Source, CommandExecuteParameters.Uniqueness, CommandExecuteParameters.Window, CommandExecuteParameters.URL);
зачем этот код?

2022-01-12 14:23 UTC, marmyshev commented on tests/com.e1c.v8codestyle.bsl.itests/workspace/Commands/.project
> +	<name>Commands</name>
Может проект по названию тест-класса называть если используется SingleProjectReadOnlyCheckTestBase - не предполагается его использовать для чего-то еще.

2022-01-23 22:19 UTC, sfaqer requested changes

2022-01-23 22:19 UTC, sfaqer commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandFormModuleCheck.java
> +            if (containedObject instanceof OperatorStyleCreator
Мне кажется нужно дополнительно исключать экспортные методы формы с префиксом "Подключаемый_", это например активно используется в подсистеме подключаемых команд БСП, и я так понимаю, не противоречит стандарту.

@marmyshev что скажешь?

2022-01-24 23:42 UTC, sfaqer commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandFormModuleCheck.java
> +            if (containedObject instanceof OperatorStyleCreator
Да, парсить все описания оповещений в целом тоже выход, не знаю правда как это на производительности проверки отразится в таком случае.
Вероятно добавление параметра с пропускаемым шаблоном имени метода будет более компромиссным вариантом, но надо конечно тестировать на предмет перфоманса.

2022-01-26 08:51 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandFormModuleCheck.java
> +            if (containedObject instanceof OperatorStyleCreator
Можно в параметре указывать внешние места с инициализацией ОписаниеОповещения

2022-02-08 07:40 UTC, marmyshev requested changes

2022-02-08 07:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/ExportMethodInCommandFormModuleCheck.java
> +        Map<String, Method> exportMethods = new HashMap<>();
Регистро-зависимое сравнение ключа. Либо CaseInsensitiveString в качестве ключа, либо другую коллекцию с регистро-независимым ключом.

2022-02-08 07:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/ru/export-method-in-command-module.md
> +# Ограничения на использование экспортных процедур и функций в модуле команд и форм
имя файла не равно коду проверки

2022-02-08 07:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/markdown/export-method-in-command-module.md
> +# Restrictions on the use of export procedures and functions in a command and form modules
имя файла не равно коду проверки

2022-02-08 09:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages_ru.properties
> +ExportMethodInCommandFormModuleCheck_Notify_description_methods=Методы оповещений
Не понятный параметр

2022-02-08 09:14 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/messages.properties
> +ExportMethodInCommandFormModuleCheck_Notify_description_methods=Notify methods
Не понятный параметр

2022-02-08 15:36 UTC, merged