Feature/38 scheduled job periodicity too short
1C-Company/v8-code-style pull request #916
Opened 2022-01-09 02:07 UTC by RedMammoth

## Что сделано

Реализована проверка периодичности выполнения регламентного задания

## Чек-лист

Общее:
- [x] ветка PR обновлена из `master` и нет конфликтов
- [x] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [x] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [x] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [x] Пользовательская документация на доп.инструменты написана (на русском)
- [x] Описание проверок - на двух языках

## Закрываемые задачи

Closes #38

2022-01-10 08:14 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/META-INF/MANIFEST.MF
> + com._1c.g5.v8.dt.schedule.model;version="2.0.0",
не хватает верхней границы ограничения по версии

2022-01-10 08:15 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +package com.e1c.v8codestyle.md.check;
Copyright

2022-01-10 08:19 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +/** Check mdo ScheduledJobs that a periodicity of execution a job is less than one minute
Док коммент обычно со второй строки
```
/**
 * Text
 *
 * @author
 */
```

2022-01-10 08:20 UTC, iArtemv commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/MdScheduledJobPeriodicityCheckTest.java
> +package com.e1c.v8codestyle.md.check.itests;
copyright

2022-01-10 08:30 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +                feature = DAILY_SCHEDULE__REPEAT_PERIOD_IN_DAY;
в целом писать без скобочек ОК, но конкретно на этом проекте сонар поругается на отсуствие скобочек при сборке

2022-01-10 08:34 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +                Messages.MdScheduledJobPeriodicityCheck_The_periodicity_of_execution_a_shceduled_job_is_less_than_one_minute;
тут наверное необязательно создавать переменную

2022-01-10 08:42 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/markdown/ru/scheduled-job-periodicity-too-short.md
> +
не хватает ссылки на стандарт (на ИТС)

2022-01-10 08:42 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/markdown/scheduled-job-periodicity-too-short.md
> +
ссылку на стандарт можно здесь поискать https://support.1ci.com/hc/en-us/categories/360002267540-1C-Enterprise-Development-Standards

2022-01-10 08:45 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +    extends BasicCheck
если наследование не предполагается обычно лучше класс делать final

2022-01-10 08:46 UTC, iArtemv commented on tests/com.e1c.v8codestyle.md.itests/src/com/e1c/v8codestyle/md/check/itests/MdScheduledJobPeriodicityCheckTest.java
> + *
java doc

2022-01-10 08:48 UTC, iArtemv commented
Имя реквеста не очень красивое) (можно глянуть примеры)

2022-01-11 13:05 UTC, marmyshev requested changes

2022-01-11 13:05 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/MdScheduledJobPeriodicity/.settings/Default.cset
> +}
не очень нужный файл

2022-01-11 13:05 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/MdScheduledJobPeriodicity/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
interval is 1 minute

2022-01-11 13:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/MdScheduledJobPeriodicityCheck.java
> +    private static final int MAX_REPEAT_SEC = 60;
было бы неплохо это в параметры вынести, но тут на твое усмотрение. Т.к. смысл стандарта такой...

просто вдруг кто-то захочет поставить проверку на более чем 60 сек - например не менее 180 сек? :) не настаиваю.

2022-01-11 13:05 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/markdown/ru/scheduled-job-periodicity-too-short.md
> +
на всякий случай - тут нечего написать для примера? копипаст из стандарта...

2022-01-11 13:07 UTC, marmyshev commented
@RedMammoth не корректный текст в описании английском, а так, остальное мелочи - на твое усмотрение.

2022-01-11 20:04 UTC, merged