Небезопасное хранение паролей в информационной базе
1C-Company/v8-code-style pull request #917
Opened 2022-01-11 09:38 UTC by iArtemv

## Что сделано

- Небезопасное хранение паролей в информационной базе.

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #412

2022-01-26 14:41 UTC, marmyshev requested changes

2022-01-26 14:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE, CONSTANT__PASSWORD_MODE);
Регистрация не корректная.
1. не очень хорошо проверять не то, на что регистрировался 
2. Нет реакции на добавление реквизитов (потому что п.1)
3. у каталога и документа - есть общий класс - DB_OBJECT - можно на него подписываться, и добавить регистраторы не специфичные - типа констант.
4. Кажется, что нужно еще на регистр сведений подписываться (на ресурсы и измерения)

2022-01-26 14:41 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            catalog.getTabularSections()
этой фичи нет в регистрации, но если подпишешься на BASIC_FEATURE - тогда и не надо (но проверь иерархию классов)

2022-01-26 14:41 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/UnsafePasswordStorage/DT-INF/PROJECT.PMF
> +Runtime-Version: 8.3.21
версия 8.3.19

2022-01-26 14:41 UTC, marmyshev commented on tests/com.e1c.v8codestyle.md.itests/workspace/UnsafePasswordStorage/.settings/com.e1c.v8codestyle.autosort.prefs
> +topObjects=true
лишний файл

2022-01-27 17:54 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE, CONSTANT__PASSWORD_MODE);
По поводу регистра, в стандарте пишут что вроде в регистре сведений можно (если осторожно)
```
3.1. При этом не следует хранить пароли и другую конфиденциальную информацию в реквизитах тех же
объектов метаданных, с которыми ведется повседневная работа. Для хранения такой информации следует
использовать отдельный объект метаданных (например, регистр сведений), организовав к нему безопасный
доступ на уровне системы прав доступа 1С:Предприятия.
```

2022-01-30 07:38 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            catalog.getTabularSections()
пробовал такой вариант, не сработал, поэтому решил что на basic feature не подписаться
`builder.topObject(BASIC_FEATURE).checkTop().features(BASIC_FEATURE__PASSWORD_MODE)`

2022-02-14 09:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            catalog.getTabularSections()
Нужно подписываться на DB_OBJECT но не ` .checkTop() ` делать - а `.containment(BASIC_FEATURE).features(BASIC_FEATURE__PASSWORD_MODE)`

2022-02-14 09:40 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE, CONSTANT__PASSWORD_MODE);
Щас регистратор с реакцией на фичи -  только на константу. остальные регистраторы - холостые по сути...

2022-02-14 09:40 UTC, marmyshev requested changes
Нужно доделать регистратор корректно. Тогда поменяется код проверки в правильную сторону...

2022-02-15 08:42 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE);
Я говорил о таком варианте, где 2 разных независимых регистратора:

```suggestion
            .extension(new StandardCheckExtension(getCheckId(), CorePlugin.PLUGIN_ID));
        builder.topObject(CONSTANT)
            .checkTop()
            .features(CONSTANT__PASSWORD_MODE);
        builder.topObject(BASIC_DB_OBJECT)
            .containment(BASIC_FEATURE)
            .features(BASIC_FEATURE__PASSWORD_MODE);

```

Единственное, что щас в ЕДТ была ошибка при использовании ТОП-супертипов и контейнмент-супертипов, которую должны были исправить (возможно в релизе или уже в 2022.1) - нужно проверить.

2022-02-15 15:07 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE);
Оказалось что мой вариант не нужен

2022-02-16 07:15 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            .features(BASIC_FEATURE__PASSWORD_MODE, CONSTANT__PASSWORD_MODE);
поправил

2022-02-16 07:16 UTC, iArtemv commented on bundles/com.e1c.v8codestyle.md/src/com/e1c/v8codestyle/md/check/UnsafePasswordStorageCheck.java
> +            catalog.getTabularSections()
поправил

2022-04-16 17:35 UTC, marmyshev commented on CHANGELOG.md
> +- Небезопасное хранение паролей в информационной базе
Нужно будет перенести на 0.3 версию

2022-04-16 17:35 UTC, marmyshev approved these changes

2022-05-12 12:17 UTC, merged