Нарушена схема работы с транзакциями
1C-Company/v8-code-style pull request #922
Opened 2022-01-14 08:24 UTC by iArtemv

## Что сделано

Стандарт 783: Нарушена схема работы с транзакциями: вызов "ЗафиксироватьТранзакцию()" находится вне конструкции "Попытка... Исключение". #567
Стандарт 783: Нарушена схема работы с транзакциями: между "ЗафиксироватьТранзакцию()" и "Исключение" есть исполняемый код, который может вызвать исключение. #568
Стандарт 783: Нарушена схема работы с транзакциями: отсутствует вызов "НачатьТранзакцию()", хотя вызываются "ЗафиксироватьТранзакцию()"/"ОтменитьТранзакцию()". #563 (Зафиксировать)

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-06-24 16:25 UTC, marmyshev requested changes

2022-06-24 16:25 UTC, marmyshev commented on CHANGELOG.md
> +    8. Mежду "Исключение" и "ОтменитьТранзакцию()" есть исполняемый код, который может вызвать исключение
Проверок добавлены 2 а не 8, предлагаю разбить  эти варианты по тем проверкам которые их реально делают - будет более понятно кто-что делает

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +        FeatureAccess featureAccess = inv.getMethodAccess();
тут нужно добавить проверку `featureAccess instanceof StaticFeatureAccess` чтобы не лезло проверять все динамические вызовы

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +        if (!(nameFeature.equalsIgnoreCase(ROLLBACK_TRANSACTION_RU)
опять типичная проблема сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +        if (!(nameFeature.equalsIgnoreCase(COMMIT_TRANSACTION_RU) || nameFeature.equalsIgnoreCase(COMMIT_TRANSACTION)))
опять типичная проблема сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +        FeatureAccess featureAccess = inv.getMethodAccess();
тут нужно добавить проверку featureAccess instanceof StaticFeatureAccess чтобы не лезло проверять все динамические вызовы

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +            if (invocName.equals(BEGIN_TRANSACTION_RU) || invocName.equals(BEGIN_TRANSACTION))
сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +            else if (invocName.equals(ROLLBACK_TRANSACTION_RU) || invocName.equals(ROLLBACK_TRANSACTION))
сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +            if (invocName.equals(BEGIN_TRANSACTION_RU) || invocName.equals(BEGIN_TRANSACTION))
сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +            else if (invocName.equals(COMMIT_TRANSACTION_RU) || invocName.equals(COMMIT_TRANSACTION))
сравнения с константой :)

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +            .checkedObjectType(INVOCATION);
нет привязки к расширению по стандартам

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +            .checkedObjectType(INVOCATION);
нет привязки к расширению по стандартам

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +            if (invocName.equals(ROLLBACK_TRANSACTION_RU) || invocName.equals(ROLLBACK_TRANSACTION))
Сравнение с констатой

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +            if (invocName.equals(COMMIT_TRANSACTION_RU) || invocName.equals(COMMIT_TRANSACTION))
Сравнение с констатой

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +    }
А зачем эта "красота" нужна? можно же просто вызвать метод у объекта `container.getStatements()`

2022-06-24 16:25 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +    }
Полагаю, что неплохо бы дать пояснение в коде - зачем здесь такое шаманство, или может переписать вызовы сразу...

2022-06-27 09:49 UTC, MaksimDzyuba requested changes

2022-06-27 09:49 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +        if (statement instanceof SimpleStatement && ((SimpleStatement)statement).getLeft() != null
нет нужды проверять на null, потом проверять на instanceof, достаточно просто instanceof

2022-06-27 09:49 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +     * @return the all statement
а мы тут в плагинах пишем про то, что может или не может быть Null

2022-06-27 09:49 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +        while (lastStatement instanceof RegionPreprocessorStatement)
а почему учитывается только regionPreprocessor, есть же еще и другие препроцессоры

2022-07-04 09:51 UTC, MaksimDzyuba requested changes

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +     * @return the last statement
лучше написать, что может быть null

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +     * @return the next statement
лучше написать, что может null

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +     * @return the statement from invoc
надо написать, что может null

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/AbstractTransactionCheck.java
> +        if (statement instanceof SimpleStatement && ((SimpleStatement)statement).getLeft() != null
зачем проверять на null, если потом проверять на instanceof

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/CommitTransactionCheck.java
> +    private void analyseExceptPart(Invocation beginTrans, List<Statement> exceptStatement, ResultAcceptor resultAceptor)
что за слово - "analyse", может analyze

2022-07-04 09:51 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/check/RollbackTransactionCheck.java
> +    private void analyseTryPart(Invocation beginTrans, List<Statement> tryStatements, ResultAcceptor resultAceptor)
может analyze

2022-07-05 07:00 UTC, merged