#818 Команда включения строгой типизации
1C-Company/v8-code-style pull request #938
Opened 2022-01-27 07:51 UTC by marmyshev

## Что сделано

Добавляется в контекстное меню:
- в навигатор 1С
- в навигатор файлов (Project Explorer)
- в редактор модуля - подменю Source

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #818

2022-02-03 12:37 UTC, MaksimDzyuba requested changes

2022-02-03 12:37 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/handlers/AddStrictTypeAnnotationHandler.java
> +    private void appedFilesHeirarhically(IResource resource, Collection<IFile> files, IProgressMonitor monitor)
appedFilesHeirarhically -> appendFilesHierarchically

2022-02-03 12:37 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/handlers/AddStrictTypeAnnotationModuleEditorHandler.java
> +            document.modify(new CancelableUnitOfWork<Void, XtextResource>()
не, это все не правильно, ты запускаешь modify транзакцию, хотя даже не уверен, что будешь что-то менять. Зачем она тебе тут нужна, тебе надо в read транзакции найти место вставки, потом создать text change на изменение документа, и применить его, для примера, можно посмотреть механизмы форматирования, шаблонов кода, quick-fix, искать можно по методу 

try (EmbeddedEditorBuffer buffer = new EmbeddedEditorBuffer(context.getXtextDocument()))
                        {
                            NonExpiringSnapshot snapshot = new NonExpiringSnapshot(buffer);
                            BufferChange bufferChange = new BufferChange(change);
                            bufferChange.setBase(snapshot);
                            buffer.applyChange(bufferChange, null);
                        }

2022-02-03 12:37 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/handlers/AddStrictTypeAnnotationModuleEditorHandler.java
> +        if (monitor.isCanceled() || resource.getContents() == null || resource.getContents().isEmpty())
ты работаешь с XtextResource, тебе правда нужен простроенный DerivedState, чтобы понять есть ли комментарий для жесткого типизирования, зачем звать resource.getContents(), можно же просто resource.getParseResult

2022-02-03 12:37 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/StrictTypeUtil.java
> +    public static void setStrictTypeAnnotation(IFile bslFile, IProgressMonitor monitor)
java-doc

2022-02-03 12:37 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/StrictTypeUtil.java
> +                bslFile.setContents(in, true, true, new NullProgressMonitor());
так у тебя же есть нормальный monitor, зачем сюда пустой передавать

2022-02-04 08:00 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.bsl.ui/src/com/e1c/v8codestyle/internal/bsl/ui/handlers/AddStrictTypeAnnotationModuleEditorHandler.java
> +        if (monitor.isCanceled() || resource.getContents() == null || resource.getContents().isEmpty())
Да, переделал

2022-02-04 12:57 UTC, merged