Фикс экспортных методов в форме и команде
1C-Company/v8-code-style pull request #962
Opened 2022-02-11 16:45 UTC by iArtemv

## Что сделано

- Фикс экспортных методов в форме и команде

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-02-12 09:44 UTC, marmyshev commented
@iArtemv предлагаю залить после https://github.com/1C-Company/v8-code-style/pull/967 нужно еще сделать хорошую обвязку для интеграционных тестов на фиксы (хотел сделать отдельной задачей)

2022-02-12 15:14 UTC, iArtemv commented
Да, поэтому и драфт, т.к. пока нет тестов. А еще вопрос в какой раздел добавлять в changelog?

2022-02-14 09:58 UTC, marmyshev requested changes

2022-02-14 09:58 UTC, marmyshev commented on CHANGELOG.md
> +- Удаление ключевого слова Экспорт
может подробней написать, где в каких случаях, для какой проверки в каких модулях? а то не сильно понятно из описания

2022-02-14 13:09 UTC, iArtemv commented on CHANGELOG.md
> +- Удаление ключевого слова Экспорт
для проверки добавлю описание со ссылкой на стандарты, текущее описание расширил

2022-02-14 13:15 UTC, iArtemv commented
Создал задачу: добавить тесты #979 , планируется реализовать после залития API для удобного создания тестов qfix

2022-02-14 13:17 UTC, merged