#941 Квик-фикс для удаления аннотации строгой типизации
1C-Company/v8-code-style pull request #967
Opened 2022-02-12 09:36 UTC by marmyshev

## Что сделано

- Quick-fix для быстрого удаления аннотации строгой типизации

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #941

2022-02-13 08:55 UTC, MaksimDzyuba requested changes

2022-02-13 08:55 UTC, MaksimDzyuba commented on bundles/com.e1c.v8codestyle.bsl/src/com/e1c/v8codestyle/bsl/strict/fix/RemoveStrictTypesAnnotationFix.java
> +    public RemoveStrictTypesAnnotationFix(CheckUid checkId)
java-doc

2022-02-14 08:06 UTC, vadimeg approved these changes

2022-02-14 08:07 UTC, vadimeg approved these changes

2022-02-14 09:43 UTC, merged