855 Проверка form-items-one-event-handler
1C-Company/v8-code-style pull request #998
Opened 2022-02-21 20:18 UTC by RedMammoth

## Что сделано

- Опишите изменения функциональности
- Реализованные проверки кода и метаданных

## Чек-лист

Общее:
- [ ] ветка PR обновлена из `master` и нет конфликтов
- [ ] Тесты-кейсы, JUnit тесты правильного и неправильного состояния
- [ ] Измененные Вами исходники отформатированы в соответствии [с конвенцией](https://github.com/1C-Company/v8-code-style/blob/master/docs/contributing/code_style.md)
- [ ] Авто-аудит (SonarQube и CheckStyle) пройден, покрытие кода хорошее, ошибок нет, плохой код устранен
- [ ] Добавлена запись в [ИСТОРИЮ ИЗМЕНЕНИЯ](https://github.com/1C-Company/v8-code-style/blob/master/CHANGELOG.md), включаемая в пользовательскую документацию плагина

Если применимо:
- [ ] Пользовательская документация на доп.инструменты написана (на русском)
- [ ] Описание проверок - на двух языках

## Закрываемые задачи

Closes #??

2022-02-21 20:25 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +                            resultAceptor.addIssue(event.getEvent().getName(), event,
@marmyshev Подскажи, пожалуйста, пробовал так вешать маркер на событие элемента, никаких значков не появлялось, в поле Location панели ошибок тоже пустота. При двойном клике открывает форму, ни на элементе ни на событии не позиционируется. Перепробовал несколько вариантов, не получается то что я хочу. В идеале хочу получить следующее: в поле Location путь к элементу формы, при двойном клике позционирование на элементе формы/или на событии, а в панеле свойств над проблемным событием маркер

2022-02-23 16:22 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +                    item, FormPackage.Literals.EVENT_HANDLER_CONTAINER__HANDLERS);
здесь вместо item нужно указывать event, а фичу нужно указывать `EVENT_HANDLER__NAME` - это фича имени обработчика.

2022-02-23 16:22 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        }
Это не очень нужный код  - монитор можно по-позже проверять.

2022-06-24 17:48 UTC, marmyshev commented
@RedMammoth ping! тут что-то далается? как-то завис реквест... :) может даже из-за меня?

2022-06-24 19:58 UTC, RedMammoth commented
> @RedMammoth ping! тут что-то далается? как-то завис реквест... :) может даже из-за меня?

У меня было пару проблем, я наверное в телеграме их спрашивал. Сейчас обновлю ветку из мастера и освежу в памяти, то с чем не получилось разобраться. Напишу вопросы в ПР, чтобы не потерялись

2022-06-24 22:30 UTC, RedMammoth commented
@marmyshev Первая проблема, если я вызываю очистку проекта, то в процедуру check ни разу не попадает топовый объект Form, поэтому ошибки не находятся. Ошибки определяются только если изменить какой-нибудь обработчик события в форме/элементах

2022-06-24 22:36 UTC, RedMammoth commented
@marmyshev Второе что мне не нравится: если я при добавлении Issue указываю event и фичу FormPackage.Literals.EVENT_HANDLER__NAME. То при двойном клике на ошибке в панели ошибок открывается форма, но на обработчике не позиционируются, также надо обработчиками не висит маркер, ну и Location пустой. Поэтому если таких ошибок несколько на одной форме, пользователям будет сложно понять, к чему относится каждая:
![image](https://user-images.githubusercontent.com/64589646/175719264-60762b75-19d6-4ab1-890a-c753b2128936.png)

2022-06-26 11:17 UTC, marmyshev requested changes

2022-06-26 11:17 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
В статическое поле нельзя - нужно инжектить сервис через конструктор

2022-06-26 11:17 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final String CHECK_ID = "form-items-one-event-handler"; //$NON-NLS-1$
one = один

single - единственный

Может лучше заменить?

2022-06-26 11:17 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        if (object instanceof Form && object instanceof EObject)
объект Form наследуется от EObject

2022-06-26 11:17 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        builder.topObject(FormPackage.Literals.FORM).containment(FormPackage.Literals.EVENT_HANDLER);
В данном случае - подписка не соответствует тому что хочется обрабатывать.

Поясню, тут 2 разных регистратора:
1. подписывается на объект EventhandlerContainer (без учета модифицируемых фич)
2. дописывается на EventHandler (без учета фич объекта)

Проблемы тут какие:
- здесь нет подписки на форму - а код при этом хочет только форму
- в реакторе на изменения - пользователь может что-то поменять в фичах объекта - проверка не перезапустится (т.к. не описано от каких фич зависит)
- 

Чтобы проверять форму - нужно указать проверяем именно ТОП-объект, а подчиненные не указывать вообще:
`.topObject(FORM).checkTop()`

2022-06-26 11:19 UTC, marmyshev commented
> Второе что мне не нравится: если я при добавлении Issue указываю event и фичу FormPackage.Literals.EVENT_HANDLER__NAME. То при двойном клике на ошибке в панели ошибок открывается форма, но на обработчике не позиционируются, также надо обработчиками не висит маркер, ну и Location пустой. Поэтому если таких ошибок несколько на одной форме, пользователям будет сложно понять, к чему относится каждая:

Это в общем проблема в ЕДТ - нужно регать ошибку на отображение контекста, на редактор форм если не показывают.
ИМХО, правильно вешать ошибку ровно туда где она есть по сути - это на имя обработчика у элемента.

2022-06-26 11:20 UTC, marmyshev commented
> Первая проблема, если я вызываю очистку проекта, то в процедуру check ни разу не попадает топовый объект Form, поэтому ошибки не находятся. Ошибки определяются только если изменить какой-нибудь обработчик события в форме/элементах

Предложил как поправить подписку на объект - мне кажется должно получиться, с учетом того что реакция на изменения подчиненных объектов потом уже делается "расширением"

2022-06-26 14:22 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
Пробовал, не получилось, т.к. не нашел интерфейс. https://t.me/e1c_edt_plugindev/9834
Я могу его создать сам?

2022-06-28 08:31 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        builder.topObject(FormPackage.Literals.FORM).containment(FormPackage.Literals.EVENT_HANDLER);
```suggestion
            .topObject(FormPackage.Literals.FORM)
            .checkTop();
```

2022-06-28 10:58 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
Бывают сервисы без интерфейса - они инжектятся точно так же - создает их локальный инжектор (внутри сервиса ведь могут быть свои зависимости от сервисов  - локальный инжектор их попытается тоже инжектить локально или глобально из регистра OSGi) 

Поэтому самостоятельно создавать не нужно - нужно инжектить.

Отдельный вопрос: 

> как создать (взять класс) из оригинального инжектора в том месте где класс создается? т.е. не из инжектора текущего  плагина.

1. Если нет интерфейса у класса, т.е. это класс - то это верный признак что через OSGi регистр этот сервис не достать.
2. Если плагин того банда - публичный можно попробовать так: 

`private final FormItemInformationService formItemInformationService FormPlugin.getDefault().getInjector().getInstance(FormItemInformationService.class);`

2022-06-29 10:02 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
Вроде должно работать через DI:
Или так:
``
@Inject
private FormItemInformationService infoService;
``

Или, лучше, так (xthtp rjycnhernjh:
``
private final FormItemInformationService infoService;

@Inject
public FormItemsOneEventHandlerCheck(FormItemInformationService infoService) {
    super();
    this.infoService = infoService;
}
``

Только зависимость на сервис форм нужно в манифест добавить. Типа:
``
com._1c.g5.v8.dt.form.service;version="[6.2.0,7.0.0)",
``

2022-06-29 11:55 UTC, vadimeg commented
@RedMammoth You have 2 Checkstyle violations

2022-06-30 00:08 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
Да, спасибо! Добавил еще в зависимости сервис IRuntimeVersionSupport, без него не работал

2022-06-30 00:08 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final String CHECK_ID = "form-items-one-event-handler"; //$NON-NLS-1$
везде заменил

2022-06-30 00:09 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        if (object instanceof Form && object instanceof EObject)
Убрал лишнее

2022-06-30 00:12 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +        builder.topObject(FormPackage.Literals.FORM).containment(FormPackage.Literals.EVENT_HANDLER);
Здесь указал, что проверяем топ объект, чтобы проверка перезапускалась после изменений фич поправил расширение

2022-06-30 04:11 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/markdown/ru/form-items-single-event-handler.md
> +Если одинаковые действия должны выполняться при возникновении событий в разных элементах формы следует:
Перед словом "следует" должна быть запятая

2022-06-30 04:13 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    boolean handlerWasChange(EStructuralFeature feature, BmSubEvent bmEvent)
handlerWasChange**d** или лучше isHandlerChanged

2022-06-30 04:14 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    boolean itemWasRemove(EStructuralFeature feature, BmSubEvent bmEvent)
Тоже самое, isItemRemoved

2022-06-30 04:17 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    public void configureContextCollector(final ICheckDefinition definition)
Двум методам выше добавить модификаторы private и опустить их ниже публичного метода. Сначала должны идти публичные, потом защищенные и в конце приватные

2022-06-30 04:19 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +        else
else не нужен, прост return

2022-06-30 04:21 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +    protected void configureCheck(CheckConfigurer builder)
Поднять метод выше, перед приватными

2022-06-30 04:29 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +        if (monitor.isCanceled() || object == null)
Тут вместо проверки на null лучше отсечь те объекты, у которых не может быть обработчиков:
!(object instanceof EventHandlerContainer)

2022-06-30 04:30 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +        String itemAsString = itemName(item);
itemAsString -> itemName

2022-06-30 04:32 UTC, vadimeg commented on tests/com.e1c.v8codestyle.form.itests/src/com/e1c/v8codestyle/form/check/itests/FormItemsSingleEventHandlerCheckTest.java
> +    private final EList<EventHandler> getHandlersByURI(IBmTransaction transaction, URI uriItem)
Приватный метод вниз

2022-06-30 04:33 UTC, vadimeg requested changes
Требуются изменения

2022-06-30 06:55 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/markdown/ru/form-items-single-event-handler.md
> +Если одинаковые действия должны выполняться при возникновении событий в разных элементах формы следует:
исправил

2022-06-30 06:55 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    boolean handlerWasChange(EStructuralFeature feature, BmSubEvent bmEvent)
исправил

2022-06-30 06:56 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    boolean itemWasRemove(EStructuralFeature feature, BmSubEvent bmEvent)
исправил

2022-06-30 06:58 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/EventHandlerChangeExtension.java
> +    public void configureContextCollector(final ICheckDefinition definition)
исправил

2022-06-30 06:58 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +        else
исправил

2022-06-30 06:58 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsSingleEventHandlerCheck.java
> +    protected void configureCheck(CheckConfigurer builder)
исправил

2022-06-30 06:59 UTC, RedMammoth commented on tests/com.e1c.v8codestyle.form.itests/src/com/e1c/v8codestyle/form/check/itests/FormItemsSingleEventHandlerCheckTest.java
> +    private final EList<EventHandler> getHandlersByURI(IBmTransaction transaction, URI uriItem)
исправил

2022-06-30 09:58 UTC, vadimeg approved these changes

2022-06-30 09:58 UTC, vadimeg approved these changes

2022-07-01 09:25 UTC, marmyshev approved these changes

2022-07-01 09:38 UTC, marmyshev requested changes

2022-07-01 09:38 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        bind(IRuntimeVersionSupport.class).toService();
Уточни, я предлагал сделать биндинг из RSP для FormItemInformationService. Не получилось?
Если не пробовал - то, удали отсюда текущий IRuntimeVersionSupport и добавь FormItemInformationService т.к. IRuntimeVersionSupport возьмется из инжектора плагина форм.

2022-07-01 09:46 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
@vadimeg  В этом случае получается дублирование инстансов сервиса, при этом сервис объявлен @Singleton и внутри у него есть кэширование данных - так что правильный способ тут будет: либо переписать сервис на честный OSGi, либо доставать из RSP

2022-07-01 09:48 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        bind(IRuntimeVersionSupport.class).toService();
@vadimeg обрати внимание - чтобы избежать дублирования сервиса

2022-07-01 12:19 UTC, vadimeg commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
М-да, похоже этот сервис вообще нельзя использовать ( Он и сейчас несколько раз создается

2022-07-01 12:27 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
@marmyshev @vadimeg Я же пробую достать из RSP?

2022-07-01 19:37 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/form/check/FormItemsOneEventHandlerCheck.java
> +    private static final FormItemInformationService formItemInformationService = new FormItemInformationService();
переделал на получение из RSP, проверьте, пожалуйста правильно ли я указал зависимость от javax.inject

2022-07-01 19:38 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        bind(IRuntimeVersionSupport.class).toService();
переделал на биндинг из RSP, правильно ли я указал зависимость от javax.inect?

2022-07-02 14:30 UTC, marmyshev requested changes

2022-07-02 14:30 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        URI uri = URI.createURI("*.bsl"); //$NON-NLS-1$
тут нужно указать расширение форм - `*.form`

2022-07-02 14:32 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        URI uri = URI.createURI("*.bsl"); //$NON-NLS-1$
Да, проглядел, когда копипастил по-новой.  Странно что работает)

2022-07-02 15:02 UTC, marmyshev commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        URI uri = URI.createURI("*.bsl"); //$NON-NLS-1$
То что работает - это просто совпадение - что в инстанс был создан в инжекторе BSL-плагина и там есть зависимость на тот сервис версий платформ

2022-07-02 16:36 UTC, RedMammoth commented on bundles/com.e1c.v8codestyle.form/src/com/e1c/v8codestyle/internal/form/ExternalDependenciesModule.java
> +        URI uri = URI.createURI("*.bsl"); //$NON-NLS-1$
исправил

2022-07-03 07:04 UTC, merged